$axure.loadCurrentPage({
  "url":"信息发布.html",
  "generationDate":new Date(1420531289164.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e907d832d8f4c2082a8945f9c9ef162",
    "type":"Axure:Page",
    "name":"信息发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9565d33e38445e38311e6b547eae18c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"ddfa66233e904e77836290a7d31eb6df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"308735a7464444f3865f989554712648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"8e33b0d3411f4dcf97564c88fc4b15ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea9617f213846539c8a9916083bbed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"a78c945747574fb0927b5970c8dd3147",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":188},
            "size":{
              "width":334,
              "height":487}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d968d8d942714269bc57572234a3651f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"08e5ec151a3e46a59724ba69e3072e49",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "location":{
                      "x":90,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ceb7676446c343eeafe29f69979dda46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "location":{
                          "x":90,
                          "y":0},
                        "size":{
                          "width":120,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u10.png"}},
{
                  "id":"34e819b870b049a2967466ca5e3d31ad",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":132},
                    "size":{
                      "width":306,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b25161390a1c4143b310b8017b16e047",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":132},
                        "size":{
                          "width":306,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u12.png"}},
{
                  "id":"a1278d6a3dce41c0b07ff48c30f3c105",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":145},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8954eb6bf89c4c18b7b348a83c86ff70",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":145},
                        "size":{
                          "width":53,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c2c89c240e6451baa1028e8a1bce6c7",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":145},
                    "size":{
                      "width":150,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c7f0b5db7b148f9a1c17959028d1852",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":145},
                        "size":{
                          "width":150,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"923ab893c5734e828568955fc145842f",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":189},
                    "size":{
                      "width":306,
                      "height":222},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d13ade9216c40f38634fb15bf907e83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":189},
                        "size":{
                          "width":306,
                          "height":222},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u18.png"}},
{
                  "id":"6d707529c04345af995d57c48c45daab",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":201},
                    "size":{
                      "width":64,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c1c387733c94d44a23edfac55b52f3b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":201},
                        "size":{
                          "width":64,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8b74fffcbe4346f681356dc09bc8eca2",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":201},
                    "size":{
                      "width":150,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb534886ccba4bf089b9cc71a7c287a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":201},
                        "size":{
                          "width":150,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8d00298e36a64a1ea83079670e74ce10",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":423},
                    "size":{
                      "width":306,
                      "height":89},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73991f90a4ed4b6980fc2e0610681d25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":423},
                        "size":{
                          "width":306,
                          "height":89},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u24.png"}},
{
                  "id":"4420e732d067409991c2be8086bdd201",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":435},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"568cf306f4d8415bb1511b62d422e898",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":435},
                        "size":{
                          "width":53,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9e4414a89175415d8b5e6194b35c27ce",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":435},
                    "size":{
                      "width":150,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ec7eebac2984dbb88c69ddde82a5c37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":435},
                        "size":{
                          "width":150,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"47b72f1f11db4652a1372a8b73372023",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":525},
                    "size":{
                      "width":306,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72eadcfcf4754734b9889d58d3ffd18e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":525},
                        "size":{
                          "width":306,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u12.png"}},
{
                  "id":"da447acd1290405494d1742beefaa6e7",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":538},
                    "size":{
                      "width":53,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1822833be9cf4d92a61b8ecce8503a01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":538},
                        "size":{
                          "width":53,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fea3c42bda8e43de86d42545206a301b",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":538},
                    "size":{
                      "width":150,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2315bb09701b455bb1784549fbdb1e67",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":538},
                        "size":{
                          "width":150,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"25e023d6279f4ce292c3f2a11466a381",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":570},
                    "size":{
                      "width":306,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"363ce02718054c80b4ab71f1650f40f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":570},
                        "size":{
                          "width":306,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/信息发布/u12.png"}},
{
                  "id":"524f63402da54a089a4fc615ba1f43ec",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":583},
                    "size":{
                      "width":64,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87a49cb01ee54dd7a1dbec2e8ea02d36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":583},
                        "size":{
                          "width":64,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"806f4d60881e4784afc17f91107d034b",
                  "label":"",
                  "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":583},
                    "size":{
                      "width":150,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd51ef0fae4243599cf1fc3d6a3cd427",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a78c945747574fb0927b5970c8dd3147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":583},
                        "size":{
                          "width":150,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a564eca91ec3495582813acac143fc4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0D7AFF,
              "opacity":1},
            "location":{
              "x":306,
              "y":147},
            "size":{
              "width":32,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace0bed20e2749efaa7b94ccec6a9aa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0D7AFF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":147},
                "size":{
                  "width":32,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "d9565d33e38445e38311e6b547eae18c":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "ddfa66233e904e77836290a7d31eb6df":{
      "scriptId":"u5"},
    "308735a7464444f3865f989554712648":{
      "scriptId":"u6"},
    "8e33b0d3411f4dcf97564c88fc4b15ac":{
      "scriptId":"u7"},
    "5ea9617f213846539c8a9916083bbed0":{
      "scriptId":"u8"},
    "a78c945747574fb0927b5970c8dd3147":{
      "scriptId":"u9"},
    "08e5ec151a3e46a59724ba69e3072e49":{
      "scriptId":"u10"},
    "ceb7676446c343eeafe29f69979dda46":{
      "scriptId":"u11"},
    "34e819b870b049a2967466ca5e3d31ad":{
      "scriptId":"u12"},
    "b25161390a1c4143b310b8017b16e047":{
      "scriptId":"u13"},
    "a1278d6a3dce41c0b07ff48c30f3c105":{
      "scriptId":"u14"},
    "8954eb6bf89c4c18b7b348a83c86ff70":{
      "scriptId":"u15"},
    "5c2c89c240e6451baa1028e8a1bce6c7":{
      "scriptId":"u16"},
    "4c7f0b5db7b148f9a1c17959028d1852":{
      "scriptId":"u17"},
    "923ab893c5734e828568955fc145842f":{
      "scriptId":"u18"},
    "8d13ade9216c40f38634fb15bf907e83":{
      "scriptId":"u19"},
    "6d707529c04345af995d57c48c45daab":{
      "scriptId":"u20"},
    "3c1c387733c94d44a23edfac55b52f3b":{
      "scriptId":"u21"},
    "8b74fffcbe4346f681356dc09bc8eca2":{
      "scriptId":"u22"},
    "fb534886ccba4bf089b9cc71a7c287a1":{
      "scriptId":"u23"},
    "8d00298e36a64a1ea83079670e74ce10":{
      "scriptId":"u24"},
    "73991f90a4ed4b6980fc2e0610681d25":{
      "scriptId":"u25"},
    "4420e732d067409991c2be8086bdd201":{
      "scriptId":"u26"},
    "568cf306f4d8415bb1511b62d422e898":{
      "scriptId":"u27"},
    "9e4414a89175415d8b5e6194b35c27ce":{
      "scriptId":"u28"},
    "1ec7eebac2984dbb88c69ddde82a5c37":{
      "scriptId":"u29"},
    "47b72f1f11db4652a1372a8b73372023":{
      "scriptId":"u30"},
    "72eadcfcf4754734b9889d58d3ffd18e":{
      "scriptId":"u31"},
    "da447acd1290405494d1742beefaa6e7":{
      "scriptId":"u32"},
    "1822833be9cf4d92a61b8ecce8503a01":{
      "scriptId":"u33"},
    "fea3c42bda8e43de86d42545206a301b":{
      "scriptId":"u34"},
    "2315bb09701b455bb1784549fbdb1e67":{
      "scriptId":"u35"},
    "25e023d6279f4ce292c3f2a11466a381":{
      "scriptId":"u36"},
    "363ce02718054c80b4ab71f1650f40f3":{
      "scriptId":"u37"},
    "524f63402da54a089a4fc615ba1f43ec":{
      "scriptId":"u38"},
    "87a49cb01ee54dd7a1dbec2e8ea02d36":{
      "scriptId":"u39"},
    "806f4d60881e4784afc17f91107d034b":{
      "scriptId":"u40"},
    "cd51ef0fae4243599cf1fc3d6a3cd427":{
      "scriptId":"u41"},
    "a564eca91ec3495582813acac143fc4b":{
      "scriptId":"u42"},
    "ace0bed20e2749efaa7b94ccec6a9aa2":{
      "scriptId":"u43"}}});