package com.kyss.generator.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dbo.sys_role_privilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysRolePrivilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.sys_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    private Long privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.sys_role_privilege.role_id
     *
     * @return the value of dbo.sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.sys_role_privilege.role_id
     *
     * @param roleId the value for dbo.sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.sys_role_privilege.privilege_id
     *
     * @return the value of dbo.sys_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.sys_role_privilege.privilege_id
     *
     * @param privilegeId the value for dbo.sys_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}