package com.kyss.generator.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dbo.sys_user_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.sys_user_role.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.sys_user_role.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.sys_user_role.user_id
     *
     * @return the value of dbo.sys_user_role.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.sys_user_role.user_id
     *
     * @param userId the value for dbo.sys_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.sys_user_role.role_id
     *
     * @return the value of dbo.sys_user_role.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.sys_user_role.role_id
     *
     * @param roleId the value for dbo.sys_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}