$axure.loadCurrentPage({
  "url":"我的发布.html",
  "generationDate":new Date(1420531296461.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b574d5d76cc0421296ebbb095ec176b7",
    "type":"Axure:Page",
    "name":"我的发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fdfeaaf8b66543f7b0374b61ccd20406",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"ddcf8f2a14134f0f86a869d9a3554cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b47fc3f1184e446f9983045a64c8aca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"6bb9cae4e6d541e7b5c1976e7e4fbc16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffc60458b4774785b0f7bfa3be424c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"41cdd0ca08ab4e5eb1a577edf3f5ebe0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":271},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"d9c233713a2a499d9f5a237254044a72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":187},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2028e8cba4d44e2f8bb29bc9c1234dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":187},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6a3670fcfd149f1a228b663294c1016",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":225},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6b557f8d65d409296234dd8867526ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":225},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43326ff5209240a5a624602c24821048",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":253},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b233d34d6254d0c90c6fb2eb019e34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":253},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"facbc5c042a44013be39c896952bcc8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":249},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28ca2a1f3e2e4e8bbde886cd49d7d105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":249},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45dad1fbf2e94b729207cab3f3e29c09",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":370},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"360e8e7cb6b04e0686d0563637eb7fa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":286},
            "size":{
              "width":198,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5951e87d00244ea9519c69a1e0c7918",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":286},
                "size":{
                  "width":198,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4547972bf5c34735b27503b29a1f079f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":324},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254b81c12bcb409390c8f9ad97f0f265",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":324},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec8ec8b72ef54c53aea31803820b662d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":352},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8fed1769686421bbea807960ba53f28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":352},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68a0c20f07b4ed182482bab1a6973c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":348},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73dce29ab723434db62013bfa670d39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":348},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"569c6987536c43a6a58667d8b98085c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":469},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"0f7cce642db2482d9ada7e6a76fe6b9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":385},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bd76a910504ea4940dd09b3f634780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":385},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37d17ae22f754327bc5ba9df7b38c508",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":423},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49d6a78f314c46679d6286e99d088db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":423},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f51a9b41b5e42f193a46263b275db18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":451},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74b8d4515c6747879214e720fcf522c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":451},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bba7d1c6b5dc4cdfab0430ad352161c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":447},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc349d9de204edd924db75a46d29b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":447},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"077f734fdd5a4795b6eeb40ab782ce23",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":370},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"6b845f8dd2b84b82a7cc39d0bf83d7bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":187},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a474be19ae14a9596f7fbe626a3498d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":187},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车市列表/u67.png"}},
{
          "id":"66917f9fda8948af942736011d5a37a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":286},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c068c992bf984bed93f5739e67a10000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":286},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车市列表/u69.png"}},
{
          "id":"0308f142edbc43218e962c05ec7b03e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":385},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e689943cb6743d185e727273658fa1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":385},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车市列表/u71.jpg"}},
{
          "id":"d88961023f2f4b78ba262db596ef2b8b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":568},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"02dc42554e8f4d4c933fdddfba28d26f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":484},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b455ebf0d08f48309b5c021f8af7f5ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":484},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb3c9d127a4240048940d677c3fd15e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":522},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4152316273e74b39a7b708c254f621b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":522},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb699dae716643b68f1575be14a45402",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":550},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7905245e36349acb3fc23b89784dfcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":550},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"591ed8377f6e4537bf6d984382f7d47d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":546},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4d21e4218a41a982b4757e2f670198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":546},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c02e0a1f534d92b82f70dcb85e8cb3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":667},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"1bbea149c3a0402faa66d86ba968e3bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":583},
            "size":{
              "width":198,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54d64f4d72284238b496043ee5b45617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":583},
                "size":{
                  "width":198,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64bca5a400814d73ae765d4a3111428e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":621},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37e1f0ee8e934c71a7e6ab2dcb7161f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":621},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfe6e9e563d54b37b4ec74d2839a26e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":649},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d77e6e42c84dd3bbc02c41d3cf8b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":649},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f73eba33c7fb41068c90be9c7aa7bce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":645},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ccb1095cbcd44948d74ae07e17de5b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":645},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e99d48b50bc43b4a97e8c2a8527f668",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":484},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c491f2b716a0475d8a673cfd59c6e166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":484},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车市列表/u67.png"}},
{
          "id":"b2436386889e4e48b4d10876b4c36439",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":583},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f29c5b47a9e4decabe9949f4bdb24da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":583},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车市列表/u69.png"}},
{
          "id":"933b970a161143c88a29020fb293bb25",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":178},
            "size":{
              "width":312,
              "height":94}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车市详情",
                      "target":{
                        "targetType":"page",
                        "url":"车市详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "fdfeaaf8b66543f7b0374b61ccd20406":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "ddcf8f2a14134f0f86a869d9a3554cab":{
      "scriptId":"u5"},
    "b47fc3f1184e446f9983045a64c8aca5":{
      "scriptId":"u6"},
    "6bb9cae4e6d541e7b5c1976e7e4fbc16":{
      "scriptId":"u7"},
    "ffc60458b4774785b0f7bfa3be424c2f":{
      "scriptId":"u8"},
    "41cdd0ca08ab4e5eb1a577edf3f5ebe0":{
      "scriptId":"u9"},
    "d9c233713a2a499d9f5a237254044a72":{
      "scriptId":"u10"},
    "2028e8cba4d44e2f8bb29bc9c1234dfe":{
      "scriptId":"u11"},
    "b6a3670fcfd149f1a228b663294c1016":{
      "scriptId":"u12"},
    "d6b557f8d65d409296234dd8867526ec":{
      "scriptId":"u13"},
    "43326ff5209240a5a624602c24821048":{
      "scriptId":"u14"},
    "7b233d34d6254d0c90c6fb2eb019e34c":{
      "scriptId":"u15"},
    "facbc5c042a44013be39c896952bcc8d":{
      "scriptId":"u16"},
    "28ca2a1f3e2e4e8bbde886cd49d7d105":{
      "scriptId":"u17"},
    "45dad1fbf2e94b729207cab3f3e29c09":{
      "scriptId":"u18"},
    "360e8e7cb6b04e0686d0563637eb7fa3":{
      "scriptId":"u19"},
    "c5951e87d00244ea9519c69a1e0c7918":{
      "scriptId":"u20"},
    "4547972bf5c34735b27503b29a1f079f":{
      "scriptId":"u21"},
    "254b81c12bcb409390c8f9ad97f0f265":{
      "scriptId":"u22"},
    "ec8ec8b72ef54c53aea31803820b662d":{
      "scriptId":"u23"},
    "e8fed1769686421bbea807960ba53f28":{
      "scriptId":"u24"},
    "a68a0c20f07b4ed182482bab1a6973c3":{
      "scriptId":"u25"},
    "73dce29ab723434db62013bfa670d39f":{
      "scriptId":"u26"},
    "569c6987536c43a6a58667d8b98085c8":{
      "scriptId":"u27"},
    "0f7cce642db2482d9ada7e6a76fe6b9d":{
      "scriptId":"u28"},
    "78bd76a910504ea4940dd09b3f634780":{
      "scriptId":"u29"},
    "37d17ae22f754327bc5ba9df7b38c508":{
      "scriptId":"u30"},
    "49d6a78f314c46679d6286e99d088db3":{
      "scriptId":"u31"},
    "5f51a9b41b5e42f193a46263b275db18":{
      "scriptId":"u32"},
    "74b8d4515c6747879214e720fcf522c6":{
      "scriptId":"u33"},
    "bba7d1c6b5dc4cdfab0430ad352161c1":{
      "scriptId":"u34"},
    "acc349d9de204edd924db75a46d29b17":{
      "scriptId":"u35"},
    "077f734fdd5a4795b6eeb40ab782ce23":{
      "scriptId":"u36"},
    "6b845f8dd2b84b82a7cc39d0bf83d7bd":{
      "scriptId":"u37"},
    "6a474be19ae14a9596f7fbe626a3498d":{
      "scriptId":"u38"},
    "66917f9fda8948af942736011d5a37a4":{
      "scriptId":"u39"},
    "c068c992bf984bed93f5739e67a10000":{
      "scriptId":"u40"},
    "0308f142edbc43218e962c05ec7b03e8":{
      "scriptId":"u41"},
    "2e689943cb6743d185e727273658fa1d":{
      "scriptId":"u42"},
    "d88961023f2f4b78ba262db596ef2b8b":{
      "scriptId":"u43"},
    "02dc42554e8f4d4c933fdddfba28d26f":{
      "scriptId":"u44"},
    "b455ebf0d08f48309b5c021f8af7f5ce":{
      "scriptId":"u45"},
    "eb3c9d127a4240048940d677c3fd15e0":{
      "scriptId":"u46"},
    "4152316273e74b39a7b708c254f621b0":{
      "scriptId":"u47"},
    "fb699dae716643b68f1575be14a45402":{
      "scriptId":"u48"},
    "a7905245e36349acb3fc23b89784dfcf":{
      "scriptId":"u49"},
    "591ed8377f6e4537bf6d984382f7d47d":{
      "scriptId":"u50"},
    "4b4d21e4218a41a982b4757e2f670198":{
      "scriptId":"u51"},
    "f0c02e0a1f534d92b82f70dcb85e8cb3":{
      "scriptId":"u52"},
    "1bbea149c3a0402faa66d86ba968e3bc":{
      "scriptId":"u53"},
    "54d64f4d72284238b496043ee5b45617":{
      "scriptId":"u54"},
    "64bca5a400814d73ae765d4a3111428e":{
      "scriptId":"u55"},
    "37e1f0ee8e934c71a7e6ab2dcb7161f3":{
      "scriptId":"u56"},
    "dfe6e9e563d54b37b4ec74d2839a26e5":{
      "scriptId":"u57"},
    "e5d77e6e42c84dd3bbc02c41d3cf8b70":{
      "scriptId":"u58"},
    "f73eba33c7fb41068c90be9c7aa7bce2":{
      "scriptId":"u59"},
    "4ccb1095cbcd44948d74ae07e17de5b1":{
      "scriptId":"u60"},
    "6e99d48b50bc43b4a97e8c2a8527f668":{
      "scriptId":"u61"},
    "c491f2b716a0475d8a673cfd59c6e166":{
      "scriptId":"u62"},
    "b2436386889e4e48b4d10876b4c36439":{
      "scriptId":"u63"},
    "6f29c5b47a9e4decabe9949f4bdb24da":{
      "scriptId":"u64"},
    "933b970a161143c88a29020fb293bb25":{
      "scriptId":"u65"}}});