$axure.loadCurrentPage({
  "url":"我的收藏-资讯.html",
  "generationDate":new Date(1420531296570.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef9d34727b96401f9c03c0d66d3a24da",
    "type":"Axure:Page",
    "name":"我的收藏-资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd97c55409254cdc83457e75ef316615",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"f922a88d1bb949dfba1acce4bf7bfba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b678ed460e44f599dd22e3f58973d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"a048e46e1b654d2897b19d2ad4fa123c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0583ff4b07040fc9dbde0b3407892de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"7c98174667684c9bb71bddba2fccef57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":433},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f834fe9c2ecb4be3b056152c6f1f0508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":433},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u9.png"}},
{
          "id":"02e732ab74ed48f5b88b9f22346c28e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30bbb015d3db4a87987f13e83971e8ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u11.png"}},
{
          "id":"78f7454d8744441387152999e30c7197",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":74,
              "y":184},
            "size":{
              "width":46,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da46b68005e4ff29e634172bf3373ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":184},
                "size":{
                  "width":46,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cb46885c1d444b19e46614720db6e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":62,
              "y":210},
            "size":{
              "width":56,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e330eb94489d4c42854c5980f4c70925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":62,
                  "y":210},
                "size":{
                  "width":56,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u15.png"}},
{
          "id":"8ab6130bbe284504a80b836f4eb7c886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":174,
              "y":184},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2462d460f85d426ab6da0677db4c6a7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":174,
                  "y":184},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7517a67f6bfb4f09a9639947b1f25481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":273,
              "y":184},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"217f11e37ef34ab589f07ec7df92a497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":273,
                  "y":184},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6b0f2d3ca3244999104d23e01773cbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":222},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a47d9464667841a28b043b6a47a13144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":222},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻/u40.png"}},
{
          "id":"3987a16bf21b4e3ea4d0e4c008a2ed7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":306},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"2c5bb2c30c104318b093b245805065de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":222},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6d619a0d6e44a6b942e729f737db5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":222},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afb8830a4a0241748c1fab0bf46970d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":260},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e519d5072e4500aed82820f01b367e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":260},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c5f6b62ed304f95a861f795f6163fd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":288},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f991b0e7a974298b6083cbf14888cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":288},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"721448cd68c44a1b92341719ac85cbbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":284},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3a0bb65c7445b9ab6efed2643902b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":284},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"375c72c7ef804a3c84b7cfa759c7e2f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":222},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c54e2f3d2504f50b097ed4fe191f2cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":222},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房产列表/u59.png"}},
{
          "id":"d25f8205e37e43dbba3e64284df27342",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":405},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"6d83d06f9fd94c7d8126cacb832c3ad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":321},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c5f9e8316d4909b66d7685110d6c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":321},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e93436a45a40029da4796866cb87db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":359},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08725fb59d6244928a4f8107376732f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":359},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"097115bbe01a48dc87b22207cc590302",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":387},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a973549866e84939a354adc63baa9169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":387},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"387730e53bcf4ed8ae78115a009d6362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":383},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b871028e7e94feb96e482d1a9ed6f30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":383},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71468192710e46d586518328b1b74bf2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":306},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"4f20e87e026444bdac99f9c30fed7491",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":321},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa8e55955064cb897545539d23105ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":321},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二手列表/u103.png"}},
{
          "id":"46d22f174b4148e09e6d2cfcbe5ad625",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":420},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269b070ad01a43d29ebc0e425b4a024e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":420},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻/u40.png"}},
{
          "id":"d35382d9c84e4005ad6760b9cac28891",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":504},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"5ffce789b749419399cd35d09d2230ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":420},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ce615f865da4e958d9ae2b740da6053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":420},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf068a5eee23416ca03f70fd3d870c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":458},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"353199e3fa464c6eb88e45f4f1ff27ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":458},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"942bdca0e2fb4a7da2a9c4a4811bf04c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":486},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d761838767f6453098d2a004d184252f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":486},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"222a502224f64dbaa07e6e446e915ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":482},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62c697f112e4ed68e574fc46ca257d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":482},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acc2208019ae45a493474854ad14f332",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":420},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb1fb6a3de774e6abf5feef6cff7bb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":420},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/房产列表/u59.png"}},
{
          "id":"800620a724504da4886cf0290fb468c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":603},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"93ec9b3550924f919df774ee05044801",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":519},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"729ad9688a4b44f7a1e7bf6825a5a93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":519},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0ef7e505d224722bdca0d16181e8cec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":154,
              "y":557},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0b0ab9f401e4d9dbabe47e961d60247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":557},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66c0e093d59e4a3fb1453171ff114a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":278,
              "y":585},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e5d30cbfdd47c9a709656afaf41af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":585},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8fa0becc6d44e3fa7c4a208e6f94100",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":154,
              "y":581},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bebd4ee69ce4923ad76afc347248b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":581},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26d931cc85be42b082f9a939131b489a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":504},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"d28588d386884b56beb057e665b2e5ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":519},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3134ff1bff2c4042918c6c95531cb074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":519},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二手列表/u103.png"}},
{
          "id":"26b08215ba9547749fb203b58a49582e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":181},
            "size":{
              "width":76,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏-店铺",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏-店铺.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aa3e6c58e48c4ed8a3d267dc44b7f064",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":181},
            "size":{
              "width":76,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏-团购",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏-团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fd7a9c6f94844832a2f71a48fd3a17a2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":218},
            "size":{
              "width":317,
              "height":89}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 房产详情",
                      "target":{
                        "targetType":"page",
                        "url":"房产详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "bd97c55409254cdc83457e75ef316615":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "f922a88d1bb949dfba1acce4bf7bfba2":{
      "scriptId":"u5"},
    "f3b678ed460e44f599dd22e3f58973d2":{
      "scriptId":"u6"},
    "a048e46e1b654d2897b19d2ad4fa123c":{
      "scriptId":"u7"},
    "f0583ff4b07040fc9dbde0b3407892de":{
      "scriptId":"u8"},
    "7c98174667684c9bb71bddba2fccef57":{
      "scriptId":"u9"},
    "f834fe9c2ecb4be3b056152c6f1f0508":{
      "scriptId":"u10"},
    "02e732ab74ed48f5b88b9f22346c28e3":{
      "scriptId":"u11"},
    "30bbb015d3db4a87987f13e83971e8ea":{
      "scriptId":"u12"},
    "78f7454d8744441387152999e30c7197":{
      "scriptId":"u13"},
    "2da46b68005e4ff29e634172bf3373ca":{
      "scriptId":"u14"},
    "9cb46885c1d444b19e46614720db6e8a":{
      "scriptId":"u15"},
    "e330eb94489d4c42854c5980f4c70925":{
      "scriptId":"u16"},
    "8ab6130bbe284504a80b836f4eb7c886":{
      "scriptId":"u17"},
    "2462d460f85d426ab6da0677db4c6a7b":{
      "scriptId":"u18"},
    "7517a67f6bfb4f09a9639947b1f25481":{
      "scriptId":"u19"},
    "217f11e37ef34ab589f07ec7df92a497":{
      "scriptId":"u20"},
    "f6b0f2d3ca3244999104d23e01773cbb":{
      "scriptId":"u21"},
    "a47d9464667841a28b043b6a47a13144":{
      "scriptId":"u22"},
    "3987a16bf21b4e3ea4d0e4c008a2ed7e":{
      "scriptId":"u23"},
    "2c5bb2c30c104318b093b245805065de":{
      "scriptId":"u24"},
    "fd6d619a0d6e44a6b942e729f737db5a":{
      "scriptId":"u25"},
    "afb8830a4a0241748c1fab0bf46970d3":{
      "scriptId":"u26"},
    "22e519d5072e4500aed82820f01b367e":{
      "scriptId":"u27"},
    "8c5f6b62ed304f95a861f795f6163fd3":{
      "scriptId":"u28"},
    "4f991b0e7a974298b6083cbf14888cae":{
      "scriptId":"u29"},
    "721448cd68c44a1b92341719ac85cbbc":{
      "scriptId":"u30"},
    "bd3a0bb65c7445b9ab6efed2643902b7":{
      "scriptId":"u31"},
    "375c72c7ef804a3c84b7cfa759c7e2f2":{
      "scriptId":"u32"},
    "8c54e2f3d2504f50b097ed4fe191f2cf":{
      "scriptId":"u33"},
    "d25f8205e37e43dbba3e64284df27342":{
      "scriptId":"u34"},
    "6d83d06f9fd94c7d8126cacb832c3ad9":{
      "scriptId":"u35"},
    "61c5f9e8316d4909b66d7685110d6c2b":{
      "scriptId":"u36"},
    "c9e93436a45a40029da4796866cb87db":{
      "scriptId":"u37"},
    "08725fb59d6244928a4f8107376732f6":{
      "scriptId":"u38"},
    "097115bbe01a48dc87b22207cc590302":{
      "scriptId":"u39"},
    "a973549866e84939a354adc63baa9169":{
      "scriptId":"u40"},
    "387730e53bcf4ed8ae78115a009d6362":{
      "scriptId":"u41"},
    "5b871028e7e94feb96e482d1a9ed6f30":{
      "scriptId":"u42"},
    "71468192710e46d586518328b1b74bf2":{
      "scriptId":"u43"},
    "4f20e87e026444bdac99f9c30fed7491":{
      "scriptId":"u44"},
    "aaa8e55955064cb897545539d23105ed":{
      "scriptId":"u45"},
    "46d22f174b4148e09e6d2cfcbe5ad625":{
      "scriptId":"u46"},
    "269b070ad01a43d29ebc0e425b4a024e":{
      "scriptId":"u47"},
    "d35382d9c84e4005ad6760b9cac28891":{
      "scriptId":"u48"},
    "5ffce789b749419399cd35d09d2230ad":{
      "scriptId":"u49"},
    "7ce615f865da4e958d9ae2b740da6053":{
      "scriptId":"u50"},
    "bf068a5eee23416ca03f70fd3d870c2b":{
      "scriptId":"u51"},
    "353199e3fa464c6eb88e45f4f1ff27ea":{
      "scriptId":"u52"},
    "942bdca0e2fb4a7da2a9c4a4811bf04c":{
      "scriptId":"u53"},
    "d761838767f6453098d2a004d184252f":{
      "scriptId":"u54"},
    "222a502224f64dbaa07e6e446e915ea6":{
      "scriptId":"u55"},
    "f62c697f112e4ed68e574fc46ca257d1":{
      "scriptId":"u56"},
    "acc2208019ae45a493474854ad14f332":{
      "scriptId":"u57"},
    "eb1fb6a3de774e6abf5feef6cff7bb85":{
      "scriptId":"u58"},
    "800620a724504da4886cf0290fb468c1":{
      "scriptId":"u59"},
    "93ec9b3550924f919df774ee05044801":{
      "scriptId":"u60"},
    "729ad9688a4b44f7a1e7bf6825a5a93c":{
      "scriptId":"u61"},
    "b0ef7e505d224722bdca0d16181e8cec":{
      "scriptId":"u62"},
    "b0b0ab9f401e4d9dbabe47e961d60247":{
      "scriptId":"u63"},
    "66c0e093d59e4a3fb1453171ff114a8c":{
      "scriptId":"u64"},
    "d1e5d30cbfdd47c9a709656afaf41af8":{
      "scriptId":"u65"},
    "b8fa0becc6d44e3fa7c4a208e6f94100":{
      "scriptId":"u66"},
    "3bebd4ee69ce4923ad76afc347248b9a":{
      "scriptId":"u67"},
    "26d931cc85be42b082f9a939131b489a":{
      "scriptId":"u68"},
    "d28588d386884b56beb057e665b2e5ea":{
      "scriptId":"u69"},
    "3134ff1bff2c4042918c6c95531cb074":{
      "scriptId":"u70"},
    "26b08215ba9547749fb203b58a49582e":{
      "scriptId":"u71"},
    "aa3e6c58e48c4ed8a3d267dc44b7f064":{
      "scriptId":"u72"},
    "fd7a9c6f94844832a2f71a48fd3a17a2":{
      "scriptId":"u73"}}});