$axure.loadCurrentPage({
  "url":"新闻.html",
  "generationDate":new Date(1420531287844.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6e461adfe5542cbaf78549a06832e96",
    "type":"Axure:Page",
    "name":"新闻",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe48703b5ed446e7bc941671dcc8976d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"526a66421c78437e9bce63c9ccbac9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08dabffcf722449cb7d2c93d384b7fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"8829fec0ce0943d78762b0d5aad204e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4f0963cf16475897b81327e5851847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 资讯",
                      "target":{
                        "targetType":"page",
                        "url":"资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
          "label":"tulun",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":177},
            "size":{
              "width":320,
              "height":176}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to 停止循环",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"current",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 you,<br>zuo",
                      "objectsToFades":[{
                          "objectPath":["26c2c83dac814bf8bf50069172e3f7e6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["173f341139da4d3aa0368a2a97dbfd23"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1<br> (If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 不明 = &quot;[[Cursor.y]],[[This.bottom]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]},
{
                  "description":"用例 2<br> (If &quot;[[Cursor.x]]&quot; &lt; &quot;[[this.left+15]]&quot; 或 &quot;[[Cursor.x]]&quot; &gt; &quot;[[this.right-15]]&quot; 或 &quot;[[Cursor.y]]&quot; &lt; &quot;[[this.top+15]]&quot; 或 &quot;[[Cursor.y]]&quot; &gt; &quot;[[this.bottom-15]]&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"<",
                      "leftExpr":{
                        "exprType":"stringLiteral",
                        "value":"[[Cursor.x]]",
                        "localVariables":{
},
                        "stos":[{
                            "computedType":"int",
                            "sto":"propCall",
                            "thisSTO":{
                              "sto":"var",
                              "name":"cursor"},
                            "prop":"x"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"[[this.left+15]]",
                        "localVariables":{
},
                        "stos":[{
                            "computedType":"int",
                            "sto":"binOp",
                            "op":"+",
                            "leftSTO":{
                              "computedType":"int",
                              "sto":"propCall",
                              "thisSTO":{
                                "desiredType":"widget",
                                "sto":"var",
                                "name":"this"},
                              "prop":"left"},
                            "rightSTO":{
                              "computedType":"int",
                              "sto":"literal",
                              "value":15}}]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":">",
                        "leftExpr":{
                          "exprType":"stringLiteral",
                          "value":"[[Cursor.x]]",
                          "stos":[{
                              "computedType":"int",
                              "sto":"propCall",
                              "thisSTO":{
                                "sto":"var",
                                "name":"cursor"},
                              "prop":"x"}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"[[this.right-15]]",
                          "stos":[{
                              "computedType":"int",
                              "sto":"binOp",
                              "op":"-",
                              "leftSTO":{
                                "computedType":"int",
                                "sto":"propCall",
                                "thisSTO":{
                                  "desiredType":"widget",
                                  "sto":"var",
                                  "name":"this"},
                                "prop":"right"},
                              "rightSTO":{
                                "computedType":"int",
                                "sto":"literal",
                                "value":15}}]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"<",
                          "leftExpr":{
                            "exprType":"stringLiteral",
                            "value":"[[Cursor.y]]",
                            "stos":[{
                                "computedType":"int",
                                "sto":"propCall",
                                "thisSTO":{
                                  "sto":"var",
                                  "name":"cursor"},
                                "prop":"y"}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"[[this.top+15]]",
                            "stos":[{
                                "computedType":"int",
                                "sto":"binOp",
                                "op":"+",
                                "leftSTO":{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"top"},
                                "rightSTO":{
                                  "computedType":"int",
                                  "sto":"literal",
                                  "value":15}}]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":">",
                          "leftExpr":{
                            "exprType":"stringLiteral",
                            "value":"[[Cursor.y]]",
                            "stos":[{
                                "computedType":"int",
                                "sto":"propCall",
                                "thisSTO":{
                                  "sto":"var",
                                  "name":"cursor"},
                                "prop":"y"}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"[[this.bottom-15]]",
                            "stos":[{
                                "computedType":"int",
                                "sto":"binOp",
                                "op":"-",
                                "leftSTO":{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"bottom"},
                                "rightSTO":{
                                  "computedType":"int",
                                  "sto":"literal",
                                  "value":15}}]}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 zuo,<br>you",
                      "objectsToFades":[{
                          "objectPath":["173f341139da4d3aa0368a2a97dbfd23"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["26c2c83dac814bf8bf50069172e3f7e6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 tulun to Next 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]},
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1<br> (If state of This = tu1)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu1 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b25887306aa447298a167f31c96be13f"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 2<br> (Else If state of This = tu2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu2 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b8872b1402414390aed94f8b36507375"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 3<br> (Else If state of This = tu3)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu3 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["be53531d3dca4be985aab019f6fa4282"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 4<br> (Else If state of This = tu4)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":3}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu4 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d6de2ab7e6084dcc92db3e4680b33384"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 5<br> (Else If state of This = tu5)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":4}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu5 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a22109e5e45f4764a3be6a96ad70575b"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 6<br> (Else If state of This = tu6)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                      "panelIndex":5}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 tu6 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8f68be397a924c99b9de31f37f3acd4d"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to Next 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"78b6f6f5bf3c4202ba21016d5343b657",
              "label":"tu1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a77648bf65e9403cbf7987d98826dce2",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-4,
                      "y":-2},
                    "size":{
                      "width":324,
                      "height":223}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31e9a411e60849d39c6d75702f1dbb59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-4,
                          "y":-2},
                        "size":{
                          "width":324,
                          "height":223}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u10.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"6c3c9318d1314e17aafb21f629649703",
              "label":"tu2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a3e0950167664b3eb00943e3a293b64a",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":-33},
                    "size":{
                      "width":326,
                      "height":240}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c5bb7c61a1948db97c9b97071d4ea2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":-33},
                        "size":{
                          "width":326,
                          "height":240}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u12.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a7dea7b2e0f0484e915109edb36e2c65",
              "label":"tu3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4e2494e775b34eed9ae5c8024737a0bc",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-26},
                    "size":{
                      "width":330,
                      "height":250}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2dcd68eddbc5445086e1808af2020290",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-26},
                        "size":{
                          "width":330,
                          "height":250}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u14.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ffcefd1d5e224704aea4d1476ad4069d",
              "label":"tu4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f9b2694b5f424a04b856e13b0cb51306",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-20},
                    "size":{
                      "width":330,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67474c89f7ab4ff2a405555c7a1eccfe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-20},
                        "size":{
                          "width":330,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u16.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f466ed04df4b4bc1b7412dc6eb0466aa",
              "label":"tu5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6372baae2ce645c4b98d455436f44a2e",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-19,
                      "y":-5},
                    "size":{
                      "width":349,
                      "height":232}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7718ea270214a88839e0cd49eba0b5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-19,
                          "y":-5},
                        "size":{
                          "width":349,
                          "height":232}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u18.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ed905cda145e42d78429a6ad99695ff6",
              "label":"tu6",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4b63e1532eeb4c199946c43f16995388",
                  "label":"",
                  "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-20,
                      "y":-21},
                    "size":{
                      "width":350,
                      "height":270}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b523fa1680f046369a27301ce135ac84",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bbfa4dd7a27e4b9c9ca3aab5376548ca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-20,
                          "y":-21},
                        "size":{
                          "width":350,
                          "height":270}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻/u20.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"173f341139da4d3aa0368a2a97dbfd23",
          "label":"zuo",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0x99000000}}},
            "fill":{
              "fillType":"solid",
              "color":0x33000000},
            "location":{
              "x":43,
              "y":240},
            "size":{
              "width":50,
              "height":50},
            "visible":false,
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978ecc52d2ce41cc80339c17b12061f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0x33000000},
                "location":{
                  "x":43,
                  "y":240},
                "size":{
                  "width":50,
                  "height":50},
                "visible":false,
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to Previous 向右滑动 out 500ms 向右滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideRight",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/zuo_u20.png",
            "mouseOver~":"images/资讯/zuo_u20_mouseOver.png"}},
{
          "id":"26c2c83dac814bf8bf50069172e3f7e6",
          "label":"you",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0x99000000}}},
            "fill":{
              "fillType":"solid",
              "color":0x33000000},
            "location":{
              "x":291,
              "y":240},
            "size":{
              "width":50,
              "height":50},
            "visible":false,
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"092d04e73a384cda9c4c5e08d24d093c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0x33000000},
                "location":{
                  "x":291,
                  "y":240},
                "size":{
                  "width":50,
                  "height":50},
                "visible":false,
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to Next 向左滑动 out 500ms 向左滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/zuo_u20.png",
            "mouseOver~":"images/资讯/zuo_u20_mouseOver.png"}},
{
          "id":"8070d72d66ee431da42588a049479455",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0x4CFFFFFF},
            "location":{
              "x":131,
              "y":330},
            "size":{
              "width":120,
              "height":14},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccab7ae9e1b849449b31bf1b01ea22da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0x4CFFFFFF},
                "location":{
                  "x":131,
                  "y":330},
                "size":{
                  "width":120,
                  "height":14},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u24.png"}},
{
          "id":"b25887306aa447298a167f31c96be13f",
          "label":"tu1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":147,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1421ed595f6c4c0b84f102fc7f5b3cfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":147,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"b8872b1402414390aed94f8b36507375",
          "label":"tu2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":163,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e9507012e574cef8239cf5825a1e776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":163,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"be53531d3dca4be985aab019f6fa4282",
          "label":"tu3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":179,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a05ac4b895164d8ea7ffcf3da7461cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":179,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"d6de2ab7e6084dcc92db3e4680b33384",
          "label":"tu4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":193,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2721c58aac4ac3b426436f3fa30d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":193,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"a22109e5e45f4764a3be6a96ad70575b",
          "label":"tu5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":209,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"482f91db3d8447528be377d16d2fd16f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":209,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"8f68be397a924c99b9de31f37f3acd4d",
          "label":"tu6",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":225,
              "y":332},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb49bbcef0e4a77ac5d713dc41ce2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":225,
                  "y":332},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 tulun to [[this.name]] 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["bbfa4dd7a27e4b9c9ca3aab5376548ca"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 选中状态值 This = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资讯/tu1_u26.png",
            "selected~":"images/资讯/tu1_u26_selected.png"}},
{
          "id":"6c0d752437ca47e08b6197271895edf6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":363},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0372bf20158e403bbaa36d0ad404facf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":363},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻/u40.png"}},
{
          "id":"0146cb0047974d11aafccfd0ec685374",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":447},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"f96a37d0f254483294f183e5a5dfed1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":363},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276ff5dbc4f946e8895fd0d78a7382b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":363},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f0ad65d4eef4095a79295d04eabf26a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":155,
              "y":397},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df66a96bf40f449ca60183277818a2d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":397},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0656a8fded014e49a0bf389fba879f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":279,
              "y":429},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa847f4a7ba14e679d8942f2ee92efc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":279,
                  "y":429},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"187e5957022e4e58bc26c2c96de47f98",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":545},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"0ac12eb8ec1f4b8897ec75a21030b84f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":461},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"022799b26d964e1da7ebbe3920dc0768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":461},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb302636c5f34a978f1bc4a1b1724893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":155,
              "y":481},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572bb8211770497599bc09f0c41b385f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":481},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"575ad008451043128a55a94195ea7e38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":279,
              "y":527},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36570ab0d70d44199df59f6eb3a78cb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":279,
                  "y":527},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b36cc7e9dc84660969a3e7d81f1660a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":461},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04bdebd79b8b426c887925dc7de27039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":461},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻/u56.png"}},
{
          "id":"f06e0f47a5c94880b8f29bb1ccfaae25",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":644},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"779ca171817d4fc1bf120ee4926859ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":560},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eed5bfa980f420d954d77502c17c304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":560},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59debc5bcc0349479e03a9144c38b6be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":155,
              "y":593},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"979ff6aa44ad494d98ddf833385ca0e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":593},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b729a019d7049429e07e9acaef4b6bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":279,
              "y":626},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ac3be8337564b3dabdda5fd364c55d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":279,
                  "y":626},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b00854b13aa447c5bbd474abf64269fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":560},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be0939df4024259af029b3272838c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":560},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻/u65.jpg"}},
{
          "id":"abfb780c2a524dc89a4b3ff011e910cc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":357},
            "size":{
              "width":320,
              "height":93}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻详情",
                      "target":{
                        "targetType":"page",
                        "url":"新闻详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "fe48703b5ed446e7bc941671dcc8976d":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "526a66421c78437e9bce63c9ccbac9e7":{
      "scriptId":"u5"},
    "08dabffcf722449cb7d2c93d384b7fa3":{
      "scriptId":"u6"},
    "8829fec0ce0943d78762b0d5aad204e4":{
      "scriptId":"u7"},
    "8e4f0963cf16475897b81327e5851847":{
      "scriptId":"u8"},
    "bbfa4dd7a27e4b9c9ca3aab5376548ca":{
      "scriptId":"u9"},
    "a77648bf65e9403cbf7987d98826dce2":{
      "scriptId":"u10"},
    "31e9a411e60849d39c6d75702f1dbb59":{
      "scriptId":"u11"},
    "a3e0950167664b3eb00943e3a293b64a":{
      "scriptId":"u12"},
    "5c5bb7c61a1948db97c9b97071d4ea2c":{
      "scriptId":"u13"},
    "4e2494e775b34eed9ae5c8024737a0bc":{
      "scriptId":"u14"},
    "2dcd68eddbc5445086e1808af2020290":{
      "scriptId":"u15"},
    "f9b2694b5f424a04b856e13b0cb51306":{
      "scriptId":"u16"},
    "67474c89f7ab4ff2a405555c7a1eccfe":{
      "scriptId":"u17"},
    "6372baae2ce645c4b98d455436f44a2e":{
      "scriptId":"u18"},
    "c7718ea270214a88839e0cd49eba0b5d":{
      "scriptId":"u19"},
    "4b63e1532eeb4c199946c43f16995388":{
      "scriptId":"u20"},
    "b523fa1680f046369a27301ce135ac84":{
      "scriptId":"u21"},
    "173f341139da4d3aa0368a2a97dbfd23":{
      "scriptId":"u22"},
    "978ecc52d2ce41cc80339c17b12061f4":{
      "scriptId":"u23"},
    "26c2c83dac814bf8bf50069172e3f7e6":{
      "scriptId":"u24"},
    "092d04e73a384cda9c4c5e08d24d093c":{
      "scriptId":"u25"},
    "8070d72d66ee431da42588a049479455":{
      "scriptId":"u26"},
    "ccab7ae9e1b849449b31bf1b01ea22da":{
      "scriptId":"u27"},
    "b25887306aa447298a167f31c96be13f":{
      "scriptId":"u28"},
    "1421ed595f6c4c0b84f102fc7f5b3cfb":{
      "scriptId":"u29"},
    "b8872b1402414390aed94f8b36507375":{
      "scriptId":"u30"},
    "0e9507012e574cef8239cf5825a1e776":{
      "scriptId":"u31"},
    "be53531d3dca4be985aab019f6fa4282":{
      "scriptId":"u32"},
    "a05ac4b895164d8ea7ffcf3da7461cff":{
      "scriptId":"u33"},
    "d6de2ab7e6084dcc92db3e4680b33384":{
      "scriptId":"u34"},
    "8a2721c58aac4ac3b426436f3fa30d19":{
      "scriptId":"u35"},
    "a22109e5e45f4764a3be6a96ad70575b":{
      "scriptId":"u36"},
    "482f91db3d8447528be377d16d2fd16f":{
      "scriptId":"u37"},
    "8f68be397a924c99b9de31f37f3acd4d":{
      "scriptId":"u38"},
    "9eb49bbcef0e4a77ac5d713dc41ce2bb":{
      "scriptId":"u39"},
    "6c0d752437ca47e08b6197271895edf6":{
      "scriptId":"u40"},
    "0372bf20158e403bbaa36d0ad404facf":{
      "scriptId":"u41"},
    "0146cb0047974d11aafccfd0ec685374":{
      "scriptId":"u42"},
    "f96a37d0f254483294f183e5a5dfed1a":{
      "scriptId":"u43"},
    "276ff5dbc4f946e8895fd0d78a7382b1":{
      "scriptId":"u44"},
    "1f0ad65d4eef4095a79295d04eabf26a":{
      "scriptId":"u45"},
    "df66a96bf40f449ca60183277818a2d0":{
      "scriptId":"u46"},
    "0656a8fded014e49a0bf389fba879f06":{
      "scriptId":"u47"},
    "aa847f4a7ba14e679d8942f2ee92efc8":{
      "scriptId":"u48"},
    "187e5957022e4e58bc26c2c96de47f98":{
      "scriptId":"u49"},
    "0ac12eb8ec1f4b8897ec75a21030b84f":{
      "scriptId":"u50"},
    "022799b26d964e1da7ebbe3920dc0768":{
      "scriptId":"u51"},
    "fb302636c5f34a978f1bc4a1b1724893":{
      "scriptId":"u52"},
    "572bb8211770497599bc09f0c41b385f":{
      "scriptId":"u53"},
    "575ad008451043128a55a94195ea7e38":{
      "scriptId":"u54"},
    "36570ab0d70d44199df59f6eb3a78cb7":{
      "scriptId":"u55"},
    "4b36cc7e9dc84660969a3e7d81f1660a":{
      "scriptId":"u56"},
    "04bdebd79b8b426c887925dc7de27039":{
      "scriptId":"u57"},
    "f06e0f47a5c94880b8f29bb1ccfaae25":{
      "scriptId":"u58"},
    "779ca171817d4fc1bf120ee4926859ad":{
      "scriptId":"u59"},
    "3eed5bfa980f420d954d77502c17c304":{
      "scriptId":"u60"},
    "59debc5bcc0349479e03a9144c38b6be":{
      "scriptId":"u61"},
    "979ff6aa44ad494d98ddf833385ca0e5":{
      "scriptId":"u62"},
    "2b729a019d7049429e07e9acaef4b6bb":{
      "scriptId":"u63"},
    "8ac3be8337564b3dabdda5fd364c55d9":{
      "scriptId":"u64"},
    "b00854b13aa447c5bbd474abf64269fd":{
      "scriptId":"u65"},
    "5be0939df4024259af029b3272838c52":{
      "scriptId":"u66"},
    "abfb780c2a524dc89a4b3ff011e910cc":{
      "scriptId":"u67"}}});