$axure.loadCurrentPage({
  "url":"我的收藏-团购.html",
  "generationDate":new Date(1420531296958.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c9fbb6c6fdc64a70911d2ce0444da9c0",
    "type":"Axure:Page",
    "name":"我的收藏-团购",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd97c55409254cdc83457e75ef316615",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"f922a88d1bb949dfba1acce4bf7bfba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b678ed460e44f599dd22e3f58973d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"a048e46e1b654d2897b19d2ad4fa123c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0583ff4b07040fc9dbde0b3407892de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"7c98174667684c9bb71bddba2fccef57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":433},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f834fe9c2ecb4be3b056152c6f1f0508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":433},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u9.png"}},
{
          "id":"02e732ab74ed48f5b88b9f22346c28e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30bbb015d3db4a87987f13e83971e8ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u11.png"}},
{
          "id":"78f7454d8744441387152999e30c7197",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":74,
              "y":184},
            "size":{
              "width":46,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da46b68005e4ff29e634172bf3373ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":184},
                "size":{
                  "width":46,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ab6130bbe284504a80b836f4eb7c886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":174,
              "y":184},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2462d460f85d426ab6da0677db4c6a7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":174,
                  "y":184},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7517a67f6bfb4f09a9639947b1f25481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":273,
              "y":184},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"217f11e37ef34ab589f07ec7df92a497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":273,
                  "y":184},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18db26949f8348f386923a8fe2005a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":262,
              "y":210},
            "size":{
              "width":56,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd30d8769c73431abb6446d990fd91a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":262,
                  "y":210},
                "size":{
                  "width":56,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏-资讯/u15.png"}},
{
          "id":"bd388e5c5ed54344bea70c368222e89a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":76,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏-资讯",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏-资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"73a7ef937bfd4be7957f3be480054f39",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":181},
            "size":{
              "width":76,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏-店铺",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏-店铺.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"42534919e4574118a25663e3de719106",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":222},
            "size":{
              "width":342,
              "height":455}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"acce23ad392348038b17a91972a68ddc",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"96678b5c598a4839a6af12648d7bfe58",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":24},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e57e1f5d7a8f43fa85e354a64a9f0fce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":24},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u19.png"}},
{
                  "id":"9924d2b1be0d44518e0deab3325c7f58",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":84},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"66af87aba9f740a1b036b39b53d86442",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":3},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da56755509d442b88c39c704ecb157fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":3},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c84b1f99d0694148948273277df9cb56",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":255,
                      "y":63},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a42c824b1290446093bdc9db2ebea3bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":255,
                          "y":63},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e6af0a9226441e78bcf0ce59a40c4f9",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3cdc75ccd194285a735800c4c496429",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":0},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/团购列表/u26.jpg"}},
{
                  "id":"163503e8e1454f66ab92496b15451bff",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":60},
                    "size":{
                      "width":38,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e581ccc9fecf4d8da26f69a9e5e8695e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":60},
                        "size":{
                          "width":38,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ac19c3487c4447db0a1888b5b10768d",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":62},
                    "size":{
                      "width":38,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d21b4473222486ebfcd97c63f0e12b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":62},
                        "size":{
                          "width":38,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9c758c8841b44cb696427b41579f19ae",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":65},
                    "size":{
                      "width":46,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/团购列表/u37_line.png"}},
{
                  "id":"8c0c71bd7eda4e3a87200a90223a57ac",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":185},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"8147765531c843338f47dff21617d93e",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":104},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e137891bba504fe989686e5dacc7706a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":104},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6eb2b52f439a45b29133c6c3e028a23b",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":255,
                      "y":165},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af0878d2c0a04b9e8a0a5ec22b96b46f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":255,
                          "y":165},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e8b375d841bb400785ca9af4bd5fea92",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":100},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99c80d9331364601a2496730321e4bad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":100},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商铺/u100.jpg"}},
{
                  "id":"391d8af49ef7484e8a4fbf05eb083103",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":124},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"100f6ba902b441d3a8e7f133f2f89502",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":124},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"1c29570913554765ad0458b6d0ec40f3",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":224},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8325c0dcfe9544e8b781b9d340a67bb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":224},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u19.png"}},
{
                  "id":"5b9383c8558c482a80d9cc90b9a596aa",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"d1c0f433d04743ca9168e811b6d858c1",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":203},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bff2bb10430e4edfa6e9e0b85fe6dd19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":203},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e1efe1ef01b48c7ab8ac2975dbe831c",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":255,
                      "y":264},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"627b9d44f93346b79e4d05ae0fb045ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":255,
                          "y":264},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2a1acaa97ef046f5a545ec1d5816b06f",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":84},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"b69273b1a4da41ef8b70f19969b45425",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":199},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20e83b5479c64f7dbc46319dd1df0706",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":199},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/团购列表/u26.jpg"}},
{
                  "id":"24266957b9024f13b89a5ffa381a4d22",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":161},
                    "size":{
                      "width":38,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4883b6ff6b224c30bb92a0449b051de8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":161},
                        "size":{
                          "width":38,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fc7d7110f0834893a4cf187b2f1a4ee0",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":164},
                    "size":{
                      "width":38,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29de82c071094a45b5790e7023df1d01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":164},
                        "size":{
                          "width":38,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54cb3bd6d6864e40894a1be5ca36121e",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":169,
                      "y":167},
                    "size":{
                      "width":39,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/选择尺码颜色/u23_line.png"}},
{
                  "id":"df0ea120155d4e09b9748a146d308829",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":261},
                    "size":{
                      "width":38,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19efddff31214d42805d9998d09ee0f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":261},
                        "size":{
                          "width":38,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f8cfb2cec1b3403caa29a74c07ebbc54",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":263},
                    "size":{
                      "width":38,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f3e9e0f9f484f669c6420e0744f6b7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":263},
                        "size":{
                          "width":38,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e051838ea3254652984492d8e4cc6128",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":266},
                    "size":{
                      "width":46,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/团购列表/u37_line.png"}},
{
                  "id":"78dee5e79d4c4e669423cba7231b7caa",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":43},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66fb483f9927456da04cc72676463d35",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":43},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"20d410f623bd4f9f857e4721ffb6f564",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":256,
                      "y":5},
                    "size":{
                      "width":50,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcdcd8e9aaed4a428646fcc5caa676ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":256,
                          "y":5},
                        "size":{
                          "width":50,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"85658f8557af45cfa3cc01761254b7a0",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":143},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"232e2dcff4824c8f980d187f92336e27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":143},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f85bf61900ec4abc930ee01b84d43e2f",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":256,
                      "y":105},
                    "size":{
                      "width":50,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87199e1eea334b16a18d6019025f7919",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":256,
                          "y":105},
                        "size":{
                          "width":50,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c53172ea3aa540e3a0b2384c7eb1b008",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":242},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7aa7c9db1bc4edd92486cf53f0c081f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":242},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8809bd74965445919d1cd12dd9d84146",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":256,
                      "y":204},
                    "size":{
                      "width":50,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfb1c72d2cf6413d92060bb9fb71ca57",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":256,
                          "y":204},
                        "size":{
                          "width":50,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"532411f947834efca64e1933d731e908",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":382},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"bbbbd2a6e5e748128294afadceea5f36",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":301},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46df90c13d9a4896b0ba58500e43de0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":301},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dc3b9b9c83864661a886090b1da80632",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":255,
                      "y":362},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0856b37788474d8880768a7128bea3ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":255,
                          "y":362},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ab9346b8497c4f3295ec7b6b52f07043",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":297},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b078892074b4281b6e87a6ad5d18ad1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":297},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商铺/u100.jpg"}},
{
                  "id":"64bce02fd8394eaa9087af4c1a115817",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":321},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c37be003fd64d6881bc76c49052eac1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":321},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"8caf7a1f53324f799167ec9aed02a87d",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":421},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e190bf0e17144ea8b100687376d669f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":421},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u19.png"}},
{
                  "id":"fb1a8ec25af8455c87a399d289d1179d",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":480},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"eabbebbd819c4f23a3d8d0ee6397a947",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":400},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4bb76f68b943449c862d65c6ad96ced1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":400},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f9e8820bc45c4c8fa4b537e310379df5",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":255,
                      "y":461},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55e8f592d01047af929db22cd4957717",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":255,
                          "y":461},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f01b3dac82a744618578ee9ad7880a5c",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":396},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57645634393841ecb7f68ba4729151d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":396},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/团购列表/u26.jpg"}},
{
                  "id":"a9345225a043485f811aa44f8e79b55a",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":358},
                    "size":{
                      "width":38,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf1b7b8a64f840b2aeac60bcf36e8c71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":358},
                        "size":{
                          "width":38,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5507589dfed461db2f6c08838deafe0",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":361},
                    "size":{
                      "width":38,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10df2a2e9a7b4101a20225eb3cdb8149",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":361},
                        "size":{
                          "width":38,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c114874fcf0482b8204670c03cb9e19",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":169,
                      "y":364},
                    "size":{
                      "width":39,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/选择尺码颜色/u23_line.png"}},
{
                  "id":"e6fa1b8c2b1b45c388d3de244d586394",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":458},
                    "size":{
                      "width":38,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2001b1fef3ef4ea4ae706efe0f263e72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":458},
                        "size":{
                          "width":38,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a6520bc91b58490e88fbcab23f7fb902",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":173,
                      "y":460},
                    "size":{
                      "width":38,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e72e99c3ecec4b57abdec25058ed6c0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":173,
                          "y":460},
                        "size":{
                          "width":38,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1acbb6e703f34160b1e3f259328b0870",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":463},
                    "size":{
                      "width":46,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/团购列表/u37_line.png"}},
{
                  "id":"161d98040e0b4ecab5e2cbc295040fd2",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":340},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6a885b4745142618a9461622183cc08",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":340},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ccd97aec9b754f1f98c7760827dcae74",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":256,
                      "y":302},
                    "size":{
                      "width":50,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"911685740df2418ead453ef472e33cf5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":256,
                          "y":302},
                        "size":{
                          "width":50,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87ad46c741404abc98237a31ef06c781",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":439},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7910c36a507b4a77907ad1881bdc713b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":439},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eb4424f5d36b4bfca0607b3dcabe0d96",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":256,
                      "y":401},
                    "size":{
                      "width":50,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec19381f6c44420aa69460e0825abbf2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":256,
                          "y":401},
                        "size":{
                          "width":50,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ebe552e42f7c4286b0f3dcb27eecf0e8",
                  "label":"",
                  "parentDynamicPanel":"42534919e4574118a25663e3de719106",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":-1},
                    "size":{
                      "width":319,
                      "height":93}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 团购详情",
                              "target":{
                                "targetType":"page",
                                "url":"团购详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "bd97c55409254cdc83457e75ef316615":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "f922a88d1bb949dfba1acce4bf7bfba2":{
      "scriptId":"u5"},
    "f3b678ed460e44f599dd22e3f58973d2":{
      "scriptId":"u6"},
    "a048e46e1b654d2897b19d2ad4fa123c":{
      "scriptId":"u7"},
    "f0583ff4b07040fc9dbde0b3407892de":{
      "scriptId":"u8"},
    "7c98174667684c9bb71bddba2fccef57":{
      "scriptId":"u9"},
    "f834fe9c2ecb4be3b056152c6f1f0508":{
      "scriptId":"u10"},
    "02e732ab74ed48f5b88b9f22346c28e3":{
      "scriptId":"u11"},
    "30bbb015d3db4a87987f13e83971e8ea":{
      "scriptId":"u12"},
    "78f7454d8744441387152999e30c7197":{
      "scriptId":"u13"},
    "2da46b68005e4ff29e634172bf3373ca":{
      "scriptId":"u14"},
    "8ab6130bbe284504a80b836f4eb7c886":{
      "scriptId":"u15"},
    "2462d460f85d426ab6da0677db4c6a7b":{
      "scriptId":"u16"},
    "7517a67f6bfb4f09a9639947b1f25481":{
      "scriptId":"u17"},
    "217f11e37ef34ab589f07ec7df92a497":{
      "scriptId":"u18"},
    "18db26949f8348f386923a8fe2005a07":{
      "scriptId":"u19"},
    "cd30d8769c73431abb6446d990fd91a7":{
      "scriptId":"u20"},
    "bd388e5c5ed54344bea70c368222e89a":{
      "scriptId":"u21"},
    "73a7ef937bfd4be7957f3be480054f39":{
      "scriptId":"u22"},
    "42534919e4574118a25663e3de719106":{
      "scriptId":"u23"},
    "96678b5c598a4839a6af12648d7bfe58":{
      "scriptId":"u24"},
    "e57e1f5d7a8f43fa85e354a64a9f0fce":{
      "scriptId":"u25"},
    "9924d2b1be0d44518e0deab3325c7f58":{
      "scriptId":"u26"},
    "66af87aba9f740a1b036b39b53d86442":{
      "scriptId":"u27"},
    "da56755509d442b88c39c704ecb157fa":{
      "scriptId":"u28"},
    "c84b1f99d0694148948273277df9cb56":{
      "scriptId":"u29"},
    "a42c824b1290446093bdc9db2ebea3bc":{
      "scriptId":"u30"},
    "7e6af0a9226441e78bcf0ce59a40c4f9":{
      "scriptId":"u31"},
    "a3cdc75ccd194285a735800c4c496429":{
      "scriptId":"u32"},
    "163503e8e1454f66ab92496b15451bff":{
      "scriptId":"u33"},
    "e581ccc9fecf4d8da26f69a9e5e8695e":{
      "scriptId":"u34"},
    "6ac19c3487c4447db0a1888b5b10768d":{
      "scriptId":"u35"},
    "0d21b4473222486ebfcd97c63f0e12b3":{
      "scriptId":"u36"},
    "9c758c8841b44cb696427b41579f19ae":{
      "scriptId":"u37"},
    "8c0c71bd7eda4e3a87200a90223a57ac":{
      "scriptId":"u38"},
    "8147765531c843338f47dff21617d93e":{
      "scriptId":"u39"},
    "e137891bba504fe989686e5dacc7706a":{
      "scriptId":"u40"},
    "6eb2b52f439a45b29133c6c3e028a23b":{
      "scriptId":"u41"},
    "af0878d2c0a04b9e8a0a5ec22b96b46f":{
      "scriptId":"u42"},
    "e8b375d841bb400785ca9af4bd5fea92":{
      "scriptId":"u43"},
    "99c80d9331364601a2496730321e4bad":{
      "scriptId":"u44"},
    "391d8af49ef7484e8a4fbf05eb083103":{
      "scriptId":"u45"},
    "100f6ba902b441d3a8e7f133f2f89502":{
      "scriptId":"u46"},
    "1c29570913554765ad0458b6d0ec40f3":{
      "scriptId":"u47"},
    "8325c0dcfe9544e8b781b9d340a67bb5":{
      "scriptId":"u48"},
    "5b9383c8558c482a80d9cc90b9a596aa":{
      "scriptId":"u49"},
    "d1c0f433d04743ca9168e811b6d858c1":{
      "scriptId":"u50"},
    "bff2bb10430e4edfa6e9e0b85fe6dd19":{
      "scriptId":"u51"},
    "7e1efe1ef01b48c7ab8ac2975dbe831c":{
      "scriptId":"u52"},
    "627b9d44f93346b79e4d05ae0fb045ef":{
      "scriptId":"u53"},
    "2a1acaa97ef046f5a545ec1d5816b06f":{
      "scriptId":"u54"},
    "b69273b1a4da41ef8b70f19969b45425":{
      "scriptId":"u55"},
    "20e83b5479c64f7dbc46319dd1df0706":{
      "scriptId":"u56"},
    "24266957b9024f13b89a5ffa381a4d22":{
      "scriptId":"u57"},
    "4883b6ff6b224c30bb92a0449b051de8":{
      "scriptId":"u58"},
    "fc7d7110f0834893a4cf187b2f1a4ee0":{
      "scriptId":"u59"},
    "29de82c071094a45b5790e7023df1d01":{
      "scriptId":"u60"},
    "54cb3bd6d6864e40894a1be5ca36121e":{
      "scriptId":"u61"},
    "df0ea120155d4e09b9748a146d308829":{
      "scriptId":"u62"},
    "19efddff31214d42805d9998d09ee0f5":{
      "scriptId":"u63"},
    "f8cfb2cec1b3403caa29a74c07ebbc54":{
      "scriptId":"u64"},
    "6f3e9e0f9f484f669c6420e0744f6b7a":{
      "scriptId":"u65"},
    "e051838ea3254652984492d8e4cc6128":{
      "scriptId":"u66"},
    "78dee5e79d4c4e669423cba7231b7caa":{
      "scriptId":"u67"},
    "66fb483f9927456da04cc72676463d35":{
      "scriptId":"u68"},
    "20d410f623bd4f9f857e4721ffb6f564":{
      "scriptId":"u69"},
    "dcdcd8e9aaed4a428646fcc5caa676ea":{
      "scriptId":"u70"},
    "85658f8557af45cfa3cc01761254b7a0":{
      "scriptId":"u71"},
    "232e2dcff4824c8f980d187f92336e27":{
      "scriptId":"u72"},
    "f85bf61900ec4abc930ee01b84d43e2f":{
      "scriptId":"u73"},
    "87199e1eea334b16a18d6019025f7919":{
      "scriptId":"u74"},
    "c53172ea3aa540e3a0b2384c7eb1b008":{
      "scriptId":"u75"},
    "f7aa7c9db1bc4edd92486cf53f0c081f":{
      "scriptId":"u76"},
    "8809bd74965445919d1cd12dd9d84146":{
      "scriptId":"u77"},
    "bfb1c72d2cf6413d92060bb9fb71ca57":{
      "scriptId":"u78"},
    "532411f947834efca64e1933d731e908":{
      "scriptId":"u79"},
    "bbbbd2a6e5e748128294afadceea5f36":{
      "scriptId":"u80"},
    "46df90c13d9a4896b0ba58500e43de0b":{
      "scriptId":"u81"},
    "dc3b9b9c83864661a886090b1da80632":{
      "scriptId":"u82"},
    "0856b37788474d8880768a7128bea3ad":{
      "scriptId":"u83"},
    "ab9346b8497c4f3295ec7b6b52f07043":{
      "scriptId":"u84"},
    "1b078892074b4281b6e87a6ad5d18ad1":{
      "scriptId":"u85"},
    "64bce02fd8394eaa9087af4c1a115817":{
      "scriptId":"u86"},
    "8c37be003fd64d6881bc76c49052eac1":{
      "scriptId":"u87"},
    "8caf7a1f53324f799167ec9aed02a87d":{
      "scriptId":"u88"},
    "e190bf0e17144ea8b100687376d669f3":{
      "scriptId":"u89"},
    "fb1a8ec25af8455c87a399d289d1179d":{
      "scriptId":"u90"},
    "eabbebbd819c4f23a3d8d0ee6397a947":{
      "scriptId":"u91"},
    "4bb76f68b943449c862d65c6ad96ced1":{
      "scriptId":"u92"},
    "f9e8820bc45c4c8fa4b537e310379df5":{
      "scriptId":"u93"},
    "55e8f592d01047af929db22cd4957717":{
      "scriptId":"u94"},
    "f01b3dac82a744618578ee9ad7880a5c":{
      "scriptId":"u95"},
    "57645634393841ecb7f68ba4729151d9":{
      "scriptId":"u96"},
    "a9345225a043485f811aa44f8e79b55a":{
      "scriptId":"u97"},
    "cf1b7b8a64f840b2aeac60bcf36e8c71":{
      "scriptId":"u98"},
    "f5507589dfed461db2f6c08838deafe0":{
      "scriptId":"u99"},
    "10df2a2e9a7b4101a20225eb3cdb8149":{
      "scriptId":"u100"},
    "5c114874fcf0482b8204670c03cb9e19":{
      "scriptId":"u101"},
    "e6fa1b8c2b1b45c388d3de244d586394":{
      "scriptId":"u102"},
    "2001b1fef3ef4ea4ae706efe0f263e72":{
      "scriptId":"u103"},
    "a6520bc91b58490e88fbcab23f7fb902":{
      "scriptId":"u104"},
    "e72e99c3ecec4b57abdec25058ed6c0c":{
      "scriptId":"u105"},
    "1acbb6e703f34160b1e3f259328b0870":{
      "scriptId":"u106"},
    "161d98040e0b4ecab5e2cbc295040fd2":{
      "scriptId":"u107"},
    "f6a885b4745142618a9461622183cc08":{
      "scriptId":"u108"},
    "ccd97aec9b754f1f98c7760827dcae74":{
      "scriptId":"u109"},
    "911685740df2418ead453ef472e33cf5":{
      "scriptId":"u110"},
    "87ad46c741404abc98237a31ef06c781":{
      "scriptId":"u111"},
    "7910c36a507b4a77907ad1881bdc713b":{
      "scriptId":"u112"},
    "eb4424f5d36b4bfca0607b3dcabe0d96":{
      "scriptId":"u113"},
    "ec19381f6c44420aa69460e0825abbf2":{
      "scriptId":"u114"},
    "ebe552e42f7c4286b0f3dcb27eecf0e8":{
      "scriptId":"u115"}}});