$axure.loadCurrentPage({
  "url":"我的资料.html",
  "generationDate":new Date(1420531295970.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e86edcc7d06e4e588e7538131241777d",
    "type":"Axure:Page",
    "name":"我的资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5665c1dd1bff47fe9b68a25bd5099aa6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"2f9248ca309c42a590264e2a10811f59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1eca13d7b174533bd9f1e7aaef0c39d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"1019b53d41ed4857a5654f84091ce55f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2d98490b27b4965b9432134ccb0ac49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"26e6f3e0aac344a3b5a3c3e8743ed9db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":193},
            "size":{
              "width":321,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5861bb75596248ae8c16eb7ec9198214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":193},
                "size":{
                  "width":321,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资料/u9.png"}},
{
          "id":"05069576ab68450681705307196de277",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":50,
              "y":212},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3646dd8ed924dea8fec92e19880d619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":50,
                  "y":212},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b455e29cbae4938814f7c2cbc7eddb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":210},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed52c04b8014a83889a627146da775b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":210},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"72c9e266cca44116a1ba3e963ef2839d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":200},
            "size":{
              "width":40,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"903051d101f54fea9a3f519b3da93ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":200},
                "size":{
                  "width":40,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u50.png"}},
{
          "id":"22e8b048881b42698758bdc1cf2cbfa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":245.5},
            "size":{
              "width":321,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fc619ed33f4ced9106dc69f83a6767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":245.5},
                "size":{
                  "width":321,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资料/u9.png"}},
{
          "id":"b7656faac95c48718e155c6a5f758d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":50,
              "y":264.5},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c694983c81ea4d3fa974b05af9c9ccfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":50,
                  "y":264.5},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28b8f349ef6747039a6118cad08bb3ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":283,
              "y":263},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa5f68e15794883af84090c77fdce7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":263},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfbf905666034e518f2f9aec61f315fd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":195},
            "size":{
              "width":321,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 sctx 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["b950907501eb4f7591166f1fd28b091c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"b950907501eb4f7591166f1fd28b091c",
          "label":"sctx",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":568},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"670db8df7fbf4c95a7fb58899bbe1854",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9bfc8bef52514b219e1da3ed3ab40c4e",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":320,
                      "height":545},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9758cb80ad042bebf6c752304dad41d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":320,
                          "height":545},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u58.png"}},
{
                  "id":"cb3b083e314d499f8fb709f24b86ddec",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":305},
                    "size":{
                      "width":320,
                      "height":265},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b9e071a51e44ad5940ca4b6b41b514f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":305},
                        "size":{
                          "width":320,
                          "height":265},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的资料/u27.png"}},
{
                  "id":"75e56d195f84461ca09abb4265a76515",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":361},
                    "size":{
                      "width":320,
                      "height":4},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e802628edbb4d309a1fc15337a766f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":361},
                        "size":{
                          "width":320,
                          "height":4},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u62.png"}},
{
                  "id":"a02555d95134411194530f0f62858598",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":125,
                      "y":321},
                    "size":{
                      "width":91,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a63c234467ab4c8ca78950267082ed6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":125,
                          "y":321},
                        "size":{
                          "width":91,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"93e98637fcc5485683048f44d810571a",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":38,
                      "y":387},
                    "size":{
                      "width":250,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"053be3f773c3411da26cfde20dabc16f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":38,
                          "y":387},
                        "size":{
                          "width":250,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的资料/u33.png"}},
{
                  "id":"f8375383be704d5ea2c52541ca5eed78",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":38,
                      "y":443},
                    "size":{
                      "width":250,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa4d6d39ca424a08b1cada8a526c7ea4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":38,
                          "y":443},
                        "size":{
                          "width":250,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的资料/u33.png"}},
{
                  "id":"7775cdd8f15449ddab98904ae9b0188c",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":38,
                      "y":499},
                    "size":{
                      "width":250,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d78f07ddd8c48dbb3df09cecdbc0e56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":38,
                          "y":499},
                        "size":{
                          "width":250,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的资料/u37.png"}},
{
                  "id":"a49ad277307a44c28bccd3baa8c4016e",
                  "label":"",
                  "parentDynamicPanel":"b950907501eb4f7591166f1fd28b091c",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":38,
                      "y":499},
                    "size":{
                      "width":250,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 sctx 向下滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["b950907501eb4f7591166f1fd28b091c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "5665c1dd1bff47fe9b68a25bd5099aa6":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "2f9248ca309c42a590264e2a10811f59":{
      "scriptId":"u5"},
    "f1eca13d7b174533bd9f1e7aaef0c39d":{
      "scriptId":"u6"},
    "1019b53d41ed4857a5654f84091ce55f":{
      "scriptId":"u7"},
    "f2d98490b27b4965b9432134ccb0ac49":{
      "scriptId":"u8"},
    "26e6f3e0aac344a3b5a3c3e8743ed9db":{
      "scriptId":"u9"},
    "5861bb75596248ae8c16eb7ec9198214":{
      "scriptId":"u10"},
    "05069576ab68450681705307196de277":{
      "scriptId":"u11"},
    "b3646dd8ed924dea8fec92e19880d619":{
      "scriptId":"u12"},
    "7b455e29cbae4938814f7c2cbc7eddb6":{
      "scriptId":"u13"},
    "eed52c04b8014a83889a627146da775b":{
      "scriptId":"u14"},
    "72c9e266cca44116a1ba3e963ef2839d":{
      "scriptId":"u15"},
    "903051d101f54fea9a3f519b3da93ba8":{
      "scriptId":"u16"},
    "22e8b048881b42698758bdc1cf2cbfa1":{
      "scriptId":"u17"},
    "26fc619ed33f4ced9106dc69f83a6767":{
      "scriptId":"u18"},
    "b7656faac95c48718e155c6a5f758d63":{
      "scriptId":"u19"},
    "c694983c81ea4d3fa974b05af9c9ccfe":{
      "scriptId":"u20"},
    "28b8f349ef6747039a6118cad08bb3ae":{
      "scriptId":"u21"},
    "9fa5f68e15794883af84090c77fdce7c":{
      "scriptId":"u22"},
    "bfbf905666034e518f2f9aec61f315fd":{
      "scriptId":"u23"},
    "b950907501eb4f7591166f1fd28b091c":{
      "scriptId":"u24"},
    "9bfc8bef52514b219e1da3ed3ab40c4e":{
      "scriptId":"u25"},
    "e9758cb80ad042bebf6c752304dad41d":{
      "scriptId":"u26"},
    "cb3b083e314d499f8fb709f24b86ddec":{
      "scriptId":"u27"},
    "1b9e071a51e44ad5940ca4b6b41b514f":{
      "scriptId":"u28"},
    "75e56d195f84461ca09abb4265a76515":{
      "scriptId":"u29"},
    "5e802628edbb4d309a1fc15337a766f0":{
      "scriptId":"u30"},
    "a02555d95134411194530f0f62858598":{
      "scriptId":"u31"},
    "a63c234467ab4c8ca78950267082ed6f":{
      "scriptId":"u32"},
    "93e98637fcc5485683048f44d810571a":{
      "scriptId":"u33"},
    "053be3f773c3411da26cfde20dabc16f":{
      "scriptId":"u34"},
    "f8375383be704d5ea2c52541ca5eed78":{
      "scriptId":"u35"},
    "aa4d6d39ca424a08b1cada8a526c7ea4":{
      "scriptId":"u36"},
    "7775cdd8f15449ddab98904ae9b0188c":{
      "scriptId":"u37"},
    "2d78f07ddd8c48dbb3df09cecdbc0e56":{
      "scriptId":"u38"},
    "a49ad277307a44c28bccd3baa8c4016e":{
      "scriptId":"u39"}}});