$axure.loadCurrentPage({
  "url":"生活服务列表.html",
  "generationDate":new Date(1420531290339.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"46ed4c32175c4df09e8a730db067e03f",
    "type":"Axure:Page",
    "name":"生活服务列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c2a0b085325a407abcff977530ee6b77",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"36155ca0d8c74be9ac74ca24590a2b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1920fd90b35a4763b71d169e7daf0b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"b867e7d756a94ec887475bee90df9bc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80cd93f614bb42c6941e1a5023869436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 生活服务",
                      "target":{
                        "targetType":"page",
                        "url":"生活服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"dea96f926a624792a2c2bd58db299d0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":508},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f53391db4a43d7904d131f07759c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":508},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻详情/u9.png"}},
{
          "id":"13106b062aa346549dc743c33a5dfbb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":165,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61cc541d0128483db201f3daeba3bb70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":165,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u11.png"}},
{
          "id":"ff4a25c23d2f48f6a1a9784ff7a7928b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":213},
            "size":{
              "width":342,
              "height":414}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d98fd6deec224c1b83c5c431e411e694",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3bf5c24b10494e6d9de73f3362bb1ce4",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":70},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c8a5cf811f944c1a904bfa247898d5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":70},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"5fe81a44bbbd4e8c891c81046991366e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":72},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86cd8261b2ac4527b67b6556884207c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":72},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a41ca3795d024e42ad6407940752fd94",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"4decd258d13c4f19b9a0397bc7faa0bf",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":15},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c7aaf377b1d4a80a9b9b03473058a85",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":15},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8acf3b683f0a4069bdc3adbbab5d30b8",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":44},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bab7ded57b842bd917cfce5d4a5f8d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":44},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08fe0dce9bab4868a905e999a36e6880",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":76},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b6a4cbf609e423d8671afc075f8ccbc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":76},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65799a8c931c45719f54c0aa703e7193",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"653cd3292c044839933c2c5320499af6",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":109},
                    "size":{
                      "width":198,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbbdeb0a1d1449ce8092f6e61eb774f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":109},
                        "size":{
                          "width":198,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"812ff068a6f74304b076ae4632c8756a",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":147},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd1a6b62ec034c6a96a340c8221d484c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":147},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"53e965817abe4e7d8bc3d0311e1ac227",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":175},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5124b11423842879787f3799bbc73d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":175},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"16818762c1f74c3796b16b5ed9017a96",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":292},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"ffabc4784a0b4ef895420065f256f04a",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":208},
                    "size":{
                      "width":200,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62b0d707a67f4169a2ecbec207910a00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":208},
                        "size":{
                          "width":200,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4268df1386ea4706b1d9694181b3269e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":246},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db8d204210564f7392af60a96d556233",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":246},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9c1c84647624474dad5a20a657a62ae6",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":274},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"353749b4e8b744a6b5219a40d98ddde3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":274},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"61f52843b89c4d54aad4077f6877acf1",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"f6fae8be6c994b71afee3eba8725c58a",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":391},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"f4c9ecbe4eaa4ecda705f0c74c541128",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":311},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7246537e928e4658838c2cc77676306f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":311},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0be53ca33b6740cb890c27d9b5ace4ee",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":342},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acfc337b66b7477fb7e0352120be3cde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":342},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"29144e42ea0b49b08486be80a4c6b87d",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":373},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb485f5d42634ade9398257731fee960",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":373},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b5fc5f28d1dd4269826cc9474a2fbb6a",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":10},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c6e88a1115045a094bc23ad89208ca6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":10},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u47.png"}},
{
                  "id":"92eaf5c65154455fa5b87bae36988ec0",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":208},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41dc84c1c4fe4d2d97418fff7330a411",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":208},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u49.png"}},
{
                  "id":"8a276c2bf5184edb96ed53db707acb21",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":109},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb10230b2c4b4950b5455f3d943d09e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":109},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u51.jpg"}},
{
                  "id":"6902689cb0e8401583d4fcc99b2e2129",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "lineSpacing":"28px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":8,
                      "y":306},
                    "size":{
                      "width":106,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10d2307c70ed498c8567fdf98daa8529",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "lineSpacing":"28px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":8,
                          "y":306},
                        "size":{
                          "width":106,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u53.png"}},
{
                  "id":"981abf77125c4f0ba8d71c83722e268f",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"918b5c50c9b246f1abb046e7f50aa75e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":406},
                    "size":{
                      "width":200,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"172efb6a852744bd82828e8079257dde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":406},
                        "size":{
                          "width":200,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4f1501d8505d4218a723e38a8c820ff1",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":444},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4fa086f873e4caf8a3bdda2a5f108d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":444},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4f8039844e3d458f8467f28bef1bb184",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":472},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b82b9b516bc341929afcf2b60034b938",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":472},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"29aec1b4ba774cdda6d0f9766e54ef43",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":391},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"6bd147ebe9ef4542b11bdb18e1b8c9c1",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":589},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"22536734a1f44f2f955b735aa6bf7db6",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":509},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c7de5eddfaf490385272d25f521a84f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":509},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b7861d6815164d129b0b86c9d25c80b3",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":540},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bc7c9809d534d26ad412699e3fbb541",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":540},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fe4c4e925032452a9388d6813ea0c92b",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":571},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ced8ece7d6545eb8b9a0a6627de2ced",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":571},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"98dc8af8af154ef7adf42e20a1cb778c",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":406},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a312c1b1f3044a38acb68611f0b2f2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":406},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u49.png"}},
{
                  "id":"1016f4fc7c534e59a5ff62008a9009a2",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "lineSpacing":"28px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":8,
                      "y":504},
                    "size":{
                      "width":106,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1a8b3c8c3ee345269a94fadce649cc9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "lineSpacing":"28px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":8,
                          "y":504},
                        "size":{
                          "width":106,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u53.png"}},
{
                  "id":"0da75cef6c97419584d433978c33d4ba",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":0},
                    "size":{
                      "width":314,
                      "height":99}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 生活服务详情",
                              "target":{
                                "targetType":"page",
                                "url":"生活服务详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"dd27b788ebc0483d82f995250925c0e4",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":170},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a0a68afc9524f48bbfefb75d0293a3b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":170},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"d1d9b422030c49aab99e2755432b5edc",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":172},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98e555f9a8534c8fbcdf6c32536d051e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":172},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3d918bafdd884b819793a5066060ad55",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":270},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f986f3f87d74f6ea072e2caec287ec8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":270},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"dc9c2a31653747b89a0edcb6341d1d3f",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":272},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91bd3ca155694aef9fede386d3f8bd70",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":272},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a3e1e605a7c447c987cf3ad61706f490",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":366},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc2b8025b59d46d0b631be518f102bc5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":366},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"e3ab50e3e5d248f79fa3294fe04f1539",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":368},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5adb8c09a93b49b08d3c4255bdf98962",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":368},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e27eee4dd9244abea6e64e5b8eeca0dd",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":466},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b4a55013e054a68a3588f0a8593ad84",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":466},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"3b230becf85749ee879790e26cb03011",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":468},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c4bd28a71af44f18b7e2626539a232e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":468},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ad0c226aa1d341a59a9fa1c25c7c3585",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":564},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00eecf55fd5f45b4b7a8f92776a6215f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":564},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"3cd8d790e94f4063a4fc3adeb69fc949",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":566},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf0858f1d7794d1a85a344aae1ef938e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":566},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e137370cbf5644c9ac501951eb0b4bab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1483e0a19f864965afa4f878561a85f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信息发布",
                      "target":{
                        "targetType":"page",
                        "url":"信息发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/房产列表/u129.png"}},
{
          "id":"d7516a49c3be49c695d71ff0a296acf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":137,
              "y":192},
            "size":{
              "width":10,
              "height":8},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13bca617419d44cbb61d964a0ac09652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":137,
                  "y":192},
                "size":{
                  "width":10,
                  "height":8},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u97.png"}},
{
          "id":"9a2752abf27e475e8cc11cdc1d4c6906",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":196,
              "y":177},
            "size":{
              "width":157,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7831bcd072184ddc85447d8d7d03a264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":196,
                  "y":177},
                "size":{
                  "width":157,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u99.png"}},
{
          "id":"7d4b375f753f4e5ba6265fb15906888d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":189},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"045eb696efa34c7e89d1feaf04bd4593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":189},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u101.png"}},
{
          "id":"bce9f5b3ef0847fba55ef975b00c8910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":637},
            "size":{
              "width":321,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20fe448d55c14064a13e1f1105c436bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":637},
                "size":{
                  "width":321,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u85.png"}},
{
          "id":"64f19c79d3ed40fb95d457bebf520736",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":647},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表/u87_line.png"}},
{
          "id":"990f2c477ef14ae991154dd75540293f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":646},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ead1210782341508811aa10bc46b734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":646},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u88.png"}},
{
          "id":"b62bcdd0d60641f9bbd34d3aa19099ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF662C,
              "opacity":1},
            "location":{
              "x":115,
              "y":652},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fb557d024d549b5a5515d358b072188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF662C,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":652},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ec5b45ade6547eda92c47283556aa2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":272,
              "y":652},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa8a08dcf0db4b389a73da0eb4b26253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":272,
                  "y":652},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab4186b14d504c5f87c0a48cfbd4d037",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":646},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e194ff6d481f4f4585359bfdd71fb49d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":646},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u94.png"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "c2a0b085325a407abcff977530ee6b77":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "36155ca0d8c74be9ac74ca24590a2b90":{
      "scriptId":"u5"},
    "1920fd90b35a4763b71d169e7daf0b93":{
      "scriptId":"u6"},
    "b867e7d756a94ec887475bee90df9bc8":{
      "scriptId":"u7"},
    "80cd93f614bb42c6941e1a5023869436":{
      "scriptId":"u8"},
    "dea96f926a624792a2c2bd58db299d0f":{
      "scriptId":"u9"},
    "62f53391db4a43d7904d131f07759c3e":{
      "scriptId":"u10"},
    "13106b062aa346549dc743c33a5dfbb6":{
      "scriptId":"u11"},
    "61cc541d0128483db201f3daeba3bb70":{
      "scriptId":"u12"},
    "ff4a25c23d2f48f6a1a9784ff7a7928b":{
      "scriptId":"u13"},
    "3bf5c24b10494e6d9de73f3362bb1ce4":{
      "scriptId":"u14"},
    "6c8a5cf811f944c1a904bfa247898d5a":{
      "scriptId":"u15"},
    "5fe81a44bbbd4e8c891c81046991366e":{
      "scriptId":"u16"},
    "86cd8261b2ac4527b67b6556884207c3":{
      "scriptId":"u17"},
    "a41ca3795d024e42ad6407940752fd94":{
      "scriptId":"u18"},
    "4decd258d13c4f19b9a0397bc7faa0bf":{
      "scriptId":"u19"},
    "5c7aaf377b1d4a80a9b9b03473058a85":{
      "scriptId":"u20"},
    "8acf3b683f0a4069bdc3adbbab5d30b8":{
      "scriptId":"u21"},
    "7bab7ded57b842bd917cfce5d4a5f8d8":{
      "scriptId":"u22"},
    "08fe0dce9bab4868a905e999a36e6880":{
      "scriptId":"u23"},
    "5b6a4cbf609e423d8671afc075f8ccbc":{
      "scriptId":"u24"},
    "65799a8c931c45719f54c0aa703e7193":{
      "scriptId":"u25"},
    "653cd3292c044839933c2c5320499af6":{
      "scriptId":"u26"},
    "fbbdeb0a1d1449ce8092f6e61eb774f3":{
      "scriptId":"u27"},
    "812ff068a6f74304b076ae4632c8756a":{
      "scriptId":"u28"},
    "dd1a6b62ec034c6a96a340c8221d484c":{
      "scriptId":"u29"},
    "53e965817abe4e7d8bc3d0311e1ac227":{
      "scriptId":"u30"},
    "d5124b11423842879787f3799bbc73d8":{
      "scriptId":"u31"},
    "16818762c1f74c3796b16b5ed9017a96":{
      "scriptId":"u32"},
    "ffabc4784a0b4ef895420065f256f04a":{
      "scriptId":"u33"},
    "62b0d707a67f4169a2ecbec207910a00":{
      "scriptId":"u34"},
    "4268df1386ea4706b1d9694181b3269e":{
      "scriptId":"u35"},
    "db8d204210564f7392af60a96d556233":{
      "scriptId":"u36"},
    "9c1c84647624474dad5a20a657a62ae6":{
      "scriptId":"u37"},
    "353749b4e8b744a6b5219a40d98ddde3":{
      "scriptId":"u38"},
    "61f52843b89c4d54aad4077f6877acf1":{
      "scriptId":"u39"},
    "f6fae8be6c994b71afee3eba8725c58a":{
      "scriptId":"u40"},
    "f4c9ecbe4eaa4ecda705f0c74c541128":{
      "scriptId":"u41"},
    "7246537e928e4658838c2cc77676306f":{
      "scriptId":"u42"},
    "0be53ca33b6740cb890c27d9b5ace4ee":{
      "scriptId":"u43"},
    "acfc337b66b7477fb7e0352120be3cde":{
      "scriptId":"u44"},
    "29144e42ea0b49b08486be80a4c6b87d":{
      "scriptId":"u45"},
    "cb485f5d42634ade9398257731fee960":{
      "scriptId":"u46"},
    "b5fc5f28d1dd4269826cc9474a2fbb6a":{
      "scriptId":"u47"},
    "3c6e88a1115045a094bc23ad89208ca6":{
      "scriptId":"u48"},
    "92eaf5c65154455fa5b87bae36988ec0":{
      "scriptId":"u49"},
    "41dc84c1c4fe4d2d97418fff7330a411":{
      "scriptId":"u50"},
    "8a276c2bf5184edb96ed53db707acb21":{
      "scriptId":"u51"},
    "bb10230b2c4b4950b5455f3d943d09e3":{
      "scriptId":"u52"},
    "6902689cb0e8401583d4fcc99b2e2129":{
      "scriptId":"u53"},
    "10d2307c70ed498c8567fdf98daa8529":{
      "scriptId":"u54"},
    "981abf77125c4f0ba8d71c83722e268f":{
      "scriptId":"u55"},
    "918b5c50c9b246f1abb046e7f50aa75e":{
      "scriptId":"u56"},
    "172efb6a852744bd82828e8079257dde":{
      "scriptId":"u57"},
    "4f1501d8505d4218a723e38a8c820ff1":{
      "scriptId":"u58"},
    "e4fa086f873e4caf8a3bdda2a5f108d0":{
      "scriptId":"u59"},
    "4f8039844e3d458f8467f28bef1bb184":{
      "scriptId":"u60"},
    "b82b9b516bc341929afcf2b60034b938":{
      "scriptId":"u61"},
    "29aec1b4ba774cdda6d0f9766e54ef43":{
      "scriptId":"u62"},
    "6bd147ebe9ef4542b11bdb18e1b8c9c1":{
      "scriptId":"u63"},
    "22536734a1f44f2f955b735aa6bf7db6":{
      "scriptId":"u64"},
    "6c7de5eddfaf490385272d25f521a84f":{
      "scriptId":"u65"},
    "b7861d6815164d129b0b86c9d25c80b3":{
      "scriptId":"u66"},
    "0bc7c9809d534d26ad412699e3fbb541":{
      "scriptId":"u67"},
    "fe4c4e925032452a9388d6813ea0c92b":{
      "scriptId":"u68"},
    "5ced8ece7d6545eb8b9a0a6627de2ced":{
      "scriptId":"u69"},
    "98dc8af8af154ef7adf42e20a1cb778c":{
      "scriptId":"u70"},
    "5a312c1b1f3044a38acb68611f0b2f2d":{
      "scriptId":"u71"},
    "1016f4fc7c534e59a5ff62008a9009a2":{
      "scriptId":"u72"},
    "1a8b3c8c3ee345269a94fadce649cc9a":{
      "scriptId":"u73"},
    "0da75cef6c97419584d433978c33d4ba":{
      "scriptId":"u74"},
    "dd27b788ebc0483d82f995250925c0e4":{
      "scriptId":"u75"},
    "2a0a68afc9524f48bbfefb75d0293a3b":{
      "scriptId":"u76"},
    "d1d9b422030c49aab99e2755432b5edc":{
      "scriptId":"u77"},
    "98e555f9a8534c8fbcdf6c32536d051e":{
      "scriptId":"u78"},
    "3d918bafdd884b819793a5066060ad55":{
      "scriptId":"u79"},
    "7f986f3f87d74f6ea072e2caec287ec8":{
      "scriptId":"u80"},
    "dc9c2a31653747b89a0edcb6341d1d3f":{
      "scriptId":"u81"},
    "91bd3ca155694aef9fede386d3f8bd70":{
      "scriptId":"u82"},
    "a3e1e605a7c447c987cf3ad61706f490":{
      "scriptId":"u83"},
    "bc2b8025b59d46d0b631be518f102bc5":{
      "scriptId":"u84"},
    "e3ab50e3e5d248f79fa3294fe04f1539":{
      "scriptId":"u85"},
    "5adb8c09a93b49b08d3c4255bdf98962":{
      "scriptId":"u86"},
    "e27eee4dd9244abea6e64e5b8eeca0dd":{
      "scriptId":"u87"},
    "8b4a55013e054a68a3588f0a8593ad84":{
      "scriptId":"u88"},
    "3b230becf85749ee879790e26cb03011":{
      "scriptId":"u89"},
    "7c4bd28a71af44f18b7e2626539a232e":{
      "scriptId":"u90"},
    "ad0c226aa1d341a59a9fa1c25c7c3585":{
      "scriptId":"u91"},
    "00eecf55fd5f45b4b7a8f92776a6215f":{
      "scriptId":"u92"},
    "3cd8d790e94f4063a4fc3adeb69fc949":{
      "scriptId":"u93"},
    "bf0858f1d7794d1a85a344aae1ef938e":{
      "scriptId":"u94"},
    "e137370cbf5644c9ac501951eb0b4bab":{
      "scriptId":"u95"},
    "1483e0a19f864965afa4f878561a85f7":{
      "scriptId":"u96"},
    "d7516a49c3be49c695d71ff0a296acf7":{
      "scriptId":"u97"},
    "13bca617419d44cbb61d964a0ac09652":{
      "scriptId":"u98"},
    "9a2752abf27e475e8cc11cdc1d4c6906":{
      "scriptId":"u99"},
    "7831bcd072184ddc85447d8d7d03a264":{
      "scriptId":"u100"},
    "7d4b375f753f4e5ba6265fb15906888d":{
      "scriptId":"u101"},
    "045eb696efa34c7e89d1feaf04bd4593":{
      "scriptId":"u102"},
    "bce9f5b3ef0847fba55ef975b00c8910":{
      "scriptId":"u103"},
    "20fe448d55c14064a13e1f1105c436bd":{
      "scriptId":"u104"},
    "64f19c79d3ed40fb95d457bebf520736":{
      "scriptId":"u105"},
    "990f2c477ef14ae991154dd75540293f":{
      "scriptId":"u106"},
    "1ead1210782341508811aa10bc46b734":{
      "scriptId":"u107"},
    "b62bcdd0d60641f9bbd34d3aa19099ab":{
      "scriptId":"u108"},
    "2fb557d024d549b5a5515d358b072188":{
      "scriptId":"u109"},
    "4ec5b45ade6547eda92c47283556aa2b":{
      "scriptId":"u110"},
    "aa8a08dcf0db4b389a73da0eb4b26253":{
      "scriptId":"u111"},
    "ab4186b14d504c5f87c0a48cfbd4d037":{
      "scriptId":"u112"},
    "e194ff6d481f4f4585359bfdd71fb49d":{
      "scriptId":"u113"}}});