$axure.loadCurrentPage({
  "url":"找回密码.html",
  "generationDate":new Date(1420531287178.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f9a8168fb29642c8a7695f9b943d7660",
    "type":"Axure:Page",
    "name":"找回密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f16b6068f6f42bbb53264679589f4a7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"02b214b810f843f1a32913dc69ab0b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd1ea2183f7413a9ac6326bacdfd843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"27095cad27634ee3997f3be68eeb942e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d0d39ef2244add8f3f766da69a580a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"84986a2963954060b3c777635f397a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":44,
              "y":347},
            "size":{
              "width":296,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9269a1bae57e49f6998f77dc91d0a6d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":44,
                  "y":347},
                "size":{
                  "width":296,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置新密码",
                      "target":{
                        "targetType":"page",
                        "url":"设置新密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u36.png"}},
{
          "id":"f7d4f8c375a24b8698e1286c4e2237e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":204},
            "size":{
              "width":298,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f511d04aba487699fd8e1275492e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":204},
                "size":{
                  "width":298,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u9.png"}},
{
          "id":"85b1a4051b994c6897635a9ffed7d754",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":254},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"5280e8fd736347979b08868252f2f5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":104,
              "y":223},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225d2d0799244993bbaf1ecebcfc9430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":223},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc0ace4bd97843579c4867ea7224ba5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":104,
              "y":277},
            "size":{
              "width":156,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f12f51c4904a49b2ebf5d0b7fbac3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":277},
                "size":{
                  "width":156,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0705dfcc1ca84f7eb53769cc226fb45f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":214},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97412658b0ee4af6a1aba973e8f896b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":214},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u18.png"}},
{
          "id":"ced2d1c9501244feb086e74155c957ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":268},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df02604f3b6424b8c016f39a246a5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":268},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u20.png"}},
{
          "id":"84a69c94a3314e65afb318636797b332",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":259,
              "y":213},
            "size":{
              "width":73,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d192bf99ba0f4405960a54ed5c689ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":259,
                  "y":213},
                "size":{
                  "width":73,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u22.png"}},
{
          "id":"cca639e9c00f41e7b669fd1ea982caa1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":219},
            "size":{
              "width":25,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11971241ea4542558b7dff4031c5b6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":219},
                "size":{
                  "width":25,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u24.png"}},
{
          "id":"d5916e42c9ca43f0be622129bded0cb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":470},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01436e94f982443a8ca2350d13c61827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":470},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u26.png"}},
{
          "id":"283496429aa8477f842477b14af7a949",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":413},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/找回密码/u28_end.png",
            "line~":"images/找回密码/u28_line.png"}},
{
          "id":"39126fff57ad41f8abfc1bfea5a04f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":540,
              "y":406},
            "size":{
              "width":220,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9e6199e79544acb91066b86a1cbb11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":406},
                "size":{
                  "width":220,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18004904e26c4b20a6bf8f9d0e9cbe20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":276,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"797d7f70d89444c583f9902a4b687b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":276,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "8f16b6068f6f42bbb53264679589f4a7":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "02b214b810f843f1a32913dc69ab0b85":{
      "scriptId":"u5"},
    "2cd1ea2183f7413a9ac6326bacdfd843":{
      "scriptId":"u6"},
    "27095cad27634ee3997f3be68eeb942e":{
      "scriptId":"u7"},
    "e5d0d39ef2244add8f3f766da69a580a":{
      "scriptId":"u8"},
    "84986a2963954060b3c777635f397a46":{
      "scriptId":"u9"},
    "9269a1bae57e49f6998f77dc91d0a6d9":{
      "scriptId":"u10"},
    "f7d4f8c375a24b8698e1286c4e2237e9":{
      "scriptId":"u11"},
    "c9f511d04aba487699fd8e1275492e9d":{
      "scriptId":"u12"},
    "85b1a4051b994c6897635a9ffed7d754":{
      "scriptId":"u13"},
    "5280e8fd736347979b08868252f2f5a1":{
      "scriptId":"u14"},
    "225d2d0799244993bbaf1ecebcfc9430":{
      "scriptId":"u15"},
    "bc0ace4bd97843579c4867ea7224ba5a":{
      "scriptId":"u16"},
    "96f12f51c4904a49b2ebf5d0b7fbac3c":{
      "scriptId":"u17"},
    "0705dfcc1ca84f7eb53769cc226fb45f":{
      "scriptId":"u18"},
    "97412658b0ee4af6a1aba973e8f896b5":{
      "scriptId":"u19"},
    "ced2d1c9501244feb086e74155c957ad":{
      "scriptId":"u20"},
    "8df02604f3b6424b8c016f39a246a5b5":{
      "scriptId":"u21"},
    "84a69c94a3314e65afb318636797b332":{
      "scriptId":"u22"},
    "d192bf99ba0f4405960a54ed5c689ea1":{
      "scriptId":"u23"},
    "cca639e9c00f41e7b669fd1ea982caa1":{
      "scriptId":"u24"},
    "11971241ea4542558b7dff4031c5b6f9":{
      "scriptId":"u25"},
    "d5916e42c9ca43f0be622129bded0cb5":{
      "scriptId":"u26"},
    "01436e94f982443a8ca2350d13c61827":{
      "scriptId":"u27"},
    "283496429aa8477f842477b14af7a949":{
      "scriptId":"u28"},
    "39126fff57ad41f8abfc1bfea5a04f36":{
      "scriptId":"u29"},
    "ff9e6199e79544acb91066b86a1cbb11":{
      "scriptId":"u30"},
    "18004904e26c4b20a6bf8f9d0e9cbe20":{
      "scriptId":"u31"},
    "797d7f70d89444c583f9902a4b687b9f":{
      "scriptId":"u32"}}});