$axure.loadCurrentPage({
  "url":"招聘详情.html",
  "generationDate":new Date(1420531288617.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"51c5eb96f6244f98aee4c3fadd08490e",
    "type":"Axure:Page",
    "name":"招聘详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be35e684d9b74bc581ab846797a3d323",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"7b82670a043d49ab98c9baa2717d443d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b2d47989654a968bcd1489fa7c075b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"5b7f43ae9f6f4c2eadb4dfdb7a6ea648",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411ca0f582ce49c7a52bbd27e34cb4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 招聘列表",
                      "target":{
                        "targetType":"page",
                        "url":"招聘列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"51add27ca33547b98705bed0d7799bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":630},
            "size":{
              "width":321,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba82c7ba910a4d06afd1080de989e4bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":630},
                "size":{
                  "width":321,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u9.png"}},
{
          "id":"6635696a310f4029be66ddd8cc888dff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":45,
              "y":638},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cbee05cf02d4f0aa06db19ba89b96e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":45,
                  "y":638},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e282ff03abf04d819ac09ee2e191986b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":44,
              "y":662},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7aee864386348ca96e117d0887f78c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":662},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5820c9daef4b4da3aada512619377002",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":637},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘详情/u15_line.png"}},
{
          "id":"2fed99ed8b854f58a728218635fa13df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":641},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e2a6bd528949a3a97f5c3e3eb3da86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":641},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u16.png"}},
{
          "id":"eac7b1fe64874c26a426a3ddbd1fde05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":144},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9f7daeeec842df911b669fc2b17df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":144},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 fenxiang 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["dbe35fd656a947fc8e7c8e79998c746b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u18.png"}},
{
          "id":"8a0a7a4c180e4380bad53c73fd85402c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":27,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8981e714cd4766b64823a7b9944231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":27,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 cg",
                      "objectsToFades":[{
                          "objectPath":["2a14de516212424ca90443e851643131"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 cg",
                      "objectsToFades":[{
                          "objectPath":["2a14de516212424ca90443e851643131"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u20.png"}},
{
          "id":"1e7f660e9b5f43569008a96dd88dab29",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":177},
            "size":{
              "width":341,
              "height":443}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9296fac1a75f46319509a76d398dcb78",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b8707db59b844afa3e2b532f84807a8",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":239},
                    "size":{
                      "width":302,
                      "height":353},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9adf131fd45477aabaf50d344c34fec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":239},
                        "size":{
                          "width":302,
                          "height":353},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u23.png"}},
{
                  "id":"a91a2dd731c44360b3d1a68cc0bc88af",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":12,
                      "y":172},
                    "size":{
                      "width":298,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77cec34fee5b48538ad2b523e5a1a500",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":12,
                          "y":172},
                        "size":{
                          "width":298,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8e79b6bf1fb460c91df119fddd542c3",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":213},
                    "size":{
                      "width":146,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7ac7eac2d81459084377c70672b7948",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":213},
                        "size":{
                          "width":146,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c4cce5a237448ba8b9ebe401da0ff32",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":282},
                    "size":{
                      "width":121,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5d6e769ccf24a789f3a3e486e22b194",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":282},
                        "size":{
                          "width":121,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdbef536b8f14e84a1c8c3bba4660647",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":313},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5450e25f06f344a09f58a58708a7cfb0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":313},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"90aaa93120db4292b4f87b3518f996dd",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":337},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cf343c522d445308338ef7009371eaf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":337},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"00bbcbcfcb4d43a1bd91e9a923c90a65",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":361},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a0776f3997e456690f15f7b00190b52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":361},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cb0a8d6bb4974a17a2d92991b986a96d",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":250},
                    "size":{
                      "width":78,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9c3be21dbb44d98bbd5de44f8132eb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":250},
                        "size":{
                          "width":78,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3da88a6d098049dc9274b414c363cb2b",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"24px",
                    "location":{
                      "x":31,
                      "y":386},
                    "size":{
                      "width":253,
                      "height":144}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6044a9a37b0f4f7dbd4e7da4b95717e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"24px",
                        "location":{
                          "x":31,
                          "y":386},
                        "size":{
                          "width":253,
                          "height":144}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"284a66abac6e437d9f263bd677a83c53",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":550},
                    "size":{
                      "width":255,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df4727262ec94c219cbe9bec4cdfed33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":550},
                        "size":{
                          "width":255,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3a23a19b49e54a95902659c093f0d144",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":535},
                    "size":{
                      "width":302,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u43_line.png"}},
{
                  "id":"d214016046cb4307a585239994e9f19b",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":270},
                    "size":{
                      "width":280,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u44_line.png"}},
{
                  "id":"7150ed82bcda4b7ba1c4893b211d24ea",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":258,
                      "y":205},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2cbf3375e5e46dd809dc366937d4773",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":258,
                          "y":205},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"ae87790207fb4176ab71735f1c5b23ef",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":288,
                      "y":209},
                    "size":{
                      "width":22,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fffa3e0243b498d887306109097a138",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":288,
                          "y":209},
                        "size":{
                          "width":22,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d5e54102ed9c4bf4a4ec848dcfe184fd",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26bec4f7d363413cafda22fbfea3d5ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u49.jpg"}},
{
                  "id":"6f8859c3c940493881786d3d2277b0b0",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":137,
                      "y":135},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"212cec645ed1428d90575408e0a8315f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":137,
                          "y":135},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"a8e9bc90a8fe4c1faf58cdc57248b2e2",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":161,
                      "y":135},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f6b75aaac534400887a081de655e389",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":161,
                          "y":135},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"13a10379f2ae4a72aa6477112fc36e5f",
                  "label":"",
                  "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":185,
                      "y":135},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"417f5117dfd84e1fbba12761d5417c31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e7f660e9b5f43569008a96dd88dab29",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":185,
                          "y":135},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"dbe35fd656a947fc8e7c8e79998c746b",
          "label":"fenxiang",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":568},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4abd344973e44d859d503a99874bb33d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7e78d468a607456baffa653952c3161a",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":320,
                      "height":545},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"551bed26de7949fcb0e7db735e7c21df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":320,
                          "height":545},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u58.png"}},
{
                  "id":"c0c8953d2dec4579a6627c4ae2ca636c",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":304},
                    "size":{
                      "width":321,
                      "height":265},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47d9254aa2a9402d8e85e6d59f4978d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":304},
                        "size":{
                          "width":321,
                          "height":265},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u60.png"}},
{
                  "id":"a862b9ebcae2400682514159e2a0e83f",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":359},
                    "size":{
                      "width":320,
                      "height":4},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b81e965363bf4ff68b5f43e419d2c54a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":359},
                        "size":{
                          "width":320,
                          "height":4},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u62.png"}},
{
                  "id":"7812e1452f8f485d9194b70c74fa1524",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":144,
                      "y":322},
                    "size":{
                      "width":39,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8c68a94f58e4b16a62f62f355d1dc29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":144,
                          "y":322},
                        "size":{
                          "width":39,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dc313486107e4242b1d06c3cf4b0b9b0",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2dd4838be29d4abc84ef585ebb9fd576",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":20,
                          "y":507},
                        "size":{
                          "width":280,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u66.png"}},
{
                  "id":"e1cf7361d1774131a01bf043bdcb47de",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 fenxiang 向下滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["dbe35fd656a947fc8e7c8e79998c746b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"24e1055c635c44c0982fe563b9d7f72a",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36048b1a32354e83bbd1589f11fa4e23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u69.png"}},
{
                  "id":"f37886f01a4349459cf2bbf93c6f9b20",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":192,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5fa0c85f53647f6a3b60d8e9449c971",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":192,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u71.png"}},
{
                  "id":"887d67716e40446abd0e4f16bf046228",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":48,
                      "y":471},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85e451538a7b4d3baf9bbaa5d4ddb517",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":48,
                          "y":471},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7152c14fd7074acea37437c259789d30",
                  "label":"",
                  "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":194,
                      "y":471},
                    "size":{
                      "width":83,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c78086b85fbb43569748c558fe5f6835",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dbe35fd656a947fc8e7c8e79998c746b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":194,
                          "y":471},
                        "size":{
                          "width":83,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2a14de516212424ca90443e851643131",
          "label":"cg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":109,
              "y":380},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"001ee0a1f735420f8a2b110d015a7aa9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"58bb87cb19924bc7858bb4423b1f24e2",
                  "label":"cg",
                  "parentDynamicPanel":"2a14de516212424ca90443e851643131",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":150,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4dd9eb4c1ebe461597f10c7d87e237e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a14de516212424ca90443e851643131",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":150,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/cg_u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "be35e684d9b74bc581ab846797a3d323":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "7b82670a043d49ab98c9baa2717d443d":{
      "scriptId":"u5"},
    "92b2d47989654a968bcd1489fa7c075b":{
      "scriptId":"u6"},
    "5b7f43ae9f6f4c2eadb4dfdb7a6ea648":{
      "scriptId":"u7"},
    "411ca0f582ce49c7a52bbd27e34cb4d4":{
      "scriptId":"u8"},
    "51add27ca33547b98705bed0d7799bf8":{
      "scriptId":"u9"},
    "ba82c7ba910a4d06afd1080de989e4bc":{
      "scriptId":"u10"},
    "6635696a310f4029be66ddd8cc888dff":{
      "scriptId":"u11"},
    "9cbee05cf02d4f0aa06db19ba89b96e2":{
      "scriptId":"u12"},
    "e282ff03abf04d819ac09ee2e191986b":{
      "scriptId":"u13"},
    "a7aee864386348ca96e117d0887f78c9":{
      "scriptId":"u14"},
    "5820c9daef4b4da3aada512619377002":{
      "scriptId":"u15"},
    "2fed99ed8b854f58a728218635fa13df":{
      "scriptId":"u16"},
    "a1e2a6bd528949a3a97f5c3e3eb3da86":{
      "scriptId":"u17"},
    "eac7b1fe64874c26a426a3ddbd1fde05":{
      "scriptId":"u18"},
    "7a9f7daeeec842df911b669fc2b17df2":{
      "scriptId":"u19"},
    "8a0a7a4c180e4380bad53c73fd85402c":{
      "scriptId":"u20"},
    "da8981e714cd4766b64823a7b9944231":{
      "scriptId":"u21"},
    "1e7f660e9b5f43569008a96dd88dab29":{
      "scriptId":"u22"},
    "2b8707db59b844afa3e2b532f84807a8":{
      "scriptId":"u23"},
    "d9adf131fd45477aabaf50d344c34fec":{
      "scriptId":"u24"},
    "a91a2dd731c44360b3d1a68cc0bc88af":{
      "scriptId":"u25"},
    "77cec34fee5b48538ad2b523e5a1a500":{
      "scriptId":"u26"},
    "b8e79b6bf1fb460c91df119fddd542c3":{
      "scriptId":"u27"},
    "e7ac7eac2d81459084377c70672b7948":{
      "scriptId":"u28"},
    "1c4cce5a237448ba8b9ebe401da0ff32":{
      "scriptId":"u29"},
    "f5d6e769ccf24a789f3a3e486e22b194":{
      "scriptId":"u30"},
    "fdbef536b8f14e84a1c8c3bba4660647":{
      "scriptId":"u31"},
    "5450e25f06f344a09f58a58708a7cfb0":{
      "scriptId":"u32"},
    "90aaa93120db4292b4f87b3518f996dd":{
      "scriptId":"u33"},
    "9cf343c522d445308338ef7009371eaf":{
      "scriptId":"u34"},
    "00bbcbcfcb4d43a1bd91e9a923c90a65":{
      "scriptId":"u35"},
    "6a0776f3997e456690f15f7b00190b52":{
      "scriptId":"u36"},
    "cb0a8d6bb4974a17a2d92991b986a96d":{
      "scriptId":"u37"},
    "d9c3be21dbb44d98bbd5de44f8132eb7":{
      "scriptId":"u38"},
    "3da88a6d098049dc9274b414c363cb2b":{
      "scriptId":"u39"},
    "6044a9a37b0f4f7dbd4e7da4b95717e8":{
      "scriptId":"u40"},
    "284a66abac6e437d9f263bd677a83c53":{
      "scriptId":"u41"},
    "df4727262ec94c219cbe9bec4cdfed33":{
      "scriptId":"u42"},
    "3a23a19b49e54a95902659c093f0d144":{
      "scriptId":"u43"},
    "d214016046cb4307a585239994e9f19b":{
      "scriptId":"u44"},
    "7150ed82bcda4b7ba1c4893b211d24ea":{
      "scriptId":"u45"},
    "f2cbf3375e5e46dd809dc366937d4773":{
      "scriptId":"u46"},
    "ae87790207fb4176ab71735f1c5b23ef":{
      "scriptId":"u47"},
    "2fffa3e0243b498d887306109097a138":{
      "scriptId":"u48"},
    "d5e54102ed9c4bf4a4ec848dcfe184fd":{
      "scriptId":"u49"},
    "26bec4f7d363413cafda22fbfea3d5ab":{
      "scriptId":"u50"},
    "6f8859c3c940493881786d3d2277b0b0":{
      "scriptId":"u51"},
    "212cec645ed1428d90575408e0a8315f":{
      "scriptId":"u52"},
    "a8e9bc90a8fe4c1faf58cdc57248b2e2":{
      "scriptId":"u53"},
    "5f6b75aaac534400887a081de655e389":{
      "scriptId":"u54"},
    "13a10379f2ae4a72aa6477112fc36e5f":{
      "scriptId":"u55"},
    "417f5117dfd84e1fbba12761d5417c31":{
      "scriptId":"u56"},
    "dbe35fd656a947fc8e7c8e79998c746b":{
      "scriptId":"u57"},
    "7e78d468a607456baffa653952c3161a":{
      "scriptId":"u58"},
    "551bed26de7949fcb0e7db735e7c21df":{
      "scriptId":"u59"},
    "c0c8953d2dec4579a6627c4ae2ca636c":{
      "scriptId":"u60"},
    "47d9254aa2a9402d8e85e6d59f4978d5":{
      "scriptId":"u61"},
    "a862b9ebcae2400682514159e2a0e83f":{
      "scriptId":"u62"},
    "b81e965363bf4ff68b5f43e419d2c54a":{
      "scriptId":"u63"},
    "7812e1452f8f485d9194b70c74fa1524":{
      "scriptId":"u64"},
    "f8c68a94f58e4b16a62f62f355d1dc29":{
      "scriptId":"u65"},
    "dc313486107e4242b1d06c3cf4b0b9b0":{
      "scriptId":"u66"},
    "2dd4838be29d4abc84ef585ebb9fd576":{
      "scriptId":"u67"},
    "e1cf7361d1774131a01bf043bdcb47de":{
      "scriptId":"u68"},
    "24e1055c635c44c0982fe563b9d7f72a":{
      "scriptId":"u69"},
    "36048b1a32354e83bbd1589f11fa4e23":{
      "scriptId":"u70"},
    "f37886f01a4349459cf2bbf93c6f9b20":{
      "scriptId":"u71"},
    "e5fa0c85f53647f6a3b60d8e9449c971":{
      "scriptId":"u72"},
    "887d67716e40446abd0e4f16bf046228":{
      "scriptId":"u73"},
    "85e451538a7b4d3baf9bbaa5d4ddb517":{
      "scriptId":"u74"},
    "7152c14fd7074acea37437c259789d30":{
      "scriptId":"u75"},
    "c78086b85fbb43569748c558fe5f6835":{
      "scriptId":"u76"},
    "2a14de516212424ca90443e851643131":{
      "scriptId":"u77"},
    "58bb87cb19924bc7858bb4423b1f24e2":{
      "scriptId":"u78"},
    "4dd9eb4c1ebe461597f10c7d87e237e5":{
      "scriptId":"u79"}}});