$axure.loadCurrentPage({
  "url":"店铺列表.html",
  "generationDate":new Date(1420531293242.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ffa976d5d804c0dbfa1aac057289419",
    "type":"Axure:Page",
    "name":"店铺列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3147fdb98e6d47ec86d9903f9a6178e2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"f4840d36736442cda9ba33777cc56b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"460070ff4fe8457fb889d62cf038820a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"bf23b53bb605498d8ffa3cf18f4da15b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":161,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66462685f53b4e76aac60fdc741a4134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":161,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u7.png"}},
{
          "id":"7aea25bf2d04487cafaf70fb7ebc57c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":131,
              "y":192},
            "size":{
              "width":10,
              "height":8},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6711d91859a84fb7b523f7e6710b93a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":131,
                  "y":192},
                "size":{
                  "width":10,
                  "height":8},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u97.png"}},
{
          "id":"72e69e37a7494cd48acaa8ad5ba38bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":192,
              "y":177},
            "size":{
              "width":161,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923c288c2c0e4c219a1dbf2d94646725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":192,
                  "y":177},
                "size":{
                  "width":161,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u7.png"}},
{
          "id":"b6d946e3b64b4ad6ae1ad23063888547",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":223},
            "size":{
              "width":342,
              "height":455}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bff73c7136484aafa4e2a0fc3391f0cd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"29e7566b8eb941d286c5614a0c5a457e",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":84},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"557a5ba856bc40879098e51b47dad617",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":8},
                    "size":{
                      "width":147,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f33955c04fd445efbbc3a344b6db0bfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":8},
                        "size":{
                          "width":147,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ec65207d61634fa1bac6fe8f510846c5",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":34},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2bf53ea3e8aa49aca18b27a05a0b4bf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":34},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"2c4213cdddff438c871a7f06d5f46d6c",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":133},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f18902c7dee4952943687e6af894b19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":133},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u19.png"}},
{
                  "id":"16240672bbb94db2b31ce6f50591bfc9",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":123,
                      "y":59},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5397be3630345a1b018545ed12dbc2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":123,
                          "y":59},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"56edcc1d09b8412d9ae5fe13345604d0",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":182},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"1e2951a981fb452b8badffbb7c0a12a3",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":106},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a702b9f6afd34393bd59274250a9e936",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":106},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7ea0629419094a84b245ff37c15597c3",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":157},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"957c8bb894e748f7a6393de48784a6a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":157},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7b8ce77664474657821ba14760987e17",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":281},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"317f0cad66184ca7a876ed6de378d43a",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":205},
                    "size":{
                      "width":138,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"254bc0d40a35475ba26185541e2e6ba1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":205},
                        "size":{
                          "width":138,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fda3ae5afc1348ccb0934bbdd7bd8409",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":230},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdb3ec549a244c8791cb8fe8a178fa01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":121,
                          "y":230},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"340163aa5b89432d99157b82f9e3e811",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":123,
                      "y":255},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c563e40d697049d68eaa2b87fc4739ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":123,
                          "y":255},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"919d9953a01e4a948c612b7f75dc54f0",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":379},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"4fb2dcaf8c2b4f098c94762fd8e4d0a9",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":303},
                    "size":{
                      "width":147,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c2c322cb4fa44e2ab3a5e81bd0c64a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":303},
                        "size":{
                          "width":147,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ea75ce76976f4ebb90623e6faf65bb86",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":123,
                      "y":328},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39cbb6fb8e7a4cbf8cc3a6a90ed2241e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":123,
                          "y":328},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"25ed6ee928994853b57b857dcf725df2",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":124,
                      "y":352},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2911dd681bfe44ca8d6b8e79b5689589",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":124,
                          "y":352},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65053629711e44448251165807d02686",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":28.4999980926514},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cdae5b937d7d490ab81a11e086d48ea0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":28.4999980926514},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"26890501da98401db60a7302ea148d68",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":125.500007629395},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79be486e6b284ae494e7800a2150bfab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":125.500007629395},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"b8ac707f22a2410c80fc220b462f666b",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":224.5},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1681cd36074947acadd2419294a82b04",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":224.5},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"e6626800eed44252ac83164f1789ae4e",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":277,
                      "y":322.5},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d897f38bf2c4f4ba53e6d2e7a35d794",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":277,
                          "y":322.5},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"dd150771e8e4413b844ce69a1ffbd850",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ece5af1520e843098793083508cdae4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":0},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u50.png"}},
{
                  "id":"8a493aab79af488ba49ac2f440d9b296",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":98},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3bd01a328e841309e71c6833b492d31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":98},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u52.jpg"}},
{
                  "id":"5dadd9740f3c4f8e8eef28ef4295809b",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":197},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"254ffd3f74464c18a0bab23d2da591dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":197},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u54.jpg"}},
{
                  "id":"60df0019d8d64298b4c3483ea09a9f0f",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":295},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbfdff69701345619bf1052efcc8770b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":295},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u56.jpg"}},
{
                  "id":"5cc0286ffce742e78d2fde16fd2bc626",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":478},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"821b5e506c484a5c84eca39116bcbbfd",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":402},
                    "size":{
                      "width":147,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98e9fc5759804e0a8fef3ee493fdf51b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":402},
                        "size":{
                          "width":147,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"316071befb754b0f81fdeec232d381d8",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":427},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ae3aed58e7d491994ba6f4957a39865",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":427},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"f89f40e8d0a24dd0a7108781318e80e4",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":125,
                      "y":451},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"78a8e0ba71ab4d7aba347a339cfc0864",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":125,
                          "y":451},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"001c70b2b6524f89857f8e5da6a59591",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":278,
                      "y":421.5},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d28b47c47f2441c39ff7d1d39c7c98a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":278,
                          "y":421.5},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"5a652d36b395494ca1b50407c0b800bf",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":394},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02bb2017efdc4a06bebddc88e05930de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":394},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u56.jpg"}},
{
                  "id":"f82ba041e6a84b2796ea866afe04a2c3",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":394},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1304c9f4a9db40f59eae41af9b3e4ce4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":394},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u54.jpg"}},
{
                  "id":"33b16392e4314eacb86d633c837488d0",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":577},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"f11cb18c471443709e9e8d0e59caeb1f",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":501},
                    "size":{
                      "width":147,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac494b736e8741c5827e74a09baf9bf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":501},
                        "size":{
                          "width":147,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9338418dc4e846e7a26c6f121b6a7649",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":526},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf59907a9c0b4f1eaa804cf43dcd7a20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":526},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"41b690ee39b946ada9e8eb12b6e20cd7",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":125,
                      "y":550},
                    "size":{
                      "width":58,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6351ef6f5196428d924b006f7089097a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":125,
                          "y":550},
                        "size":{
                          "width":58,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a7262fc0cfd482193a63f28a04073bc",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":278,
                      "y":520.5},
                    "size":{
                      "width":27,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"108bba9844fe412ca598468ed88426c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":278,
                          "y":520.5},
                        "size":{
                          "width":27,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 cg",
                              "objectsToFades":[{
                                  "objectPath":["e06ab56e58364979a75031e28da2e623"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/招聘详情/u20.png"}},
{
                  "id":"89152b174a7043bab3a6d2c2b666555b",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":493},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af80e2436a364f6ea76a8e13abd2dc3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":493},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u56.jpg"}},
{
                  "id":"941c1ac9837b409c867d8b0366997af5",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":0},
                    "size":{
                      "width":271,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"1907623fa9834686b02ce32ce72e57b1",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":94},
                    "size":{
                      "width":271,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"07212b20131944c4ad80e20927d81cd7",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":193},
                    "size":{
                      "width":271,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"87080ec4ea1b4904b149b9e83afb7159",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":291},
                    "size":{
                      "width":273,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"a05153496ca94045b7a3c77f027849d9",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":390},
                    "size":{
                      "width":273,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"54eb6d627f67438a8f8fa295a244ec62",
                  "label":"",
                  "parentDynamicPanel":"b6d946e3b64b4ad6ae1ad23063888547",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":489},
                    "size":{
                      "width":273,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品列表",
                              "target":{
                                "targetType":"page",
                                "url":"商品列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"080e0825281442f693ee1def3e37dcc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c2a00aa765240639085bd0c7975b3d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商铺",
                      "target":{
                        "targetType":"page",
                        "url":"商铺.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"e06ab56e58364979a75031e28da2e623",
          "label":"cg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":117.5,
              "y":390},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"dcbd50118cd74b77b885679607248aa8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9a7c237ed6ef466995523f3eba3a42f1",
                  "label":"cg",
                  "parentDynamicPanel":"e06ab56e58364979a75031e28da2e623",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":150,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"714015d9e4d34778ae2f101623b2cfd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e06ab56e58364979a75031e28da2e623",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":150,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/cg_u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"3918695f368747b5b2900c67bedfb429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":188},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5857f1ef20c04666a1449c873d5f95a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":188},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u101.png"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "3147fdb98e6d47ec86d9903f9a6178e2":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "f4840d36736442cda9ba33777cc56b2d":{
      "scriptId":"u5"},
    "460070ff4fe8457fb889d62cf038820a":{
      "scriptId":"u6"},
    "bf23b53bb605498d8ffa3cf18f4da15b":{
      "scriptId":"u7"},
    "66462685f53b4e76aac60fdc741a4134":{
      "scriptId":"u8"},
    "7aea25bf2d04487cafaf70fb7ebc57c7":{
      "scriptId":"u9"},
    "6711d91859a84fb7b523f7e6710b93a6":{
      "scriptId":"u10"},
    "72e69e37a7494cd48acaa8ad5ba38bb3":{
      "scriptId":"u11"},
    "923c288c2c0e4c219a1dbf2d94646725":{
      "scriptId":"u12"},
    "b6d946e3b64b4ad6ae1ad23063888547":{
      "scriptId":"u13"},
    "29e7566b8eb941d286c5614a0c5a457e":{
      "scriptId":"u14"},
    "557a5ba856bc40879098e51b47dad617":{
      "scriptId":"u15"},
    "f33955c04fd445efbbc3a344b6db0bfa":{
      "scriptId":"u16"},
    "ec65207d61634fa1bac6fe8f510846c5":{
      "scriptId":"u17"},
    "2bf53ea3e8aa49aca18b27a05a0b4bf4":{
      "scriptId":"u18"},
    "2c4213cdddff438c871a7f06d5f46d6c":{
      "scriptId":"u19"},
    "7f18902c7dee4952943687e6af894b19":{
      "scriptId":"u20"},
    "16240672bbb94db2b31ce6f50591bfc9":{
      "scriptId":"u21"},
    "b5397be3630345a1b018545ed12dbc2a":{
      "scriptId":"u22"},
    "56edcc1d09b8412d9ae5fe13345604d0":{
      "scriptId":"u23"},
    "1e2951a981fb452b8badffbb7c0a12a3":{
      "scriptId":"u24"},
    "a702b9f6afd34393bd59274250a9e936":{
      "scriptId":"u25"},
    "7ea0629419094a84b245ff37c15597c3":{
      "scriptId":"u26"},
    "957c8bb894e748f7a6393de48784a6a5":{
      "scriptId":"u27"},
    "7b8ce77664474657821ba14760987e17":{
      "scriptId":"u28"},
    "317f0cad66184ca7a876ed6de378d43a":{
      "scriptId":"u29"},
    "254bc0d40a35475ba26185541e2e6ba1":{
      "scriptId":"u30"},
    "fda3ae5afc1348ccb0934bbdd7bd8409":{
      "scriptId":"u31"},
    "bdb3ec549a244c8791cb8fe8a178fa01":{
      "scriptId":"u32"},
    "340163aa5b89432d99157b82f9e3e811":{
      "scriptId":"u33"},
    "c563e40d697049d68eaa2b87fc4739ed":{
      "scriptId":"u34"},
    "919d9953a01e4a948c612b7f75dc54f0":{
      "scriptId":"u35"},
    "4fb2dcaf8c2b4f098c94762fd8e4d0a9":{
      "scriptId":"u36"},
    "5c2c322cb4fa44e2ab3a5e81bd0c64a1":{
      "scriptId":"u37"},
    "ea75ce76976f4ebb90623e6faf65bb86":{
      "scriptId":"u38"},
    "39cbb6fb8e7a4cbf8cc3a6a90ed2241e":{
      "scriptId":"u39"},
    "25ed6ee928994853b57b857dcf725df2":{
      "scriptId":"u40"},
    "2911dd681bfe44ca8d6b8e79b5689589":{
      "scriptId":"u41"},
    "65053629711e44448251165807d02686":{
      "scriptId":"u42"},
    "cdae5b937d7d490ab81a11e086d48ea0":{
      "scriptId":"u43"},
    "26890501da98401db60a7302ea148d68":{
      "scriptId":"u44"},
    "79be486e6b284ae494e7800a2150bfab":{
      "scriptId":"u45"},
    "b8ac707f22a2410c80fc220b462f666b":{
      "scriptId":"u46"},
    "1681cd36074947acadd2419294a82b04":{
      "scriptId":"u47"},
    "e6626800eed44252ac83164f1789ae4e":{
      "scriptId":"u48"},
    "0d897f38bf2c4f4ba53e6d2e7a35d794":{
      "scriptId":"u49"},
    "dd150771e8e4413b844ce69a1ffbd850":{
      "scriptId":"u50"},
    "ece5af1520e843098793083508cdae4e":{
      "scriptId":"u51"},
    "8a493aab79af488ba49ac2f440d9b296":{
      "scriptId":"u52"},
    "e3bd01a328e841309e71c6833b492d31":{
      "scriptId":"u53"},
    "5dadd9740f3c4f8e8eef28ef4295809b":{
      "scriptId":"u54"},
    "254ffd3f74464c18a0bab23d2da591dc":{
      "scriptId":"u55"},
    "60df0019d8d64298b4c3483ea09a9f0f":{
      "scriptId":"u56"},
    "fbfdff69701345619bf1052efcc8770b":{
      "scriptId":"u57"},
    "5cc0286ffce742e78d2fde16fd2bc626":{
      "scriptId":"u58"},
    "821b5e506c484a5c84eca39116bcbbfd":{
      "scriptId":"u59"},
    "98e9fc5759804e0a8fef3ee493fdf51b":{
      "scriptId":"u60"},
    "316071befb754b0f81fdeec232d381d8":{
      "scriptId":"u61"},
    "8ae3aed58e7d491994ba6f4957a39865":{
      "scriptId":"u62"},
    "f89f40e8d0a24dd0a7108781318e80e4":{
      "scriptId":"u63"},
    "78a8e0ba71ab4d7aba347a339cfc0864":{
      "scriptId":"u64"},
    "001c70b2b6524f89857f8e5da6a59591":{
      "scriptId":"u65"},
    "d28b47c47f2441c39ff7d1d39c7c98a0":{
      "scriptId":"u66"},
    "5a652d36b395494ca1b50407c0b800bf":{
      "scriptId":"u67"},
    "02bb2017efdc4a06bebddc88e05930de":{
      "scriptId":"u68"},
    "f82ba041e6a84b2796ea866afe04a2c3":{
      "scriptId":"u69"},
    "1304c9f4a9db40f59eae41af9b3e4ce4":{
      "scriptId":"u70"},
    "33b16392e4314eacb86d633c837488d0":{
      "scriptId":"u71"},
    "f11cb18c471443709e9e8d0e59caeb1f":{
      "scriptId":"u72"},
    "ac494b736e8741c5827e74a09baf9bf4":{
      "scriptId":"u73"},
    "9338418dc4e846e7a26c6f121b6a7649":{
      "scriptId":"u74"},
    "bf59907a9c0b4f1eaa804cf43dcd7a20":{
      "scriptId":"u75"},
    "41b690ee39b946ada9e8eb12b6e20cd7":{
      "scriptId":"u76"},
    "6351ef6f5196428d924b006f7089097a":{
      "scriptId":"u77"},
    "5a7262fc0cfd482193a63f28a04073bc":{
      "scriptId":"u78"},
    "108bba9844fe412ca598468ed88426c0":{
      "scriptId":"u79"},
    "89152b174a7043bab3a6d2c2b666555b":{
      "scriptId":"u80"},
    "af80e2436a364f6ea76a8e13abd2dc3a":{
      "scriptId":"u81"},
    "941c1ac9837b409c867d8b0366997af5":{
      "scriptId":"u82"},
    "1907623fa9834686b02ce32ce72e57b1":{
      "scriptId":"u83"},
    "07212b20131944c4ad80e20927d81cd7":{
      "scriptId":"u84"},
    "87080ec4ea1b4904b149b9e83afb7159":{
      "scriptId":"u85"},
    "a05153496ca94045b7a3c77f027849d9":{
      "scriptId":"u86"},
    "54eb6d627f67438a8f8fa295a244ec62":{
      "scriptId":"u87"},
    "080e0825281442f693ee1def3e37dcc7":{
      "scriptId":"u88"},
    "1c2a00aa765240639085bd0c7975b3d4":{
      "scriptId":"u89"},
    "e06ab56e58364979a75031e28da2e623":{
      "scriptId":"u90"},
    "9a7c237ed6ef466995523f3eba3a42f1":{
      "scriptId":"u91"},
    "714015d9e4d34778ae2f101623b2cfd8":{
      "scriptId":"u92"},
    "3918695f368747b5b2900c67bedfb429":{
      "scriptId":"u93"},
    "5857f1ef20c04666a1449c873d5f95a7":{
      "scriptId":"u94"}}});