$axure.loadCurrentPage({
  "url":"设置新密码.html",
  "generationDate":new Date(1420531287225.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"939fbe5dd2d341cd9815cceb5af27aa4",
    "type":"Axure:Page",
    "name":"设置新密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7cc0b4a716fd467f9711f4c01d91609b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"9369d78e484842b6b034f5e4a4fea13b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98f7c6dad2c9483d8108057bb115dce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"3ad949e022f848c9824a65701f0c4941",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcac714277d84fc0991ead88173785ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 找回密码",
                      "target":{
                        "targetType":"page",
                        "url":"找回密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"0290dc6a18cf4b2fb5e2f3da45fd6892",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":470},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0a9a4c22f5411abedeb395c0f01bd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":470},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u26.png"}},
{
          "id":"5821f2c0595d4e6f833d10c41f3582dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":44,
              "y":394},
            "size":{
              "width":296,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3152d4d37ca14d0da1ed2bc8255bf478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":44,
                  "y":394},
                "size":{
                  "width":296,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码修改成功",
                      "target":{
                        "targetType":"page",
                        "url":"密码修改成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u36.png"}},
{
          "id":"6ebafb874ae441a082110c58c6de967b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":219},
            "size":{
              "width":298,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c50716b4bbcf414999fbdcd20df2706d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":219},
                "size":{
                  "width":298,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置新密码/u13.png"}},
{
          "id":"913d950524f44660878be7c62be72e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":45,
              "y":193},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2134e3e1ff414981a7dcc2cedba594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":193},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6298bd743364daba678c990694941e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":311},
            "size":{
              "width":298,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f3109fdf0644fa9c4552a2f851ca62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":311},
                "size":{
                  "width":298,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置新密码/u13.png"}},
{
          "id":"a7901f0659494ace8bb9f000448fd81a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":45,
              "y":285},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"369380813e0d438dbce218b38e60b19f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":285},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "7cc0b4a716fd467f9711f4c01d91609b":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "9369d78e484842b6b034f5e4a4fea13b":{
      "scriptId":"u5"},
    "98f7c6dad2c9483d8108057bb115dce4":{
      "scriptId":"u6"},
    "3ad949e022f848c9824a65701f0c4941":{
      "scriptId":"u7"},
    "dcac714277d84fc0991ead88173785ef":{
      "scriptId":"u8"},
    "0290dc6a18cf4b2fb5e2f3da45fd6892":{
      "scriptId":"u9"},
    "aa0a9a4c22f5411abedeb395c0f01bd4":{
      "scriptId":"u10"},
    "5821f2c0595d4e6f833d10c41f3582dd":{
      "scriptId":"u11"},
    "3152d4d37ca14d0da1ed2bc8255bf478":{
      "scriptId":"u12"},
    "6ebafb874ae441a082110c58c6de967b":{
      "scriptId":"u13"},
    "c50716b4bbcf414999fbdcd20df2706d":{
      "scriptId":"u14"},
    "913d950524f44660878be7c62be72e46":{
      "scriptId":"u15"},
    "2f2134e3e1ff414981a7dcc2cedba594":{
      "scriptId":"u16"},
    "f6298bd743364daba678c990694941e2":{
      "scriptId":"u17"},
    "60f3109fdf0644fa9c4552a2f851ca62":{
      "scriptId":"u18"},
    "a7901f0659494ace8bb9f000448fd81a":{
      "scriptId":"u19"},
    "369380813e0d438dbce218b38e60b19f":{
      "scriptId":"u20"}}});