$axure.loadCurrentPage({
  "url":"购物车-团购.html",
  "generationDate":new Date(1420531295124.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3f6639f09833475eaf3d885da8029b34",
    "type":"Axure:Page",
    "name":"购物车-团购",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f49dc274f87465da2f695e12b9baccb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"a642293fc8a3470c968001cac0e45e73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7875b98a06747bd9cc6406f30caadd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"56c1e4250f9545428922cb755da6775b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbf4ed3129946eabc0fa019235d7032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 团购详情",
                      "target":{
                        "targetType":"page",
                        "url":"团购详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"2e20ec9640ac477d8fe2dbd7e9dbf575",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bb3682b6393481da45e18cc1c56c7b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u9.png"}},
{
          "id":"a03ef5a59781497aac0eb8e7018d0330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":191},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f32842488b841e1915daa1a006359e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":191},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"82f035e7781647a0ae3a342808685f70",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":216},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"40d473ceaad746428f7dba74c749618b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":77,
              "y":192},
            "size":{
              "width":163,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d299ec75b9064a73be914f6968fdddc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":192},
                "size":{
                  "width":163,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"256951e5cfe344759aa54d54a02fe5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":252},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbd0048255f4c76a647aa67a452a5a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":252},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"089a87bb6cee4758befa28b395dc3a0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":236},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"326dbf8403724599969757a08efd6702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":236},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a89fedc19aff4ec09ce71c2cb5af87c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":293,
              "y":236},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7deed047794d1a9489bcff7eb800a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":236},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aaef024ca184b928c329f3fffb70b6a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":298},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"0a539dedc822490aa6568fed402341db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":313},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6db53f88fc264c1e9d2d5f0d9d57900e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":313},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef9cfe53f59f4cb0a942042aa1ab702e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":246,
              "y":313},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9597b3b90cc417c9b61c7391e6c4c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":246,
                  "y":313},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9179775ceeeb417f8b3cea6f300fbf72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":621},
            "size":{
              "width":321,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44217a7f22c34e25884ff28e64f6b705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":621},
                "size":{
                  "width":321,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u31.png"}},
{
          "id":"8a85fce7150443a2bcc5152c280f26c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":644},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c2f0f40ca3c48d4839bf43016a14394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":644},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"b8f5f9e39e3943ef82d1882d110065f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":133,
              "y":645},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23e53e7e8f8a479e8123f3925de6542c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":133,
                  "y":645},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe4e2d4140834290843e4c5eb1cc1137",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":249,
              "y":631},
            "size":{
              "width":95,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8830359a8f84c55814a951b7fdfa36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":249,
                  "y":631},
                "size":{
                  "width":95,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单确认-团购",
                      "target":{
                        "targetType":"page",
                        "url":"订单确认-团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购物车/u37.png"}},
{
          "id":"f56c673701564000b42905f0294f03b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":351},
            "size":{
              "width":321,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f29989f426140f8ade397b17155705c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":351},
                "size":{
                  "width":321,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-团购/u35.png"}},
{
          "id":"c74106905f5848ceaa92bd48cd19b9f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":365},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842c98ee158a42479f9b0ed2d4ea03e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":365},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"1afbd60d74364824b22f16bf6722e2e2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":390},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"27f6d0afa069460eb158a1f747993580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":77,
              "y":366},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68e07190e6cb4d828e85ba0c93d3b640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":366},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a4840590f7b452dbd505935b4320858",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":426},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fbc71029ace41f4a71beb316b9d70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":426},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"844034a539064a9fb5dbeddf9e1ed0d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":409},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13ea6d4a789c4aaf9bd1f3dd945a8ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":409},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u18.png"}},
{
          "id":"a8ede2f9f8af4f3fa20d3003c72ac9b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":410},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55046d3bf6184c4b8c243a896b893f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":410},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a960e773725048ab9f03461274dee7f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":286,
              "y":410},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de40c26ad4c44ce881d0fcbf50dfa691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":410},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dec0b7cb37c41bd9e51b3ac6982eb00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":141,
              "y":432},
            "size":{
              "width":128,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"283d0544327440409bfb397a5ffd58f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":432},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f48dab7ce9c2474e9671454a7e9fdb0e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":490},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"b30954b3c7464058aaf21e5691812a97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":506},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b52b1dcb02f4c5294280c9aabc21193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":506},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"446f85b3e40145c18c895e8005a144d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":246,
              "y":506},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e3fea4f8234402bea12062f5eb075f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":246,
                  "y":506},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a7956a573e946f2897f3787edaa86f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":191},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d7fef9c8fa54c63a93ce34e178b019a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":191},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"99bb0b7670e1489f9cc9934f55ee3583",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":252},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83fa866067b9478d87a3ff41c8d06aa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":252},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"599f58fd1140464a8451fa4bdb4c8080",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0D7AFF,
              "opacity":1},
            "location":{
              "x":306,
              "y":147},
            "size":{
              "width":32,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16fa98bae2f4e90b20a2ff5769bef0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0D7AFF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":147},
                "size":{
                  "width":32,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车编辑",
                      "target":{
                        "targetType":"page",
                        "url":"购物车编辑_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58d56b98dc9545f495fe0cab1c09baf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":262},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52786df799b3481dac8c24957f214b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":262},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购详情/u27.png"}},
{
          "id":"7b94bcf1bb9f401b82381b3129e7739a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":165,
              "y":269},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df17614e3ea4954a227de832e5e916b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":269},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64551933088b4155a7f98d2a3fff9a98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":235},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f054b084219748d8a6b79fc99e75062d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":235},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-团购/u67.png"}},
{
          "id":"04b1ba978dde4d969adb840c859e2b01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":464},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd3ea55aa2cd47e2a8b5bd27f4038a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":464},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购详情/u27.png"}},
{
          "id":"06cc87f9bb3049c78943f755ba439f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":165,
              "y":471},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6891119ce89f41c3929ea3b9cc60b360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":471},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23cd5d089ac14db1b23d5bda35b046f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":78,
              "y":645},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a17745460543e8af2433deb0f2d107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":78,
                  "y":645},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"503836b15c164c97a113c247e57fa7f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":321,
              "y":267},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0329e35cd1db4103a786898cbdf577cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":267},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cfaf7f0c3ef4e43be45a4b9d1bfda62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":322,
              "y":442},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9a7d719f2b4a48b433557f7ec04c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":322,
                  "y":442},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "8f49dc274f87465da2f695e12b9baccb":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "a642293fc8a3470c968001cac0e45e73":{
      "scriptId":"u5"},
    "f7875b98a06747bd9cc6406f30caadd2":{
      "scriptId":"u6"},
    "56c1e4250f9545428922cb755da6775b":{
      "scriptId":"u7"},
    "5dbf4ed3129946eabc0fa019235d7032":{
      "scriptId":"u8"},
    "2e20ec9640ac477d8fe2dbd7e9dbf575":{
      "scriptId":"u9"},
    "9bb3682b6393481da45e18cc1c56c7b3":{
      "scriptId":"u10"},
    "a03ef5a59781497aac0eb8e7018d0330":{
      "scriptId":"u11"},
    "0f32842488b841e1915daa1a006359e1":{
      "scriptId":"u12"},
    "82f035e7781647a0ae3a342808685f70":{
      "scriptId":"u13"},
    "40d473ceaad746428f7dba74c749618b":{
      "scriptId":"u14"},
    "d299ec75b9064a73be914f6968fdddc6":{
      "scriptId":"u15"},
    "256951e5cfe344759aa54d54a02fe5b1":{
      "scriptId":"u16"},
    "1cbd0048255f4c76a647aa67a452a5a2":{
      "scriptId":"u17"},
    "089a87bb6cee4758befa28b395dc3a0e":{
      "scriptId":"u18"},
    "326dbf8403724599969757a08efd6702":{
      "scriptId":"u19"},
    "a89fedc19aff4ec09ce71c2cb5af87c6":{
      "scriptId":"u20"},
    "7b7deed047794d1a9489bcff7eb800a9":{
      "scriptId":"u21"},
    "4aaef024ca184b928c329f3fffb70b6a":{
      "scriptId":"u22"},
    "0a539dedc822490aa6568fed402341db":{
      "scriptId":"u23"},
    "6db53f88fc264c1e9d2d5f0d9d57900e":{
      "scriptId":"u24"},
    "ef9cfe53f59f4cb0a942042aa1ab702e":{
      "scriptId":"u25"},
    "c9597b3b90cc417c9b61c7391e6c4c55":{
      "scriptId":"u26"},
    "9179775ceeeb417f8b3cea6f300fbf72":{
      "scriptId":"u27"},
    "44217a7f22c34e25884ff28e64f6b705":{
      "scriptId":"u28"},
    "8a85fce7150443a2bcc5152c280f26c7":{
      "scriptId":"u29"},
    "6c2f0f40ca3c48d4839bf43016a14394":{
      "scriptId":"u30"},
    "b8f5f9e39e3943ef82d1882d110065f4":{
      "scriptId":"u31"},
    "23e53e7e8f8a479e8123f3925de6542c":{
      "scriptId":"u32"},
    "fe4e2d4140834290843e4c5eb1cc1137":{
      "scriptId":"u33"},
    "c8830359a8f84c55814a951b7fdfa36a":{
      "scriptId":"u34"},
    "f56c673701564000b42905f0294f03b5":{
      "scriptId":"u35"},
    "2f29989f426140f8ade397b17155705c":{
      "scriptId":"u36"},
    "c74106905f5848ceaa92bd48cd19b9f5":{
      "scriptId":"u37"},
    "842c98ee158a42479f9b0ed2d4ea03e6":{
      "scriptId":"u38"},
    "1afbd60d74364824b22f16bf6722e2e2":{
      "scriptId":"u39"},
    "27f6d0afa069460eb158a1f747993580":{
      "scriptId":"u40"},
    "68e07190e6cb4d828e85ba0c93d3b640":{
      "scriptId":"u41"},
    "4a4840590f7b452dbd505935b4320858":{
      "scriptId":"u42"},
    "7fbc71029ace41f4a71beb316b9d70da":{
      "scriptId":"u43"},
    "844034a539064a9fb5dbeddf9e1ed0d4":{
      "scriptId":"u44"},
    "13ea6d4a789c4aaf9bd1f3dd945a8ec0":{
      "scriptId":"u45"},
    "a8ede2f9f8af4f3fa20d3003c72ac9b1":{
      "scriptId":"u46"},
    "55046d3bf6184c4b8c243a896b893f09":{
      "scriptId":"u47"},
    "a960e773725048ab9f03461274dee7f4":{
      "scriptId":"u48"},
    "de40c26ad4c44ce881d0fcbf50dfa691":{
      "scriptId":"u49"},
    "3dec0b7cb37c41bd9e51b3ac6982eb00":{
      "scriptId":"u50"},
    "283d0544327440409bfb397a5ffd58f6":{
      "scriptId":"u51"},
    "f48dab7ce9c2474e9671454a7e9fdb0e":{
      "scriptId":"u52"},
    "b30954b3c7464058aaf21e5691812a97":{
      "scriptId":"u53"},
    "1b52b1dcb02f4c5294280c9aabc21193":{
      "scriptId":"u54"},
    "446f85b3e40145c18c895e8005a144d6":{
      "scriptId":"u55"},
    "b0e3fea4f8234402bea12062f5eb075f":{
      "scriptId":"u56"},
    "2a7956a573e946f2897f3787edaa86f8":{
      "scriptId":"u57"},
    "2d7fef9c8fa54c63a93ce34e178b019a":{
      "scriptId":"u58"},
    "99bb0b7670e1489f9cc9934f55ee3583":{
      "scriptId":"u59"},
    "83fa866067b9478d87a3ff41c8d06aa4":{
      "scriptId":"u60"},
    "599f58fd1140464a8451fa4bdb4c8080":{
      "scriptId":"u61"},
    "d16fa98bae2f4e90b20a2ff5769bef0b":{
      "scriptId":"u62"},
    "58d56b98dc9545f495fe0cab1c09baf4":{
      "scriptId":"u63"},
    "52786df799b3481dac8c24957f214b5b":{
      "scriptId":"u64"},
    "7b94bcf1bb9f401b82381b3129e7739a":{
      "scriptId":"u65"},
    "2df17614e3ea4954a227de832e5e916b":{
      "scriptId":"u66"},
    "64551933088b4155a7f98d2a3fff9a98":{
      "scriptId":"u67"},
    "f054b084219748d8a6b79fc99e75062d":{
      "scriptId":"u68"},
    "04b1ba978dde4d969adb840c859e2b01":{
      "scriptId":"u69"},
    "fd3ea55aa2cd47e2a8b5bd27f4038a09":{
      "scriptId":"u70"},
    "06cc87f9bb3049c78943f755ba439f9f":{
      "scriptId":"u71"},
    "6891119ce89f41c3929ea3b9cc60b360":{
      "scriptId":"u72"},
    "23cd5d089ac14db1b23d5bda35b046f8":{
      "scriptId":"u73"},
    "f1a17745460543e8af2433deb0f2d107":{
      "scriptId":"u74"},
    "503836b15c164c97a113c247e57fa7f4":{
      "scriptId":"u75"},
    "0329e35cd1db4103a786898cbdf577cf":{
      "scriptId":"u76"},
    "6cfaf7f0c3ef4e43be45a4b9d1bfda62":{
      "scriptId":"u77"},
    "3f9a7d719f2b4a48b433557f7ec04c17":{
      "scriptId":"u78"}}});