$axure.loadCurrentPage({
  "url":"交友列表.html",
  "generationDate":new Date(1420531292299.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc09d498410748ccae1a458e09feee14",
    "type":"Axure:Page",
    "name":"交友列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c2a0b085325a407abcff977530ee6b77",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"36155ca0d8c74be9ac74ca24590a2b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1920fd90b35a4763b71d169e7daf0b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"b867e7d756a94ec887475bee90df9bc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80cd93f614bb42c6941e1a5023869436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交友",
                      "target":{
                        "targetType":"page",
                        "url":"交友.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"dea96f926a624792a2c2bd58db299d0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":508},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f53391db4a43d7904d131f07759c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":508},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻详情/u9.png"}},
{
          "id":"ff4a25c23d2f48f6a1a9784ff7a7928b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":213},
            "size":{
              "width":342,
              "height":414}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d98fd6deec224c1b83c5c431e411e694",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a41ca3795d024e42ad6407940752fd94",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"4decd258d13c4f19b9a0397bc7faa0bf",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":15},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c7aaf377b1d4a80a9b9b03473058a85",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":15},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8acf3b683f0a4069bdc3adbbab5d30b8",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":44},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bab7ded57b842bd917cfce5d4a5f8d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":44},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08fe0dce9bab4868a905e999a36e6880",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":76},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b6a4cbf609e423d8671afc075f8ccbc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":76},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9ce028efd182446d8a3054ce76898fc3",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":72},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff442e1704c4418e9dddf817e4223e9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":72},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"513a9460b06c45e083ec969db65208d9",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":10},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25834727a20c4620a5a9ca8d6b85335a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":10},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u21.png"}},
{
                  "id":"a597857be3524220a0ebb90a83d24994",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":44},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f70cedad81654a49acf155f69bf6dbde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":44},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bbf526c949ac45c2931628908908347f",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"5a6d781894ef46309c60c21b56c72eca",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":113},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"912fd21ea9b647d5a3ff9d9058dcd028",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":113},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c4eeeb48dfaa4657a0a9cd66b20ccfdb",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":142},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bad848092bba40d3ac9e0bf5d7830fb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":142},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aca83071cd064455afa8e1866532f593",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":174},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cad36197a8b4440b81174548c9e69380",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":174},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03b7e9cfa97e4d2ebb9d78707bb11552",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":170},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a96f7fd4e894dda99b9affb5c0cd5ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":170},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c5b21798fec742f8b53a906b37819a35",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":142},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e68911fca9e7402590e4ee816f9e46dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":142},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"97adfa3ebae34efbafb4b82f91a7cd42",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":291},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"7e38d466efe84c03b3aa6fd43541c916",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":212},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54ba8768faa6415b9ebc7b1382ac74c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":212},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"685a20ad608c4a6cb33c19c650c8504f",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":241},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3768c61b2b4c41a78d46119d5d134b63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":241},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"21d0f9274cea4e328257954eddfe41fc",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":273},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f15de7bc0f64231a8d950828a776159",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":273},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"24e722e2d2f84032bf4e7a12749c1409",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":269},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"834fefd0c84a45b680e41ead88502cde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":269},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f62580b302bc42fd9f9ad5bde0407e3d",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":241},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d942d93a203b4f0ebf921eae966dc8d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":241},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f7668b896f314917b51089418269dff0",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":389},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"88c17e1a99354c97bf54fa40e1ce6403",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":310},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"525eb030391c4cc2b45961ea0532c4aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":310},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"acfc344cb32946dd87b3b006d2a2784e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":339},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efe3f34927634fd69a6e5a79b23b4375",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":339},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b6eeb3a9a24940c69f9a540a98607c4e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":371},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f36e143f4cd460483c0ea9763da3f10",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":371},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0cad46e864464e70a2fdfb9d049a2c3a",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":367},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed832c1b17f94fb6b9a18a3ea6e400e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":367},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"38d2f39c5c5d4201ac362e3b364928bb",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":339},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d58ccdd7fd641f89ae298da3ada8af2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":339},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f01bf2a4b0eb4e15940ececd478931c2",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":487},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"7ac9fbef9810438da980f1b1aa00c702",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":408},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f18ed0d68ae14394963fd59e6c842351",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":408},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e12ebc5449c4826ba8b47b135778eeb",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":437},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b06d57421f54bd2a6dd4fbae2443c34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":437},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c466741865a45e5bc85b8083f4ffa8c",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":469},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"284ce50583ae4b9bb7ce5d772b34b903",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":469},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"43c33050b8c54406a35313e879b893e9",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":465},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21548246a60f451aa66de2b9d9a8ce9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":465},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dce41d6cb2994009a7605447b3ebf318",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":437},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1f82eb194b149838764550c05320653",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":437},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a623f4f99d9d486b92397841da3957f9",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":586},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"cba05b317b9442e7ad9568f7a988ade0",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":507},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af4713fbd459412286f0a2b01e49f8c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":507},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"894cb57fafb74202851c713d7cb6554e",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":536},
                    "size":{
                      "width":190,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea5cb52764724dc8b122a53064d72f9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":536},
                        "size":{
                          "width":190,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0bbff5368fe24d8eaf1763c22599fdba",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":568},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66255d1c35ca49109abcaa560a360d48",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":568},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1d99cb0863345d4a7a954d4922ba055",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":564},
                    "size":{
                      "width":68,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35dc8615468b4622b6c7ae6815abd313",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":564},
                        "size":{
                          "width":68,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"991ef8b7d47e457bb508dd9b334d3e09",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":536},
                    "size":{
                      "width":48,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00815f921aff490aa02deeaebc04946c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":193,
                          "y":536},
                        "size":{
                          "width":48,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"df8031078d294eb6b15e9d2c66234c96",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":2},
                    "size":{
                      "width":322,
                      "height":94}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 交友详情",
                              "target":{
                                "targetType":"page",
                                "url":"交友详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"42f7c19e130d416eaf4a9be0e7d470c4",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":108},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac1dc9fb2c084551a11e6ba6885a3f63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":108},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u81.png"}},
{
                  "id":"a1913323d3ae4041b977385a91b650df",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":207},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77e7b318674f44798b080a16ed5ce65e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":207},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u83.png"}},
{
                  "id":"855ebfd96d924236b74669d7938af0a8",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":305},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d197c2f6c03418f92952e9011882b50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":305},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u85.png"}},
{
                  "id":"9624aecf1890432288e0ab3b599231da",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":403},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd942f2b13f54cb1b17e4a7c46a143b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":403},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u87.png"}},
{
                  "id":"6a66187bff2a4e91b42c705ea1e03c50",
                  "label":"",
                  "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":502},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"066a8e06bf2744d9b470b96cf8fadb28",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff4a25c23d2f48f6a1a9784ff7a7928b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":502},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友列表/u89.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e137370cbf5644c9ac501951eb0b4bab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1483e0a19f864965afa4f878561a85f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信息发布",
                      "target":{
                        "targetType":"page",
                        "url":"信息发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/房产列表/u129.png"}},
{
          "id":"9862dc8260254855b6a6eb7810c45c78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":637},
            "size":{
              "width":321,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5526cff04efb443cb217ac2cdfe751bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":637},
                "size":{
                  "width":321,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u85.png"}},
{
          "id":"f8620d2509ac47fb8c36200dd8dbd841",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":647},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表/u87_line.png"}},
{
          "id":"575abc47bed54fe8b1ea03cc1367cb69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":646},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7ac32bccd341219155ae18e639d66c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":646},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u88.png"}},
{
          "id":"dfc3c81861bc4613ae8d4cf7b1ed35a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF662C,
              "opacity":1},
            "location":{
              "x":115,
              "y":652},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86885e4d16c464f9daa84e973f06411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF662C,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":652},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fa76f606bdc468e94959d600bd743c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":272,
              "y":652},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa471046fd149209e5e9d94c2a7af07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":272,
                  "y":652},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaf539ea254e46138428798dbee9ba92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":646},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10c47f83cf647a581ea04755d71205b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":646},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表/u94.png"}},
{
          "id":"74c2907d368849b28a4a3ab153093349",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":165,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaed9c28fcd7499f8b0043a3c64d57f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":165,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u11.png"}},
{
          "id":"3c42b4d7fad945e48db69f2172e55855",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":137,
              "y":192},
            "size":{
              "width":10,
              "height":8},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a9f54bad2d74594bc129c5bcdb529fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":137,
                  "y":192},
                "size":{
                  "width":10,
                  "height":8},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u97.png"}},
{
          "id":"05396e9a78844e8dacf1dc46a26d8840",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":196,
              "y":177},
            "size":{
              "width":157,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"637c591d676b4d72a6da46f2f425a39d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":196,
                  "y":177},
                "size":{
                  "width":157,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u99.png"}},
{
          "id":"039e62a172f7452bbcecaebfccf4f092",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":189},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"515d7b2f2a0d4c8e91b7bca4f27abbdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":189},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u101.png"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "c2a0b085325a407abcff977530ee6b77":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "36155ca0d8c74be9ac74ca24590a2b90":{
      "scriptId":"u5"},
    "1920fd90b35a4763b71d169e7daf0b93":{
      "scriptId":"u6"},
    "b867e7d756a94ec887475bee90df9bc8":{
      "scriptId":"u7"},
    "80cd93f614bb42c6941e1a5023869436":{
      "scriptId":"u8"},
    "dea96f926a624792a2c2bd58db299d0f":{
      "scriptId":"u9"},
    "62f53391db4a43d7904d131f07759c3e":{
      "scriptId":"u10"},
    "ff4a25c23d2f48f6a1a9784ff7a7928b":{
      "scriptId":"u11"},
    "a41ca3795d024e42ad6407940752fd94":{
      "scriptId":"u12"},
    "4decd258d13c4f19b9a0397bc7faa0bf":{
      "scriptId":"u13"},
    "5c7aaf377b1d4a80a9b9b03473058a85":{
      "scriptId":"u14"},
    "8acf3b683f0a4069bdc3adbbab5d30b8":{
      "scriptId":"u15"},
    "7bab7ded57b842bd917cfce5d4a5f8d8":{
      "scriptId":"u16"},
    "08fe0dce9bab4868a905e999a36e6880":{
      "scriptId":"u17"},
    "5b6a4cbf609e423d8671afc075f8ccbc":{
      "scriptId":"u18"},
    "9ce028efd182446d8a3054ce76898fc3":{
      "scriptId":"u19"},
    "ff442e1704c4418e9dddf817e4223e9c":{
      "scriptId":"u20"},
    "513a9460b06c45e083ec969db65208d9":{
      "scriptId":"u21"},
    "25834727a20c4620a5a9ca8d6b85335a":{
      "scriptId":"u22"},
    "a597857be3524220a0ebb90a83d24994":{
      "scriptId":"u23"},
    "f70cedad81654a49acf155f69bf6dbde":{
      "scriptId":"u24"},
    "bbf526c949ac45c2931628908908347f":{
      "scriptId":"u25"},
    "5a6d781894ef46309c60c21b56c72eca":{
      "scriptId":"u26"},
    "912fd21ea9b647d5a3ff9d9058dcd028":{
      "scriptId":"u27"},
    "c4eeeb48dfaa4657a0a9cd66b20ccfdb":{
      "scriptId":"u28"},
    "bad848092bba40d3ac9e0bf5d7830fb6":{
      "scriptId":"u29"},
    "aca83071cd064455afa8e1866532f593":{
      "scriptId":"u30"},
    "cad36197a8b4440b81174548c9e69380":{
      "scriptId":"u31"},
    "03b7e9cfa97e4d2ebb9d78707bb11552":{
      "scriptId":"u32"},
    "9a96f7fd4e894dda99b9affb5c0cd5ef":{
      "scriptId":"u33"},
    "c5b21798fec742f8b53a906b37819a35":{
      "scriptId":"u34"},
    "e68911fca9e7402590e4ee816f9e46dc":{
      "scriptId":"u35"},
    "97adfa3ebae34efbafb4b82f91a7cd42":{
      "scriptId":"u36"},
    "7e38d466efe84c03b3aa6fd43541c916":{
      "scriptId":"u37"},
    "54ba8768faa6415b9ebc7b1382ac74c5":{
      "scriptId":"u38"},
    "685a20ad608c4a6cb33c19c650c8504f":{
      "scriptId":"u39"},
    "3768c61b2b4c41a78d46119d5d134b63":{
      "scriptId":"u40"},
    "21d0f9274cea4e328257954eddfe41fc":{
      "scriptId":"u41"},
    "8f15de7bc0f64231a8d950828a776159":{
      "scriptId":"u42"},
    "24e722e2d2f84032bf4e7a12749c1409":{
      "scriptId":"u43"},
    "834fefd0c84a45b680e41ead88502cde":{
      "scriptId":"u44"},
    "f62580b302bc42fd9f9ad5bde0407e3d":{
      "scriptId":"u45"},
    "d942d93a203b4f0ebf921eae966dc8d5":{
      "scriptId":"u46"},
    "f7668b896f314917b51089418269dff0":{
      "scriptId":"u47"},
    "88c17e1a99354c97bf54fa40e1ce6403":{
      "scriptId":"u48"},
    "525eb030391c4cc2b45961ea0532c4aa":{
      "scriptId":"u49"},
    "acfc344cb32946dd87b3b006d2a2784e":{
      "scriptId":"u50"},
    "efe3f34927634fd69a6e5a79b23b4375":{
      "scriptId":"u51"},
    "b6eeb3a9a24940c69f9a540a98607c4e":{
      "scriptId":"u52"},
    "5f36e143f4cd460483c0ea9763da3f10":{
      "scriptId":"u53"},
    "0cad46e864464e70a2fdfb9d049a2c3a":{
      "scriptId":"u54"},
    "ed832c1b17f94fb6b9a18a3ea6e400e9":{
      "scriptId":"u55"},
    "38d2f39c5c5d4201ac362e3b364928bb":{
      "scriptId":"u56"},
    "3d58ccdd7fd641f89ae298da3ada8af2":{
      "scriptId":"u57"},
    "f01bf2a4b0eb4e15940ececd478931c2":{
      "scriptId":"u58"},
    "7ac9fbef9810438da980f1b1aa00c702":{
      "scriptId":"u59"},
    "f18ed0d68ae14394963fd59e6c842351":{
      "scriptId":"u60"},
    "7e12ebc5449c4826ba8b47b135778eeb":{
      "scriptId":"u61"},
    "7b06d57421f54bd2a6dd4fbae2443c34":{
      "scriptId":"u62"},
    "8c466741865a45e5bc85b8083f4ffa8c":{
      "scriptId":"u63"},
    "284ce50583ae4b9bb7ce5d772b34b903":{
      "scriptId":"u64"},
    "43c33050b8c54406a35313e879b893e9":{
      "scriptId":"u65"},
    "21548246a60f451aa66de2b9d9a8ce9a":{
      "scriptId":"u66"},
    "dce41d6cb2994009a7605447b3ebf318":{
      "scriptId":"u67"},
    "d1f82eb194b149838764550c05320653":{
      "scriptId":"u68"},
    "a623f4f99d9d486b92397841da3957f9":{
      "scriptId":"u69"},
    "cba05b317b9442e7ad9568f7a988ade0":{
      "scriptId":"u70"},
    "af4713fbd459412286f0a2b01e49f8c5":{
      "scriptId":"u71"},
    "894cb57fafb74202851c713d7cb6554e":{
      "scriptId":"u72"},
    "ea5cb52764724dc8b122a53064d72f9a":{
      "scriptId":"u73"},
    "0bbff5368fe24d8eaf1763c22599fdba":{
      "scriptId":"u74"},
    "66255d1c35ca49109abcaa560a360d48":{
      "scriptId":"u75"},
    "f1d99cb0863345d4a7a954d4922ba055":{
      "scriptId":"u76"},
    "35dc8615468b4622b6c7ae6815abd313":{
      "scriptId":"u77"},
    "991ef8b7d47e457bb508dd9b334d3e09":{
      "scriptId":"u78"},
    "00815f921aff490aa02deeaebc04946c":{
      "scriptId":"u79"},
    "df8031078d294eb6b15e9d2c66234c96":{
      "scriptId":"u80"},
    "42f7c19e130d416eaf4a9be0e7d470c4":{
      "scriptId":"u81"},
    "ac1dc9fb2c084551a11e6ba6885a3f63":{
      "scriptId":"u82"},
    "a1913323d3ae4041b977385a91b650df":{
      "scriptId":"u83"},
    "77e7b318674f44798b080a16ed5ce65e":{
      "scriptId":"u84"},
    "855ebfd96d924236b74669d7938af0a8":{
      "scriptId":"u85"},
    "8d197c2f6c03418f92952e9011882b50":{
      "scriptId":"u86"},
    "9624aecf1890432288e0ab3b599231da":{
      "scriptId":"u87"},
    "dd942f2b13f54cb1b17e4a7c46a143b4":{
      "scriptId":"u88"},
    "6a66187bff2a4e91b42c705ea1e03c50":{
      "scriptId":"u89"},
    "066a8e06bf2744d9b470b96cf8fadb28":{
      "scriptId":"u90"},
    "e137370cbf5644c9ac501951eb0b4bab":{
      "scriptId":"u91"},
    "1483e0a19f864965afa4f878561a85f7":{
      "scriptId":"u92"},
    "9862dc8260254855b6a6eb7810c45c78":{
      "scriptId":"u93"},
    "5526cff04efb443cb217ac2cdfe751bf":{
      "scriptId":"u94"},
    "f8620d2509ac47fb8c36200dd8dbd841":{
      "scriptId":"u95"},
    "575abc47bed54fe8b1ea03cc1367cb69":{
      "scriptId":"u96"},
    "7c7ac32bccd341219155ae18e639d66c":{
      "scriptId":"u97"},
    "dfc3c81861bc4613ae8d4cf7b1ed35a4":{
      "scriptId":"u98"},
    "b86885e4d16c464f9daa84e973f06411":{
      "scriptId":"u99"},
    "5fa76f606bdc468e94959d600bd743c8":{
      "scriptId":"u100"},
    "6aa471046fd149209e5e9d94c2a7af07":{
      "scriptId":"u101"},
    "eaf539ea254e46138428798dbee9ba92":{
      "scriptId":"u102"},
    "a10c47f83cf647a581ea04755d71205b":{
      "scriptId":"u103"},
    "74c2907d368849b28a4a3ab153093349":{
      "scriptId":"u104"},
    "aaed9c28fcd7499f8b0043a3c64d57f3":{
      "scriptId":"u105"},
    "3c42b4d7fad945e48db69f2172e55855":{
      "scriptId":"u106"},
    "9a9f54bad2d74594bc129c5bcdb529fe":{
      "scriptId":"u107"},
    "05396e9a78844e8dacf1dc46a26d8840":{
      "scriptId":"u108"},
    "637c591d676b4d72a6da46f2f425a39d":{
      "scriptId":"u109"},
    "039e62a172f7452bbcecaebfccf4f092":{
      "scriptId":"u110"},
    "515d7b2f2a0d4c8e91b7bca4f27abbdc":{
      "scriptId":"u111"}}});