$axure.loadCurrentPage({
  "url":"本地服务列表.html",
  "generationDate":new Date(1420531290893.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dd1abff9eacf47f4b6bbfd5009b78ae4",
    "type":"Axure:Page",
    "name":"本地服务列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c2a0b085325a407abcff977530ee6b77",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"36155ca0d8c74be9ac74ca24590a2b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1920fd90b35a4763b71d169e7daf0b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"b867e7d756a94ec887475bee90df9bc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80cd93f614bb42c6941e1a5023869436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 本地服务",
                      "target":{
                        "targetType":"page",
                        "url":"本地服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"dea96f926a624792a2c2bd58db299d0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":508},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f53391db4a43d7904d131f07759c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":508},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻详情/u9.png"}},
{
          "id":"e137370cbf5644c9ac501951eb0b4bab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1483e0a19f864965afa4f878561a85f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信息发布",
                      "target":{
                        "targetType":"page",
                        "url":"信息发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/房产列表/u129.png"}},
{
          "id":"4cd0f9bc1141438d860311c076895394",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":165,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8232dfe89c754957a6ef0155c3ac84f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":165,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u11.png"}},
{
          "id":"38e8365803254b42b88232a1ab659c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":137,
              "y":192},
            "size":{
              "width":10,
              "height":8},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e98ce8e6b164d9d935d1e7fa5a0ee5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":137,
                  "y":192},
                "size":{
                  "width":10,
                  "height":8},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u97.png"}},
{
          "id":"fac6bdcb09e7474f8797405911eee334",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":196,
              "y":177},
            "size":{
              "width":157,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afccf36c8dc240a7aef70ea4b337de57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":196,
                  "y":177},
                "size":{
                  "width":157,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u99.png"}},
{
          "id":"2ae6206b758c4a9f91e13d804224e744",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":189},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed6773540a144c18a2ff8e49d997e42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":189},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/生活服务列表/u101.png"}},
{
          "id":"4ef048fe56774833ade17d3212fc211c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":213},
            "size":{
              "width":342,
              "height":467}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ecd52af07e7a44529797fbbc86f9436b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"598e164cb26c4905b0b5e9a86e43b077",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":70},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cda39be974714cf2a00d3183fd6bc03a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":70},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"7cff739334d94ebd815c56ef95cf1e23",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":72},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21fed8cab4da4dae94126648b43f40ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":72},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3b0126f285504869a14be9f16b834295",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"c43419da97e6466980669bd8ffc10c8e",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":15},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e52d9afa9c994d2aa2f6fb5b67b703c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":15},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b3a57c1f143b413d9ba5dd22f5bc7ef9",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":44},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59eb346b0aec40fdae10151a53f3ba17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":44},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f8b264d47fce4ddaa8c523d76b67b1c9",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":76},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"beb3041af85b4324979f470aec9ed90f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":76},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b68a292aaf054a34b98266f4e80d0210",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"8a4108a9fd2d45a19a7e1e2350953ddb",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":109},
                    "size":{
                      "width":198,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a315a95f05544f3ab102347a29151ef1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":109},
                        "size":{
                          "width":198,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c08c62e16791487bb67929170e56613a",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":147},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea2abb8f4f2a49fc8b7165029c8e2e00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":147},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c0b07f1f019e46f88dce75c934fd9eba",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":175},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7368915b640246f9b60944ac71459fbc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":175},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f185cb9804804bd6a3798bc127f4ecff",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":292},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"00d47930b48242bbaeb3d6053b5eeed2",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":208},
                    "size":{
                      "width":200,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18269ee7fe9144b78111852317986d6d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":208},
                        "size":{
                          "width":200,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ddfd1aaee4a24e76a7d0cf420fd31b2e",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":246},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"578a1aceee4743d8995aa61a906cf180",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":246},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a7a102e1355143c4a48eeb7c5cfe1aad",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":274},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c767e744f5574f4ba2092bd9761aa605",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":274},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f524b7e5c9d0419c947bce73b70a29d3",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"4693e49addf549b59a03c4f9bd575f5b",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":391},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"53579c3757f84ac3855c1e4c3b6ad0ad",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":311},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c48a7989ce504e6a96365fca3de7a1cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":311},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d954f2574e3841bdbb0b22526fbe64c0",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":342},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9ea2b40629949edbab50014cbeed96d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":342},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1f0e246c435b48d394fd78cb43d3e927",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":373},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b75b597292b6454382592e970b986acd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":373},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0540f67b4fb44f209fb6d9be1bcce51c",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":10},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35b5d096089f4c19b7d2308aad523b34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":10},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u47.png"}},
{
                  "id":"352b5b2b6f9e4783a32b2f81c4965fb2",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":208},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3af0591692874e279ab86c1c0d281034",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":208},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u49.png"}},
{
                  "id":"3e15eec4fd844e24b9d855232c18e6d9",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":109},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeaca6f593864b3db406c3f0fc82e3e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":109},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u51.jpg"}},
{
                  "id":"8c188d1c154444e19e5bfe2e9de5822a",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "lineSpacing":"28px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":8,
                      "y":306},
                    "size":{
                      "width":106,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c5ff197571845fea7e684e31fadd4db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "lineSpacing":"28px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":8,
                          "y":306},
                        "size":{
                          "width":106,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u53.png"}},
{
                  "id":"5ddc261c566d47f5aa80bf680bc8589c",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":490},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"cd5f4eed411a430dba4acc22e5466d4f",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":406},
                    "size":{
                      "width":200,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73bd6ec42e7f4cb9b83d117c6663f148",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":406},
                        "size":{
                          "width":200,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bb1f412fa9b4437d8425a50d45028d56",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":444},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2646c5ee5bd34d9ea7999b93c69818ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":444},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e08c1d990e5c4674956d680fc86213c8",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":472},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0959247fcc4c4789a51e42344248534b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":472},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"79342335439543e49ef2282bbb139ee5",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":391},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"13ca35b06a90493f87d6f6d7cce7fa4d",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":589},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"0573840ea5964e72a793e136b49c5c10",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":122,
                      "y":509},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50ab5a1528c541f6bc9d788d27319249",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":122,
                          "y":509},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"643a1ea3807848c8a2d864d5031bf7b8",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":122,
                      "y":540},
                    "size":{
                      "width":190,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"472365c59b7340feb9aa458138b9054b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":122,
                          "y":540},
                        "size":{
                          "width":190,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99c93721e68d45ee94235640ec10d38f",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":246,
                      "y":571},
                    "size":{
                      "width":67,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fcababff7b5449ce9283a9b180d9411b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":246,
                          "y":571},
                        "size":{
                          "width":67,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"94115147f56b46b8a17ba215879e83f0",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":406},
                    "size":{
                      "width":106,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2be5097dbba48429e01493001fd88f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":406},
                        "size":{
                          "width":106,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u49.png"}},
{
                  "id":"401bad05a08a4815934dfb826eaa9a4d",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "lineSpacing":"28px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":8,
                      "y":504},
                    "size":{
                      "width":106,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c343f0bb3b1946819b772b4d1372621d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Adobe 楷体 Std R Bold', 'Adobe 楷体 Std'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "lineSpacing":"28px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":8,
                          "y":504},
                        "size":{
                          "width":106,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务列表/u53.png"}},
{
                  "id":"4813f1048fac481bb2794d7e93c9dfba",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":0},
                    "size":{
                      "width":314,
                      "height":99}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 本地服务详情",
                              "target":{
                                "targetType":"page",
                                "url":"本地服务详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"d3b8d647502b47468483456a7850928e",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":170},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82e64d44696c4337920949ab87632aa2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":170},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"6720b3adc3704344a25155554cf31421",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":172},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"548d7dab0ecb4979aa0fa93037dffa71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":172},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9e48f6b4506c46b98232c919e1fd7453",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":270},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa978c14302348c488815833eddd327f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":270},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"f118cbea83fb4e3e931eae46d4e93b84",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":272},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35d020df339e4f3fb45dfd178cba5813",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":272},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"55dd183b475d4ee8911ad121c82be834",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":366},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cccbdddbb64a42d599f29f133c850fe4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":366},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"46e4e117008e4639982ef8e41bcb66d5",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":368},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36fd31b374a34027b2791d1cf6b6a0bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":368},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"19a6f1903f2f414ea8af9d60f322c9b2",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":466},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33f7b3c252574b46a83b0a05f2aa5209",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":466},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"715b526a151c457383100851c52f8ae8",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":468},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06dadcff745a418c8472abf111364b5f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":468},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5960f537669f4e209a5bbc692bd9c6ba",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":564},
                    "size":{
                      "width":19,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e6561c8b06e480d942010b497cae3cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":564},
                        "size":{
                          "width":19,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"db7533cc1383474ab8027d5cc5ebf17a",
                  "label":"",
                  "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":147,
                      "y":566},
                    "size":{
                      "width":31,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b442d7b2dce24403b8f374558cf4d9ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ef048fe56774833ade17d3212fc211c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":147,
                          "y":566},
                        "size":{
                          "width":31,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "c2a0b085325a407abcff977530ee6b77":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "36155ca0d8c74be9ac74ca24590a2b90":{
      "scriptId":"u5"},
    "1920fd90b35a4763b71d169e7daf0b93":{
      "scriptId":"u6"},
    "b867e7d756a94ec887475bee90df9bc8":{
      "scriptId":"u7"},
    "80cd93f614bb42c6941e1a5023869436":{
      "scriptId":"u8"},
    "dea96f926a624792a2c2bd58db299d0f":{
      "scriptId":"u9"},
    "62f53391db4a43d7904d131f07759c3e":{
      "scriptId":"u10"},
    "e137370cbf5644c9ac501951eb0b4bab":{
      "scriptId":"u11"},
    "1483e0a19f864965afa4f878561a85f7":{
      "scriptId":"u12"},
    "4cd0f9bc1141438d860311c076895394":{
      "scriptId":"u13"},
    "8232dfe89c754957a6ef0155c3ac84f2":{
      "scriptId":"u14"},
    "38e8365803254b42b88232a1ab659c15":{
      "scriptId":"u15"},
    "2e98ce8e6b164d9d935d1e7fa5a0ee5d":{
      "scriptId":"u16"},
    "fac6bdcb09e7474f8797405911eee334":{
      "scriptId":"u17"},
    "afccf36c8dc240a7aef70ea4b337de57":{
      "scriptId":"u18"},
    "2ae6206b758c4a9f91e13d804224e744":{
      "scriptId":"u19"},
    "6ed6773540a144c18a2ff8e49d997e42":{
      "scriptId":"u20"},
    "4ef048fe56774833ade17d3212fc211c":{
      "scriptId":"u21"},
    "598e164cb26c4905b0b5e9a86e43b077":{
      "scriptId":"u22"},
    "cda39be974714cf2a00d3183fd6bc03a":{
      "scriptId":"u23"},
    "7cff739334d94ebd815c56ef95cf1e23":{
      "scriptId":"u24"},
    "21fed8cab4da4dae94126648b43f40ef":{
      "scriptId":"u25"},
    "3b0126f285504869a14be9f16b834295":{
      "scriptId":"u26"},
    "c43419da97e6466980669bd8ffc10c8e":{
      "scriptId":"u27"},
    "e52d9afa9c994d2aa2f6fb5b67b703c7":{
      "scriptId":"u28"},
    "b3a57c1f143b413d9ba5dd22f5bc7ef9":{
      "scriptId":"u29"},
    "59eb346b0aec40fdae10151a53f3ba17":{
      "scriptId":"u30"},
    "f8b264d47fce4ddaa8c523d76b67b1c9":{
      "scriptId":"u31"},
    "beb3041af85b4324979f470aec9ed90f":{
      "scriptId":"u32"},
    "b68a292aaf054a34b98266f4e80d0210":{
      "scriptId":"u33"},
    "8a4108a9fd2d45a19a7e1e2350953ddb":{
      "scriptId":"u34"},
    "a315a95f05544f3ab102347a29151ef1":{
      "scriptId":"u35"},
    "c08c62e16791487bb67929170e56613a":{
      "scriptId":"u36"},
    "ea2abb8f4f2a49fc8b7165029c8e2e00":{
      "scriptId":"u37"},
    "c0b07f1f019e46f88dce75c934fd9eba":{
      "scriptId":"u38"},
    "7368915b640246f9b60944ac71459fbc":{
      "scriptId":"u39"},
    "f185cb9804804bd6a3798bc127f4ecff":{
      "scriptId":"u40"},
    "00d47930b48242bbaeb3d6053b5eeed2":{
      "scriptId":"u41"},
    "18269ee7fe9144b78111852317986d6d":{
      "scriptId":"u42"},
    "ddfd1aaee4a24e76a7d0cf420fd31b2e":{
      "scriptId":"u43"},
    "578a1aceee4743d8995aa61a906cf180":{
      "scriptId":"u44"},
    "a7a102e1355143c4a48eeb7c5cfe1aad":{
      "scriptId":"u45"},
    "c767e744f5574f4ba2092bd9761aa605":{
      "scriptId":"u46"},
    "f524b7e5c9d0419c947bce73b70a29d3":{
      "scriptId":"u47"},
    "4693e49addf549b59a03c4f9bd575f5b":{
      "scriptId":"u48"},
    "53579c3757f84ac3855c1e4c3b6ad0ad":{
      "scriptId":"u49"},
    "c48a7989ce504e6a96365fca3de7a1cf":{
      "scriptId":"u50"},
    "d954f2574e3841bdbb0b22526fbe64c0":{
      "scriptId":"u51"},
    "d9ea2b40629949edbab50014cbeed96d":{
      "scriptId":"u52"},
    "1f0e246c435b48d394fd78cb43d3e927":{
      "scriptId":"u53"},
    "b75b597292b6454382592e970b986acd":{
      "scriptId":"u54"},
    "0540f67b4fb44f209fb6d9be1bcce51c":{
      "scriptId":"u55"},
    "35b5d096089f4c19b7d2308aad523b34":{
      "scriptId":"u56"},
    "352b5b2b6f9e4783a32b2f81c4965fb2":{
      "scriptId":"u57"},
    "3af0591692874e279ab86c1c0d281034":{
      "scriptId":"u58"},
    "3e15eec4fd844e24b9d855232c18e6d9":{
      "scriptId":"u59"},
    "eeaca6f593864b3db406c3f0fc82e3e1":{
      "scriptId":"u60"},
    "8c188d1c154444e19e5bfe2e9de5822a":{
      "scriptId":"u61"},
    "7c5ff197571845fea7e684e31fadd4db":{
      "scriptId":"u62"},
    "5ddc261c566d47f5aa80bf680bc8589c":{
      "scriptId":"u63"},
    "cd5f4eed411a430dba4acc22e5466d4f":{
      "scriptId":"u64"},
    "73bd6ec42e7f4cb9b83d117c6663f148":{
      "scriptId":"u65"},
    "bb1f412fa9b4437d8425a50d45028d56":{
      "scriptId":"u66"},
    "2646c5ee5bd34d9ea7999b93c69818ba":{
      "scriptId":"u67"},
    "e08c1d990e5c4674956d680fc86213c8":{
      "scriptId":"u68"},
    "0959247fcc4c4789a51e42344248534b":{
      "scriptId":"u69"},
    "79342335439543e49ef2282bbb139ee5":{
      "scriptId":"u70"},
    "13ca35b06a90493f87d6f6d7cce7fa4d":{
      "scriptId":"u71"},
    "0573840ea5964e72a793e136b49c5c10":{
      "scriptId":"u72"},
    "50ab5a1528c541f6bc9d788d27319249":{
      "scriptId":"u73"},
    "643a1ea3807848c8a2d864d5031bf7b8":{
      "scriptId":"u74"},
    "472365c59b7340feb9aa458138b9054b":{
      "scriptId":"u75"},
    "99c93721e68d45ee94235640ec10d38f":{
      "scriptId":"u76"},
    "fcababff7b5449ce9283a9b180d9411b":{
      "scriptId":"u77"},
    "94115147f56b46b8a17ba215879e83f0":{
      "scriptId":"u78"},
    "e2be5097dbba48429e01493001fd88f9":{
      "scriptId":"u79"},
    "401bad05a08a4815934dfb826eaa9a4d":{
      "scriptId":"u80"},
    "c343f0bb3b1946819b772b4d1372621d":{
      "scriptId":"u81"},
    "4813f1048fac481bb2794d7e93c9dfba":{
      "scriptId":"u82"},
    "d3b8d647502b47468483456a7850928e":{
      "scriptId":"u83"},
    "82e64d44696c4337920949ab87632aa2":{
      "scriptId":"u84"},
    "6720b3adc3704344a25155554cf31421":{
      "scriptId":"u85"},
    "548d7dab0ecb4979aa0fa93037dffa71":{
      "scriptId":"u86"},
    "9e48f6b4506c46b98232c919e1fd7453":{
      "scriptId":"u87"},
    "aa978c14302348c488815833eddd327f":{
      "scriptId":"u88"},
    "f118cbea83fb4e3e931eae46d4e93b84":{
      "scriptId":"u89"},
    "35d020df339e4f3fb45dfd178cba5813":{
      "scriptId":"u90"},
    "55dd183b475d4ee8911ad121c82be834":{
      "scriptId":"u91"},
    "cccbdddbb64a42d599f29f133c850fe4":{
      "scriptId":"u92"},
    "46e4e117008e4639982ef8e41bcb66d5":{
      "scriptId":"u93"},
    "36fd31b374a34027b2791d1cf6b6a0bf":{
      "scriptId":"u94"},
    "19a6f1903f2f414ea8af9d60f322c9b2":{
      "scriptId":"u95"},
    "33f7b3c252574b46a83b0a05f2aa5209":{
      "scriptId":"u96"},
    "715b526a151c457383100851c52f8ae8":{
      "scriptId":"u97"},
    "06dadcff745a418c8472abf111364b5f":{
      "scriptId":"u98"},
    "5960f537669f4e209a5bbc692bd9c6ba":{
      "scriptId":"u99"},
    "5e6561c8b06e480d942010b497cae3cb":{
      "scriptId":"u100"},
    "db7533cc1383474ab8027d5cc5ebf17a":{
      "scriptId":"u101"},
    "b442d7b2dce24403b8f374558cf4d9ca":{
      "scriptId":"u102"}}});