$axure.loadCurrentPage({
  "url":"本地服务详情.html",
  "generationDate":new Date(1420531291011.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4c6409bec7a544f598ce7b9310548abd",
    "type":"Axure:Page",
    "name":"本地服务详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3afa16ce1e2d4688954346594eaf88e1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"c317025246f24250a302b038f60e5b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4d6f971fbc454296a72c8542bf9509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"1c0d53c986ed4d22ac8e83463b6ac18b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f2a78a138a346729ccbecd8384e696f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 本地服务列表",
                      "target":{
                        "targetType":"page",
                        "url":"本地服务列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"12a9bed7bfaf49f88d54d1984daf3eba",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":177},
            "size":{
              "width":340,
              "height":443}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43f843965f15483e9f322929cb0050f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d30e0ce8300b407996838c6384c88be5",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8019f292cff64bd59ce40bb98bfa4602",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务详情/u23.png"}},
{
                  "id":"ad8e52c3792d47f39814a375ce183c76",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":129,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"194b981db4d940aea86846937ea8faf6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":129,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"6e03da86acb84ec49082b173cba27a15",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":153,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdb5d08a478840b286d3c61224896b86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":153,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"e7ad33f47c9f4979b05a99b47a09efe6",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":177,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"655a500cbe204e8d836ff73cea12b13e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":177,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"9c82c23c93b24d1cbab8e2e2c6d66e89",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":240},
                    "size":{
                      "width":302,
                      "height":340},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7b6da76f0c246fc806c89dcef9c2400",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":240},
                        "size":{
                          "width":302,
                          "height":340},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生活服务详情/u10.png"}},
{
                  "id":"1ff3e8a5b6254a1e9432955eb6540c89",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":528},
                    "size":{
                      "width":302,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u43_line.png"}},
{
                  "id":"6a687960d9c44e238c8b7db0dc2478f0",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":11,
                      "y":171},
                    "size":{
                      "width":298,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6b15a4bd16894d5489bf9bd9a04086af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":11,
                          "y":171},
                        "size":{
                          "width":298,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"18d49f3d5b0848e9a8d9cfb9eec603e8",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":205},
                    "size":{
                      "width":146,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ffe2b96326f48d584098f3787695dbb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":205},
                        "size":{
                          "width":146,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b743bf0951bd42c288cac7d49f1b2425",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":21,
                      "y":237},
                    "size":{
                      "width":269,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"329b543e01e841f28ee2236508a98eb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":21,
                          "y":237},
                        "size":{
                          "width":269,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4a39947041584020a0a92d028ce32b25",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"18px",
                    "location":{
                      "x":21,
                      "y":293},
                    "size":{
                      "width":271,
                      "height":108}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88f26fd96c0f4c20bec9b54ec97431b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"18px",
                        "location":{
                          "x":21,
                          "y":293},
                        "size":{
                          "width":271,
                          "height":108}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"89346dbecc5f4226bb570d100ff8da37",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"18px",
                    "location":{
                      "x":21,
                      "y":413},
                    "size":{
                      "width":271,
                      "height":108}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0dbf7693d71c4d149cabb491ab202c7c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"18px",
                        "location":{
                          "x":21,
                          "y":413},
                        "size":{
                          "width":271,
                          "height":108}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2cf03b1dd27e473fbd9c6f33730adbb9",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":21,
                      "y":547},
                    "size":{
                      "width":259,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7201da42db9c42d49f0d273582fd90be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":21,
                          "y":547},
                        "size":{
                          "width":259,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e2347a704cfb4457a32e684bbd3e38d3",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":258,
                      "y":196},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6bae93c32c924088ae8d1d6dc06932d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":258,
                          "y":196},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"bcdceee2bd27443bb2b7e2e7c06aced0",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":288,
                      "y":200},
                    "size":{
                      "width":22,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1cbff9418394109b3f4492c6d3b14e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":288,
                          "y":200},
                        "size":{
                          "width":22,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"39277184d9aa4083a25a217e9a92696e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":27,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db6f037c8cb4a18b58620c9813522e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":27,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u20.png"}},
{
          "id":"c67496075f004aff865791355050173b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":144},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028fa829ec9d4101b67e4b3b89023315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":144},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 fenxiang 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u18.png"}},
{
          "id":"aab7cf0731004a1dbb6063f361458723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":630},
            "size":{
              "width":321,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffcffd626934491ba1b4817d3c0e9542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":630},
                "size":{
                  "width":321,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u9.png"}},
{
          "id":"6f8c3531a05a4581a99350f0de717ba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":45,
              "y":638},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e6cd9a59834b29b527d474ba56b508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":45,
                  "y":638},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdc0f1ec55ba48f5b7732372e48595ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":44,
              "y":662},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0638b5778394269b54e303ecbef8f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":662},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"375b671e499a40d7a12792e2877db806",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":637},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘详情/u15_line.png"}},
{
          "id":"3e1f08a2dec649b6b69f756475ba02e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":641},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2c8ef2621f4595a9732d949fe5cec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":641},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u16.png"}},
{
          "id":"4cbf4f753cc242e9a322f99681861228",
          "label":"fenxiang",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":568},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ecbcb5d2268240b7a5a907e339ad6915",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4040fa465f8742558d24b3a26fee4c82",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":320,
                      "height":545},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ea0c13145f24082b9e863c59862d824",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":320,
                          "height":545},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u58.png"}},
{
                  "id":"6a0edb0ca1cd4d6ea80aa0c7e5597c23",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":304},
                    "size":{
                      "width":321,
                      "height":265},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a0aa6f46ff641d4a9c5254a90af1917",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":304},
                        "size":{
                          "width":321,
                          "height":265},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u60.png"}},
{
                  "id":"4e5a698539404713b8fe5dd2e6c7cb50",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":359},
                    "size":{
                      "width":320,
                      "height":4},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acf07dc8f6824d43bb07754cc070b79b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":359},
                        "size":{
                          "width":320,
                          "height":4},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u62.png"}},
{
                  "id":"5695acb419634a12947a39bcc21f0a20",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":144,
                      "y":322},
                    "size":{
                      "width":39,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54ce1ddc5ef1426cb285416850325c91",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":144,
                          "y":322},
                        "size":{
                          "width":39,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f435b98abc1b4c69b89629814b872fc2",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa83a050ea074ef284da2968cfc47cc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":20,
                          "y":507},
                        "size":{
                          "width":280,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u66.png"}},
{
                  "id":"17aab75fd845444e8ef608854af9e54b",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 fenxiang 向下滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"77f1215fb7cd449c96684d8675ed9310",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ffe5ce6f3b941918bc094c240c84dee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u69.png"}},
{
                  "id":"90380fb2d93f4965962ad07679f1b6cd",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":192,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c921e53aa593403b88406b2ea36027b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":192,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u71.png"}},
{
                  "id":"32f6f1b807574e4e88d1105e653f50bc",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":48,
                      "y":471},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a72de691eb174be380904e67905f3347",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":48,
                          "y":471},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f415bfb1ec2426592c5312cb93e8ac8",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":194,
                      "y":471},
                    "size":{
                      "width":83,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f54316d3784544889116cbdd7b5555d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":194,
                          "y":471},
                        "size":{
                          "width":83,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1d171c90045847be906014fbf216ee7c",
          "label":"cg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":118,
              "y":380},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eb7a97d572f54721a9a6c05ce7f91a16",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b6171c19ccaf4eeca9234185ead4d9b8",
                  "label":"cg",
                  "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":150,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeadfb91863141f6b16bd2b3697ca1d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":150,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/cg_u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "3afa16ce1e2d4688954346594eaf88e1":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "c317025246f24250a302b038f60e5b27":{
      "scriptId":"u5"},
    "1f4d6f971fbc454296a72c8542bf9509":{
      "scriptId":"u6"},
    "1c0d53c986ed4d22ac8e83463b6ac18b":{
      "scriptId":"u7"},
    "3f2a78a138a346729ccbecd8384e696f":{
      "scriptId":"u8"},
    "12a9bed7bfaf49f88d54d1984daf3eba":{
      "scriptId":"u9"},
    "d30e0ce8300b407996838c6384c88be5":{
      "scriptId":"u10"},
    "8019f292cff64bd59ce40bb98bfa4602":{
      "scriptId":"u11"},
    "ad8e52c3792d47f39814a375ce183c76":{
      "scriptId":"u12"},
    "194b981db4d940aea86846937ea8faf6":{
      "scriptId":"u13"},
    "6e03da86acb84ec49082b173cba27a15":{
      "scriptId":"u14"},
    "bdb5d08a478840b286d3c61224896b86":{
      "scriptId":"u15"},
    "e7ad33f47c9f4979b05a99b47a09efe6":{
      "scriptId":"u16"},
    "655a500cbe204e8d836ff73cea12b13e":{
      "scriptId":"u17"},
    "9c82c23c93b24d1cbab8e2e2c6d66e89":{
      "scriptId":"u18"},
    "f7b6da76f0c246fc806c89dcef9c2400":{
      "scriptId":"u19"},
    "1ff3e8a5b6254a1e9432955eb6540c89":{
      "scriptId":"u20"},
    "6a687960d9c44e238c8b7db0dc2478f0":{
      "scriptId":"u21"},
    "6b15a4bd16894d5489bf9bd9a04086af":{
      "scriptId":"u22"},
    "18d49f3d5b0848e9a8d9cfb9eec603e8":{
      "scriptId":"u23"},
    "8ffe2b96326f48d584098f3787695dbb":{
      "scriptId":"u24"},
    "b743bf0951bd42c288cac7d49f1b2425":{
      "scriptId":"u25"},
    "329b543e01e841f28ee2236508a98eb7":{
      "scriptId":"u26"},
    "4a39947041584020a0a92d028ce32b25":{
      "scriptId":"u27"},
    "88f26fd96c0f4c20bec9b54ec97431b0":{
      "scriptId":"u28"},
    "89346dbecc5f4226bb570d100ff8da37":{
      "scriptId":"u29"},
    "0dbf7693d71c4d149cabb491ab202c7c":{
      "scriptId":"u30"},
    "2cf03b1dd27e473fbd9c6f33730adbb9":{
      "scriptId":"u31"},
    "7201da42db9c42d49f0d273582fd90be":{
      "scriptId":"u32"},
    "e2347a704cfb4457a32e684bbd3e38d3":{
      "scriptId":"u33"},
    "6bae93c32c924088ae8d1d6dc06932d0":{
      "scriptId":"u34"},
    "bcdceee2bd27443bb2b7e2e7c06aced0":{
      "scriptId":"u35"},
    "e1cbff9418394109b3f4492c6d3b14e5":{
      "scriptId":"u36"},
    "39277184d9aa4083a25a217e9a92696e":{
      "scriptId":"u37"},
    "4db6f037c8cb4a18b58620c9813522e0":{
      "scriptId":"u38"},
    "c67496075f004aff865791355050173b":{
      "scriptId":"u39"},
    "028fa829ec9d4101b67e4b3b89023315":{
      "scriptId":"u40"},
    "aab7cf0731004a1dbb6063f361458723":{
      "scriptId":"u41"},
    "ffcffd626934491ba1b4817d3c0e9542":{
      "scriptId":"u42"},
    "6f8c3531a05a4581a99350f0de717ba2":{
      "scriptId":"u43"},
    "08e6cd9a59834b29b527d474ba56b508":{
      "scriptId":"u44"},
    "cdc0f1ec55ba48f5b7732372e48595ed":{
      "scriptId":"u45"},
    "b0638b5778394269b54e303ecbef8f8a":{
      "scriptId":"u46"},
    "375b671e499a40d7a12792e2877db806":{
      "scriptId":"u47"},
    "3e1f08a2dec649b6b69f756475ba02e5":{
      "scriptId":"u48"},
    "5f2c8ef2621f4595a9732d949fe5cec3":{
      "scriptId":"u49"},
    "4cbf4f753cc242e9a322f99681861228":{
      "scriptId":"u50"},
    "4040fa465f8742558d24b3a26fee4c82":{
      "scriptId":"u51"},
    "3ea0c13145f24082b9e863c59862d824":{
      "scriptId":"u52"},
    "6a0edb0ca1cd4d6ea80aa0c7e5597c23":{
      "scriptId":"u53"},
    "2a0aa6f46ff641d4a9c5254a90af1917":{
      "scriptId":"u54"},
    "4e5a698539404713b8fe5dd2e6c7cb50":{
      "scriptId":"u55"},
    "acf07dc8f6824d43bb07754cc070b79b":{
      "scriptId":"u56"},
    "5695acb419634a12947a39bcc21f0a20":{
      "scriptId":"u57"},
    "54ce1ddc5ef1426cb285416850325c91":{
      "scriptId":"u58"},
    "f435b98abc1b4c69b89629814b872fc2":{
      "scriptId":"u59"},
    "fa83a050ea074ef284da2968cfc47cc8":{
      "scriptId":"u60"},
    "17aab75fd845444e8ef608854af9e54b":{
      "scriptId":"u61"},
    "77f1215fb7cd449c96684d8675ed9310":{
      "scriptId":"u62"},
    "7ffe5ce6f3b941918bc094c240c84dee":{
      "scriptId":"u63"},
    "90380fb2d93f4965962ad07679f1b6cd":{
      "scriptId":"u64"},
    "c921e53aa593403b88406b2ea36027b6":{
      "scriptId":"u65"},
    "32f6f1b807574e4e88d1105e653f50bc":{
      "scriptId":"u66"},
    "a72de691eb174be380904e67905f3347":{
      "scriptId":"u67"},
    "0f415bfb1ec2426592c5312cb93e8ac8":{
      "scriptId":"u68"},
    "f54316d3784544889116cbdd7b5555d7":{
      "scriptId":"u69"},
    "1d171c90045847be906014fbf216ee7c":{
      "scriptId":"u70"},
    "b6171c19ccaf4eeca9234185ead4d9b8":{
      "scriptId":"u71"},
    "eeadfb91863141f6b16bd2b3697ca1d1":{
      "scriptId":"u72"}}});