$axure.loadCurrentPage({
  "url":"购物车编辑_1.html",
  "generationDate":new Date(1420531295250.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"866b17eb858b45e9909ca047240301ac",
    "type":"Axure:Page",
    "name":"购物车编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f49dc274f87465da2f695e12b9baccb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"a642293fc8a3470c968001cac0e45e73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7875b98a06747bd9cc6406f30caadd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"56c1e4250f9545428922cb755da6775b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbf4ed3129946eabc0fa019235d7032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车-团购",
                      "target":{
                        "targetType":"page",
                        "url":"购物车-团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"9179775ceeeb417f8b3cea6f300fbf72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":621},
            "size":{
              "width":321,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44217a7f22c34e25884ff28e64f6b705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":621},
                "size":{
                  "width":321,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u31.png"}},
{
          "id":"8a85fce7150443a2bcc5152c280f26c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":644},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c2f0f40ca3c48d4839bf43016a14394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":644},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"b8f5f9e39e3943ef82d1882d110065f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":78,
              "y":645},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23e53e7e8f8a479e8123f3925de6542c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":78,
                  "y":645},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe4e2d4140834290843e4c5eb1cc1137",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":249,
              "y":631},
            "size":{
              "width":95,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8830359a8f84c55814a951b7fdfa36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":249,
                  "y":631},
                "size":{
                  "width":95,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u37.png"}},
{
          "id":"4194d7ecd67a47e6ae04a7281a665c87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":644},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81d81992e31488eb3bb4f6c788e4728",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":644},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"599f58fd1140464a8451fa4bdb4c8080",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0D7AFF,
              "opacity":1},
            "location":{
              "x":306,
              "y":147},
            "size":{
              "width":32,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16fa98bae2f4e90b20a2ff5769bef0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0D7AFF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":147},
                "size":{
                  "width":32,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车-团购",
                      "target":{
                        "targetType":"page",
                        "url":"购物车-团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7131d0d466784beda603c44187350802",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb27fb26043f4adc917fc6ece35f0c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u9.png"}},
{
          "id":"a523b15a9d114d0fa17d17580f389528",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":191},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bbf1c260d7e4b0db5726f0e6795d576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":191},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"996f1439bdfe47739ae91d88afb67a1f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":216},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"8c70e5fc7d8843fb80068b0ab0923b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":77,
              "y":192},
            "size":{
              "width":163,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3636cc09875f4e989bc38e0915b875d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":192},
                "size":{
                  "width":163,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe7f3b528dcc4f0aab26e346e81379ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":252},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07c5378ff74455698c77c49b6565600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":252},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"cbfd3e4cbfb84a38b515eabd0289c161",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":236},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdce6a6e3b9f4c39beaa3391e899c6cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":236},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f999e4e09c04afe90a6b42918a6bb9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":293,
              "y":236},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce809f94ae549e094aca19b9801b792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":236},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"660563979c024561ac5582c7bbb5ec30",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":298},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"e6de0d86198e47618bada1627cf2768d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":313},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce4a3c97c320467285daeb94cb60ab32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":313},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1ae110fe66346fd8b1ed8f21ac48ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":246,
              "y":313},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16ee97172b04fa0a35184969e78027f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":246,
                  "y":313},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"927b0c9a3ff543c39c515d600e4cd980",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":351},
            "size":{
              "width":321,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75003af096f14d30b46d91b914c3860f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":351},
                "size":{
                  "width":321,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-团购/u35.png"}},
{
          "id":"8594fea1cdc1452192d90df5b0876b36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":365},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ca0742d92ff438ab39a4d961310ee18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":365},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"7b9afceeb3de4684b0308a919a6604e9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":390},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"d59f474eb032441982b8295679ae1910",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":77,
              "y":366},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63d2b69d24441b7910e808801c6b5ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":366},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c212fa7cf6f4ad88824cf2536741eda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6D6D6},
            "location":{
              "x":43,
              "y":426},
            "size":{
              "width":18,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae1b60b58cd4c949859e9bde6d9cf35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6D6D6},
                "location":{
                  "x":43,
                  "y":426},
                "size":{
                  "width":18,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u11.png"}},
{
          "id":"f5089621d1a245279bc76a194eb9af21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":409},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7ddfc88be7c46cab81433110821a0b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":409},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u18.png"}},
{
          "id":"715934886f884384b3052a43e86768f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":410},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c55a71175b334747ba46b5c0fb21c62b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":410},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5d922a9fc0245419e1ea6c387fe9004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":286,
              "y":410},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3abbfdc69b224184a74ff7082dfab818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":410},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"201d4c0bffec4408805cc55a03ed11d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":141,
              "y":432},
            "size":{
              "width":128,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ca4478ec5d4dcf8d03c137b7571851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":432},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a568eb08ca334d7189983c0c48be53c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":490},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"92ada6ff264a4fd38603035115cd70ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":506},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2873f3f72bf145769a503c79621227c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":506},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a253845468a47ed90cad4b1d2036006",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":246,
              "y":506},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef22c9c44efd42cead761636499640e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":246,
                  "y":506},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f8d9b8855ab4993bbf19026f27245a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":191},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b2547cf3c643e983a8ed5f638f05e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":191},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"ec234abd41134eb1b811c0421c89ca05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":252},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15c58daeab0644fab32275e7019cf4da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":252},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"e9bd964157a1437b8ca75433921bd936",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":262},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90395bb5966f434aaef64037fa3b2a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":262},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购详情/u27.png"}},
{
          "id":"dedfe26cd7ca4a9993f8be52d65f2403",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":165,
              "y":269},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a8fbe13496e4ca89e08793f2edea05f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":269},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0720e78a87e4af0978a0451ef9d3512",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":235},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c922c184103442ca71bdf53047b4a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":235},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-团购/u67.png"}},
{
          "id":"607ce2bc74804637b3f0651e5e603184",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":464},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e3f76a05294e528f69235459414344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":464},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购详情/u27.png"}},
{
          "id":"834490b7a3a8459185b119b3737bdde2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":165,
              "y":471},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8e6a1f7280e409ea97675249ee3e12f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":471},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4847166113e7420d99bbac893229735a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":365},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"592e9dde27064bc5a4ca7070740acd9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":365},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"e6883df0f36d4c4489cc6f3622f3ed53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":426},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41686710a274542ac02860816c2fd69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":426},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u30.png"}},
{
          "id":"2a0eb4c1ed964532b4325be695c90aca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":286,
              "y":266},
            "size":{
              "width":36,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf99a770b0e4b7b8e7813ea907d5b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":286,
                  "y":266},
                "size":{
                  "width":36,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车编辑/u73.png"}},
{
          "id":"05de20da8e2d43e8a8c78edf8022d26b",
          "label":"ipt",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "location":{
              "x":287,
              "y":267},
            "size":{
              "width":34,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"439b4253ae3f4bc2b99eb4c6c1889798",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":322,
              "y":266},
            "size":{
              "width":21,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e54ac85bab964956a58566ed2cadaca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":322,
                  "y":266},
                "size":{
                  "width":21,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 ipt = &quot;[[ipt+1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["05de20da8e2d43e8a8c78edf8022d26b"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[ipt+1]]",
                                "localVariables":{
                                  "ipt":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["05de20da8e2d43e8a8c78edf8022d26b"]}]}},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"ipt"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购物车编辑/u76.png"}},
{
          "id":"4820268454a8495093c1069847070c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":265,
              "y":266},
            "size":{
              "width":21,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83631c9575a4fa1a2be4835b0a00218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":266},
                "size":{
                  "width":21,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 ipt = &quot;[[ipt-1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["05de20da8e2d43e8a8c78edf8022d26b"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[ipt-1]]",
                                "localVariables":{
                                  "ipt":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["05de20da8e2d43e8a8c78edf8022d26b"]}]}},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"-",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"ipt"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购物车编辑/u78.png"}},
{
          "id":"700c97857cf5493796a3359c15a93b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":286,
              "y":440},
            "size":{
              "width":36,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4c0b2416dbc4dd588966c9e027014d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":286,
                  "y":440},
                "size":{
                  "width":36,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车编辑/u73.png"}},
{
          "id":"1fe8b98f1515492780975317902dd193",
          "label":"ipt",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "location":{
              "x":287,
              "y":441},
            "size":{
              "width":34,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"f85247f07d09400a92c4da87c74c942a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":322,
              "y":440},
            "size":{
              "width":21,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307c37f2d8444a0084136c711ed7a763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":322,
                  "y":440},
                "size":{
                  "width":21,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 ipt = &quot;[[ipt+1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1fe8b98f1515492780975317902dd193"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[ipt+1]]",
                                "localVariables":{
                                  "ipt":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["1fe8b98f1515492780975317902dd193"]}]}},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"ipt"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购物车编辑/u76.png"}},
{
          "id":"089d02b2940d486e928f360593cda5bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":265,
              "y":440},
            "size":{
              "width":21,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b90c1412f3ed4dcfb6783223f040e43f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":440},
                "size":{
                  "width":21,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 ipt = &quot;[[ipt-1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1fe8b98f1515492780975317902dd193"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[ipt-1]]",
                                "localVariables":{
                                  "ipt":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["1fe8b98f1515492780975317902dd193"]}]}},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"-",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"ipt"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购物车编辑/u78.png"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "8f49dc274f87465da2f695e12b9baccb":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "a642293fc8a3470c968001cac0e45e73":{
      "scriptId":"u5"},
    "f7875b98a06747bd9cc6406f30caadd2":{
      "scriptId":"u6"},
    "56c1e4250f9545428922cb755da6775b":{
      "scriptId":"u7"},
    "5dbf4ed3129946eabc0fa019235d7032":{
      "scriptId":"u8"},
    "9179775ceeeb417f8b3cea6f300fbf72":{
      "scriptId":"u9"},
    "44217a7f22c34e25884ff28e64f6b705":{
      "scriptId":"u10"},
    "8a85fce7150443a2bcc5152c280f26c7":{
      "scriptId":"u11"},
    "6c2f0f40ca3c48d4839bf43016a14394":{
      "scriptId":"u12"},
    "b8f5f9e39e3943ef82d1882d110065f4":{
      "scriptId":"u13"},
    "23e53e7e8f8a479e8123f3925de6542c":{
      "scriptId":"u14"},
    "fe4e2d4140834290843e4c5eb1cc1137":{
      "scriptId":"u15"},
    "c8830359a8f84c55814a951b7fdfa36a":{
      "scriptId":"u16"},
    "4194d7ecd67a47e6ae04a7281a665c87":{
      "scriptId":"u17"},
    "b81d81992e31488eb3bb4f6c788e4728":{
      "scriptId":"u18"},
    "599f58fd1140464a8451fa4bdb4c8080":{
      "scriptId":"u19"},
    "d16fa98bae2f4e90b20a2ff5769bef0b":{
      "scriptId":"u20"},
    "7131d0d466784beda603c44187350802":{
      "scriptId":"u21"},
    "fb27fb26043f4adc917fc6ece35f0c17":{
      "scriptId":"u22"},
    "a523b15a9d114d0fa17d17580f389528":{
      "scriptId":"u23"},
    "3bbf1c260d7e4b0db5726f0e6795d576":{
      "scriptId":"u24"},
    "996f1439bdfe47739ae91d88afb67a1f":{
      "scriptId":"u25"},
    "8c70e5fc7d8843fb80068b0ab0923b83":{
      "scriptId":"u26"},
    "3636cc09875f4e989bc38e0915b875d5":{
      "scriptId":"u27"},
    "fe7f3b528dcc4f0aab26e346e81379ce":{
      "scriptId":"u28"},
    "e07c5378ff74455698c77c49b6565600":{
      "scriptId":"u29"},
    "cbfd3e4cbfb84a38b515eabd0289c161":{
      "scriptId":"u30"},
    "cdce6a6e3b9f4c39beaa3391e899c6cc":{
      "scriptId":"u31"},
    "1f999e4e09c04afe90a6b42918a6bb9c":{
      "scriptId":"u32"},
    "fce809f94ae549e094aca19b9801b792":{
      "scriptId":"u33"},
    "660563979c024561ac5582c7bbb5ec30":{
      "scriptId":"u34"},
    "e6de0d86198e47618bada1627cf2768d":{
      "scriptId":"u35"},
    "ce4a3c97c320467285daeb94cb60ab32":{
      "scriptId":"u36"},
    "a1ae110fe66346fd8b1ed8f21ac48ac3":{
      "scriptId":"u37"},
    "d16ee97172b04fa0a35184969e78027f":{
      "scriptId":"u38"},
    "927b0c9a3ff543c39c515d600e4cd980":{
      "scriptId":"u39"},
    "75003af096f14d30b46d91b914c3860f":{
      "scriptId":"u40"},
    "8594fea1cdc1452192d90df5b0876b36":{
      "scriptId":"u41"},
    "5ca0742d92ff438ab39a4d961310ee18":{
      "scriptId":"u42"},
    "7b9afceeb3de4684b0308a919a6604e9":{
      "scriptId":"u43"},
    "d59f474eb032441982b8295679ae1910":{
      "scriptId":"u44"},
    "a63d2b69d24441b7910e808801c6b5ba":{
      "scriptId":"u45"},
    "0c212fa7cf6f4ad88824cf2536741eda":{
      "scriptId":"u46"},
    "5ae1b60b58cd4c949859e9bde6d9cf35":{
      "scriptId":"u47"},
    "f5089621d1a245279bc76a194eb9af21":{
      "scriptId":"u48"},
    "f7ddfc88be7c46cab81433110821a0b0":{
      "scriptId":"u49"},
    "715934886f884384b3052a43e86768f4":{
      "scriptId":"u50"},
    "c55a71175b334747ba46b5c0fb21c62b":{
      "scriptId":"u51"},
    "c5d922a9fc0245419e1ea6c387fe9004":{
      "scriptId":"u52"},
    "3abbfdc69b224184a74ff7082dfab818":{
      "scriptId":"u53"},
    "201d4c0bffec4408805cc55a03ed11d8":{
      "scriptId":"u54"},
    "71ca4478ec5d4dcf8d03c137b7571851":{
      "scriptId":"u55"},
    "a568eb08ca334d7189983c0c48be53c2":{
      "scriptId":"u56"},
    "92ada6ff264a4fd38603035115cd70ae":{
      "scriptId":"u57"},
    "2873f3f72bf145769a503c79621227c7":{
      "scriptId":"u58"},
    "9a253845468a47ed90cad4b1d2036006":{
      "scriptId":"u59"},
    "ef22c9c44efd42cead761636499640e9":{
      "scriptId":"u60"},
    "9f8d9b8855ab4993bbf19026f27245a7":{
      "scriptId":"u61"},
    "85b2547cf3c643e983a8ed5f638f05e2":{
      "scriptId":"u62"},
    "ec234abd41134eb1b811c0421c89ca05":{
      "scriptId":"u63"},
    "15c58daeab0644fab32275e7019cf4da":{
      "scriptId":"u64"},
    "e9bd964157a1437b8ca75433921bd936":{
      "scriptId":"u65"},
    "90395bb5966f434aaef64037fa3b2a3b":{
      "scriptId":"u66"},
    "dedfe26cd7ca4a9993f8be52d65f2403":{
      "scriptId":"u67"},
    "8a8fbe13496e4ca89e08793f2edea05f":{
      "scriptId":"u68"},
    "b0720e78a87e4af0978a0451ef9d3512":{
      "scriptId":"u69"},
    "4c922c184103442ca71bdf53047b4a35":{
      "scriptId":"u70"},
    "607ce2bc74804637b3f0651e5e603184":{
      "scriptId":"u71"},
    "44e3f76a05294e528f69235459414344":{
      "scriptId":"u72"},
    "834490b7a3a8459185b119b3737bdde2":{
      "scriptId":"u73"},
    "b8e6a1f7280e409ea97675249ee3e12f":{
      "scriptId":"u74"},
    "4847166113e7420d99bbac893229735a":{
      "scriptId":"u75"},
    "592e9dde27064bc5a4ca7070740acd9a":{
      "scriptId":"u76"},
    "e6883df0f36d4c4489cc6f3622f3ed53":{
      "scriptId":"u77"},
    "a41686710a274542ac02860816c2fd69":{
      "scriptId":"u78"},
    "2a0eb4c1ed964532b4325be695c90aca":{
      "scriptId":"u79"},
    "daf99a770b0e4b7b8e7813ea907d5b94":{
      "scriptId":"u80"},
    "05de20da8e2d43e8a8c78edf8022d26b":{
      "scriptId":"u81"},
    "439b4253ae3f4bc2b99eb4c6c1889798":{
      "scriptId":"u82"},
    "e54ac85bab964956a58566ed2cadaca5":{
      "scriptId":"u83"},
    "4820268454a8495093c1069847070c15":{
      "scriptId":"u84"},
    "a83631c9575a4fa1a2be4835b0a00218":{
      "scriptId":"u85"},
    "700c97857cf5493796a3359c15a93b53":{
      "scriptId":"u86"},
    "c4c0b2416dbc4dd588966c9e027014d0":{
      "scriptId":"u87"},
    "1fe8b98f1515492780975317902dd193":{
      "scriptId":"u88"},
    "f85247f07d09400a92c4da87c74c942a":{
      "scriptId":"u89"},
    "307c37f2d8444a0084136c711ed7a763":{
      "scriptId":"u90"},
    "089d02b2940d486e928f360593cda5bf":{
      "scriptId":"u91"},
    "b90c1412f3ed4dcfb6783223f040e43f":{
      "scriptId":"u92"}}});