$axure.loadCurrentPage({
  "url":"商品详情.html",
  "generationDate":new Date(1420531293702.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7620d1de50204d25833348a359f218bb",
    "type":"Axure:Page",
    "name":"商品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3afa16ce1e2d4688954346594eaf88e1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"c317025246f24250a302b038f60e5b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4d6f971fbc454296a72c8542bf9509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"1c0d53c986ed4d22ac8e83463b6ac18b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f2a78a138a346729ccbecd8384e696f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品列表",
                      "target":{
                        "targetType":"page",
                        "url":"商品列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"12a9bed7bfaf49f88d54d1984daf3eba",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":177},
            "size":{
              "width":340,
              "height":503}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43f843965f15483e9f322929cb0050f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"007b04d4c77e401a961ca0ae0662cc43",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ed56147287a41c896defa173e8352fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u10.jpg"}},
{
                  "id":"32c40bcf78d34ca58f9799bc3b52c47a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.4",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":265,
                      "y":120},
                    "size":{
                      "width":34,
                      "height":26},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41c4c28545664dd8b55541756f96bb6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.4",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":265,
                          "y":120},
                        "size":{
                          "width":34,
                          "height":26},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u12.png"}},
{
                  "id":"c9a3c026df1a4a0b83993c4dac5cbb77",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":13,
                      "y":171},
                    "size":{
                      "width":298,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5e8d934d6e5473885a575c9c1301b47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":13,
                          "y":171},
                        "size":{
                          "width":298,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2e7648ab26004a489c6d9cec6b5ee1e4",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":220},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"936c552dbe6a45d7a7acbf336931c8dc",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":200},
                    "size":{
                      "width":78,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44518f31678846e88a7c95fff43b65e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":200},
                        "size":{
                          "width":78,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺列表/u17.png"}},
{
                  "id":"47c1ca9c57284d4d9e0e19ed82fff0a9",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":13,
                      "y":242},
                    "size":{
                      "width":107,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab0b792b80544ef4ba8904062eebda02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":13,
                          "y":242},
                        "size":{
                          "width":107,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd4fb297ad044a97a1c666d75b2d7a6f",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":199},
                    "size":{
                      "width":53,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8700c49d9b5547d8a90bd7810881f319",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":199},
                        "size":{
                          "width":53,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"92f4acc884054aff913a12a6dace6a92",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":213,
                      "y":232},
                    "size":{
                      "width":101,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea0fc49c4d384df9bc2653346c7d54b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":213,
                          "y":232},
                        "size":{
                          "width":101,
                          "height":38},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 选择尺码颜色",
                              "target":{
                                "targetType":"page",
                                "url":"选择尺码颜色.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品详情/u23.png"}},
{
                  "id":"df758b196865487ca706510e59ecee8d",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":272},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/新闻/u42_line.png"}},
{
                  "id":"abe0c036e4ba4093b6a9fe68de010902",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1300fc763594b5f8dcc209eee035ac9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u26.jpg"}},
{
                  "id":"1deec24420da4774b4f4a343f593900a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":1,
                      "y":288},
                    "size":{
                      "width":320,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fb1090cb4a648bbb117044af7b00dd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":1,
                          "y":288},
                        "size":{
                          "width":320,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 选择尺码颜色",
                              "target":{
                                "targetType":"page",
                                "url":"选择尺码颜色.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品详情/u28.png"}},
{
                  "id":"ef1e503c4a77402d93f279741daf8703",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":294,
                      "y":298},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c2e2695baee46b19dea6a372328e816",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":294,
                          "y":298},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u30.png"}},
{
                  "id":"1293a3ed0d1b4430aeaa5960ac70ab8a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":13,
                      "y":300},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75babadb3ca04fb9838114f05d27530f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":13,
                          "y":300},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d74ee0f8f217491c8502d7aba46f7640",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":360},
                    "size":{
                      "width":320,
                      "height":365}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d981df84139a4c2baf9466b8cc1d5fa2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":360},
                        "size":{
                          "width":320,
                          "height":365}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u34.jpg"}},
{
                  "id":"3a5e6641fea24fb386842106267b8096",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":13,
                      "y":337},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"812a4d6fdf80473ebcb1a0ebce3a9a99",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":13,
                          "y":337},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4ae474750a7a4391a91176e756563914",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":129,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66e7c8398fd646d09d60bc162682f739",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":129,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"7afdc901c32e492b905ece31eb5a530e",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":153,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe8c9aea2fd84339b963306f667d0134",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":153,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"48b93d57196041289bb823dbe976ffa1",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":177,
                      "y":138},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a7aa2a00ce34d9fa3b9e20412c8a6e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":177,
                          "y":138},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"d68f681a852a483ab36c6dd00b2922ae",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9966},
                    "location":{
                      "x":105,
                      "y":232},
                    "size":{
                      "width":101,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76e6f519b1044636a21d697a97fab5d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9966},
                        "location":{
                          "x":105,
                          "y":232},
                        "size":{
                          "width":101,
                          "height":38},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 购物车",
                              "target":{
                                "targetType":"page",
                                "url":"购物车.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品详情/u44.png"}},
{
                  "id":"bbf59721970b419da3e1f9e38eff436a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":736},
                    "size":{
                      "width":320,
                      "height":31},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97659ddfdbc044d08552cadd533297e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":736},
                        "size":{
                          "width":320,
                          "height":31},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u46.png"}},
{
                  "id":"e2bf27da6af9417b9de66728accd8c5a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":15,
                      "y":744},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4eeb7a7dadb14c2f8f71b7fcffd9f4b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":15,
                          "y":744},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e90276b57c0e4d768f15a649e965b33c",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":779},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"354aff6f1e474cc1b52cf8aad55382c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":779},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u50.png"}},
{
                  "id":"5c791844d17c47bc9b498e736ad4789d",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":779},
                    "size":{
                      "width":80,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"908d27d2225d48f498fb51c80ee824ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":779},
                        "size":{
                          "width":80,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d761fbbc5f47426d9c3c5fbe0e6ca7da",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":805},
                    "size":{
                      "width":226,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79a1fca364834fdfbc1695b5f79e50dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":805},
                        "size":{
                          "width":226,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d5b92245bd1b4a21af8ab5ceba49bcd6",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":211,
                      "y":779},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed9912dc4a524405aea1708cc14ababe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":211,
                          "y":779},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa9257df18e448deaf5c076abb866a5e",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":864},
                    "size":{
                      "width":302,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u43_line.png"}},
{
                  "id":"20defa71135746efb42e7f9c9a61e276",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF9933,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":881},
                    "size":{
                      "width":80,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af3ca526aa07423c851b9de569f7a6c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF9933,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":881},
                        "size":{
                          "width":80,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f360ebdb325b42d6a17c648390102115",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":908},
                    "size":{
                      "width":239,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a26117b3612d425282c75a69d27f6a6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":908},
                        "size":{
                          "width":239,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d1061eae2d4b4f19a00428b60cb3050a",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":210,
                      "y":881},
                    "size":{
                      "width":108,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39ae928534044ab8818affd86ba21294",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":210,
                          "y":881},
                        "size":{
                          "width":108,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3fe496c5271f4134ac8ed4dd88a3f6ca",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":972},
                    "size":{
                      "width":302,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u43_line.png"}},
{
                  "id":"a24a3992c464494eb3782f25c63561ae",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":779},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a756d9b77d5446c8882b802f027d274",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":779},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u66.png"}},
{
                  "id":"728a43cc0fed4eb0b47d4a33214cf1fd",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":881},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fb7dd05380340fc8fc3f11635011adf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":881},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u68.png"}},
{
                  "id":"2863018e7b204c7caa33d65417e7d490",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":294,
                      "y":742},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80e95ae681974386ab7d273016ea08b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":294,
                          "y":742},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u30.png"}},
{
                  "id":"f31d57a897164db9b9973dc6b7447c7f",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":278,
                      "y":744},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24049ebf417f4c84a93588d5aa74fe2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":278,
                          "y":744},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"51e3ddfed254411592c179a411797e34",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":827},
                    "size":{
                      "width":242,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5ee3815f069485b943fa6420a5e8100",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":827},
                        "size":{
                          "width":242,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd1c312ac79c42abbb765b46e31e171e",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":68,
                      "y":931},
                    "size":{
                      "width":242,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa212635236c4cc0928a8955cc90883d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":68,
                          "y":931},
                        "size":{
                          "width":242,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"07c45d4f09a6429196efd8403d05621b",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":742},
                    "size":{
                      "width":316,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 评论列表",
                              "target":{
                                "targetType":"page",
                                "url":"评论列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"39277184d9aa4083a25a217e9a92696e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":27,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db6f037c8cb4a18b58620c9813522e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":27,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u20.png"}},
{
          "id":"c67496075f004aff865791355050173b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":144},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028fa829ec9d4101b67e4b3b89023315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":144},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 fenxiang 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u18.png"}},
{
          "id":"4cbf4f753cc242e9a322f99681861228",
          "label":"fenxiang",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":568},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ecbcb5d2268240b7a5a907e339ad6915",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4040fa465f8742558d24b3a26fee4c82",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":320,
                      "height":545},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ea0c13145f24082b9e863c59862d824",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":320,
                          "height":545},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u58.png"}},
{
                  "id":"6a0edb0ca1cd4d6ea80aa0c7e5597c23",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":304},
                    "size":{
                      "width":321,
                      "height":265},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a0aa6f46ff641d4a9c5254a90af1917",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":304},
                        "size":{
                          "width":321,
                          "height":265},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u60.png"}},
{
                  "id":"4e5a698539404713b8fe5dd2e6c7cb50",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":359},
                    "size":{
                      "width":320,
                      "height":4},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acf07dc8f6824d43bb07754cc070b79b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":359},
                        "size":{
                          "width":320,
                          "height":4},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u62.png"}},
{
                  "id":"5695acb419634a12947a39bcc21f0a20",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":144,
                      "y":322},
                    "size":{
                      "width":39,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54ce1ddc5ef1426cb285416850325c91",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":144,
                          "y":322},
                        "size":{
                          "width":39,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f435b98abc1b4c69b89629814b872fc2",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa83a050ea074ef284da2968cfc47cc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":20,
                          "y":507},
                        "size":{
                          "width":280,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u66.png"}},
{
                  "id":"17aab75fd845444e8ef608854af9e54b",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 fenxiang 向下滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"77f1215fb7cd449c96684d8675ed9310",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ffe5ce6f3b941918bc094c240c84dee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u69.png"}},
{
                  "id":"90380fb2d93f4965962ad07679f1b6cd",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":192,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c921e53aa593403b88406b2ea36027b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":192,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u71.png"}},
{
                  "id":"32f6f1b807574e4e88d1105e653f50bc",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":48,
                      "y":471},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a72de691eb174be380904e67905f3347",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":48,
                          "y":471},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f415bfb1ec2426592c5312cb93e8ac8",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":194,
                      "y":471},
                    "size":{
                      "width":83,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f54316d3784544889116cbdd7b5555d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":194,
                          "y":471},
                        "size":{
                          "width":83,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1d171c90045847be906014fbf216ee7c",
          "label":"cg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":118,
              "y":380},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eb7a97d572f54721a9a6c05ce7f91a16",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b6171c19ccaf4eeca9234185ead4d9b8",
                  "label":"cg",
                  "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":150,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeadfb91863141f6b16bd2b3697ca1d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":150,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/cg_u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "3afa16ce1e2d4688954346594eaf88e1":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "c317025246f24250a302b038f60e5b27":{
      "scriptId":"u5"},
    "1f4d6f971fbc454296a72c8542bf9509":{
      "scriptId":"u6"},
    "1c0d53c986ed4d22ac8e83463b6ac18b":{
      "scriptId":"u7"},
    "3f2a78a138a346729ccbecd8384e696f":{
      "scriptId":"u8"},
    "12a9bed7bfaf49f88d54d1984daf3eba":{
      "scriptId":"u9"},
    "007b04d4c77e401a961ca0ae0662cc43":{
      "scriptId":"u10"},
    "2ed56147287a41c896defa173e8352fe":{
      "scriptId":"u11"},
    "32c40bcf78d34ca58f9799bc3b52c47a":{
      "scriptId":"u12"},
    "41c4c28545664dd8b55541756f96bb6b":{
      "scriptId":"u13"},
    "c9a3c026df1a4a0b83993c4dac5cbb77":{
      "scriptId":"u14"},
    "d5e8d934d6e5473885a575c9c1301b47":{
      "scriptId":"u15"},
    "2e7648ab26004a489c6d9cec6b5ee1e4":{
      "scriptId":"u16"},
    "936c552dbe6a45d7a7acbf336931c8dc":{
      "scriptId":"u17"},
    "44518f31678846e88a7c95fff43b65e8":{
      "scriptId":"u18"},
    "47c1ca9c57284d4d9e0e19ed82fff0a9":{
      "scriptId":"u19"},
    "ab0b792b80544ef4ba8904062eebda02":{
      "scriptId":"u20"},
    "bd4fb297ad044a97a1c666d75b2d7a6f":{
      "scriptId":"u21"},
    "8700c49d9b5547d8a90bd7810881f319":{
      "scriptId":"u22"},
    "92f4acc884054aff913a12a6dace6a92":{
      "scriptId":"u23"},
    "ea0fc49c4d384df9bc2653346c7d54b2":{
      "scriptId":"u24"},
    "df758b196865487ca706510e59ecee8d":{
      "scriptId":"u25"},
    "abe0c036e4ba4093b6a9fe68de010902":{
      "scriptId":"u26"},
    "b1300fc763594b5f8dcc209eee035ac9":{
      "scriptId":"u27"},
    "1deec24420da4774b4f4a343f593900a":{
      "scriptId":"u28"},
    "1fb1090cb4a648bbb117044af7b00dd8":{
      "scriptId":"u29"},
    "ef1e503c4a77402d93f279741daf8703":{
      "scriptId":"u30"},
    "3c2e2695baee46b19dea6a372328e816":{
      "scriptId":"u31"},
    "1293a3ed0d1b4430aeaa5960ac70ab8a":{
      "scriptId":"u32"},
    "75babadb3ca04fb9838114f05d27530f":{
      "scriptId":"u33"},
    "d74ee0f8f217491c8502d7aba46f7640":{
      "scriptId":"u34"},
    "d981df84139a4c2baf9466b8cc1d5fa2":{
      "scriptId":"u35"},
    "3a5e6641fea24fb386842106267b8096":{
      "scriptId":"u36"},
    "812a4d6fdf80473ebcb1a0ebce3a9a99":{
      "scriptId":"u37"},
    "4ae474750a7a4391a91176e756563914":{
      "scriptId":"u38"},
    "66e7c8398fd646d09d60bc162682f739":{
      "scriptId":"u39"},
    "7afdc901c32e492b905ece31eb5a530e":{
      "scriptId":"u40"},
    "fe8c9aea2fd84339b963306f667d0134":{
      "scriptId":"u41"},
    "48b93d57196041289bb823dbe976ffa1":{
      "scriptId":"u42"},
    "7a7aa2a00ce34d9fa3b9e20412c8a6e4":{
      "scriptId":"u43"},
    "d68f681a852a483ab36c6dd00b2922ae":{
      "scriptId":"u44"},
    "76e6f519b1044636a21d697a97fab5d0":{
      "scriptId":"u45"},
    "bbf59721970b419da3e1f9e38eff436a":{
      "scriptId":"u46"},
    "97659ddfdbc044d08552cadd533297e3":{
      "scriptId":"u47"},
    "e2bf27da6af9417b9de66728accd8c5a":{
      "scriptId":"u48"},
    "4eeb7a7dadb14c2f8f71b7fcffd9f4b2":{
      "scriptId":"u49"},
    "e90276b57c0e4d768f15a649e965b33c":{
      "scriptId":"u50"},
    "354aff6f1e474cc1b52cf8aad55382c5":{
      "scriptId":"u51"},
    "5c791844d17c47bc9b498e736ad4789d":{
      "scriptId":"u52"},
    "908d27d2225d48f498fb51c80ee824ef":{
      "scriptId":"u53"},
    "d761fbbc5f47426d9c3c5fbe0e6ca7da":{
      "scriptId":"u54"},
    "79a1fca364834fdfbc1695b5f79e50dd":{
      "scriptId":"u55"},
    "d5b92245bd1b4a21af8ab5ceba49bcd6":{
      "scriptId":"u56"},
    "ed9912dc4a524405aea1708cc14ababe":{
      "scriptId":"u57"},
    "aa9257df18e448deaf5c076abb866a5e":{
      "scriptId":"u58"},
    "20defa71135746efb42e7f9c9a61e276":{
      "scriptId":"u59"},
    "af3ca526aa07423c851b9de569f7a6c5":{
      "scriptId":"u60"},
    "f360ebdb325b42d6a17c648390102115":{
      "scriptId":"u61"},
    "a26117b3612d425282c75a69d27f6a6b":{
      "scriptId":"u62"},
    "d1061eae2d4b4f19a00428b60cb3050a":{
      "scriptId":"u63"},
    "39ae928534044ab8818affd86ba21294":{
      "scriptId":"u64"},
    "3fe496c5271f4134ac8ed4dd88a3f6ca":{
      "scriptId":"u65"},
    "a24a3992c464494eb3782f25c63561ae":{
      "scriptId":"u66"},
    "7a756d9b77d5446c8882b802f027d274":{
      "scriptId":"u67"},
    "728a43cc0fed4eb0b47d4a33214cf1fd":{
      "scriptId":"u68"},
    "9fb7dd05380340fc8fc3f11635011adf":{
      "scriptId":"u69"},
    "2863018e7b204c7caa33d65417e7d490":{
      "scriptId":"u70"},
    "80e95ae681974386ab7d273016ea08b1":{
      "scriptId":"u71"},
    "f31d57a897164db9b9973dc6b7447c7f":{
      "scriptId":"u72"},
    "24049ebf417f4c84a93588d5aa74fe2b":{
      "scriptId":"u73"},
    "51e3ddfed254411592c179a411797e34":{
      "scriptId":"u74"},
    "c5ee3815f069485b943fa6420a5e8100":{
      "scriptId":"u75"},
    "bd1c312ac79c42abbb765b46e31e171e":{
      "scriptId":"u76"},
    "fa212635236c4cc0928a8955cc90883d":{
      "scriptId":"u77"},
    "07c45d4f09a6429196efd8403d05621b":{
      "scriptId":"u78"},
    "39277184d9aa4083a25a217e9a92696e":{
      "scriptId":"u79"},
    "4db6f037c8cb4a18b58620c9813522e0":{
      "scriptId":"u80"},
    "c67496075f004aff865791355050173b":{
      "scriptId":"u81"},
    "028fa829ec9d4101b67e4b3b89023315":{
      "scriptId":"u82"},
    "4cbf4f753cc242e9a322f99681861228":{
      "scriptId":"u83"},
    "4040fa465f8742558d24b3a26fee4c82":{
      "scriptId":"u84"},
    "3ea0c13145f24082b9e863c59862d824":{
      "scriptId":"u85"},
    "6a0edb0ca1cd4d6ea80aa0c7e5597c23":{
      "scriptId":"u86"},
    "2a0aa6f46ff641d4a9c5254a90af1917":{
      "scriptId":"u87"},
    "4e5a698539404713b8fe5dd2e6c7cb50":{
      "scriptId":"u88"},
    "acf07dc8f6824d43bb07754cc070b79b":{
      "scriptId":"u89"},
    "5695acb419634a12947a39bcc21f0a20":{
      "scriptId":"u90"},
    "54ce1ddc5ef1426cb285416850325c91":{
      "scriptId":"u91"},
    "f435b98abc1b4c69b89629814b872fc2":{
      "scriptId":"u92"},
    "fa83a050ea074ef284da2968cfc47cc8":{
      "scriptId":"u93"},
    "17aab75fd845444e8ef608854af9e54b":{
      "scriptId":"u94"},
    "77f1215fb7cd449c96684d8675ed9310":{
      "scriptId":"u95"},
    "7ffe5ce6f3b941918bc094c240c84dee":{
      "scriptId":"u96"},
    "90380fb2d93f4965962ad07679f1b6cd":{
      "scriptId":"u97"},
    "c921e53aa593403b88406b2ea36027b6":{
      "scriptId":"u98"},
    "32f6f1b807574e4e88d1105e653f50bc":{
      "scriptId":"u99"},
    "a72de691eb174be380904e67905f3347":{
      "scriptId":"u100"},
    "0f415bfb1ec2426592c5312cb93e8ac8":{
      "scriptId":"u101"},
    "f54316d3784544889116cbdd7b5555d7":{
      "scriptId":"u102"},
    "1d171c90045847be906014fbf216ee7c":{
      "scriptId":"u103"},
    "b6171c19ccaf4eeca9234185ead4d9b8":{
      "scriptId":"u104"},
    "eeadfb91863141f6b16bd2b3697ca1d1":{
      "scriptId":"u105"}}});