$axure.loadCurrentPage({
  "url":"我的.html",
  "generationDate":new Date(1420531295848.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"001f14dd5d684ebb9227434e95ea60c4",
    "type":"Axure:Page",
    "name":"我的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7a27f51bebe44550b9763fb0bc7cff91",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"9e125fae178d4c03a9ed3cf09bdb6731",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":558},
            "size":{
              "width":321,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a872172be648d2af2b45574429a4fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":558},
                "size":{
                  "width":321,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u5.png"}},
{
          "id":"229bbe62afbe4b3e8cac2f0201160b63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f238483f317241878f08e1fcea063cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"7428958b6ef24c85b1e47ebc8408bc1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":498},
            "size":{
              "width":321,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc6376c181f4f1c968e3a2cd52edcc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":498},
                "size":{
                  "width":321,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u9.png"}},
{
          "id":"8575357a52e54e839f872d9b9d6cba5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":32,
              "y":404},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e121da9dade4f39b70ad56229b8a9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":32,
                  "y":404},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/杂志/u28.png"}},
{
          "id":"b7ab80d8743346439e4e18a603d56f0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":417},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6f1eb4cc8994aa09e7eedfc2bdffb2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":417},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9111b33b2cf4487b1d72dcdd10c5207",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":417},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879c74d08c53477fae271645a27fc0f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":417},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"a38875e238764a1e885eace9909d7086",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":415},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee5164d9271041388eaa8aa914ba8b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":415},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u17.png"}},
{
          "id":"020879f43ba54e6c84a95ed685796726",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":32,
              "y":450},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a6a75b2823944ff867e2c87922ce4c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":32,
                  "y":450},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/杂志/u28.png"}},
{
          "id":"7557cc96319c4ce9ae0262c16d705ba1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":463},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ec6c1b675b472b92bc842dd97df4f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":463},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d5e037069aa4f248c33dfe330b20ae1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":463},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ea8890fa734fccbe315d45fca37c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":463},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"20c788752ae748418bbb59059e51cd90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":461},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd329382ffc4ed19af112e02b1d1660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":461},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u17.png"}},
{
          "id":"dcd0df54a33044c49823a259cecd37a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":33,
              "y":511},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b49704c6ae2404eb3904c9bb75418c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":33,
                  "y":511},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/杂志/u28.png"}},
{
          "id":"56c36aa029be45478b945bcdde492b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":89,
              "y":524},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0251f3e8fc5415d87dfdde987c96236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":524},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36b39bdb8d514837a5ef5e224b3c4a56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":524},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbe74714ef94b0587d2b527a8dd7754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":524},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"2f83cae96c3c405cb7d3f606b6093233",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":522},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b2a2836d484f69b122c9ed846fa629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":522},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u17.png"}},
{
          "id":"977b3dbf758b4977bbff878ee92b7c75",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":506},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"7674a285109c48c2832bba2ecd4d87d5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":552},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"23388983362f43a3aceb2184b2bec45a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":320,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17298bc4de294940b4f919f2e4505d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":320,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的资料",
                      "target":{
                        "targetType":"page",
                        "url":"我的资料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的/u37.png"}},
{
          "id":"9ae85549f2874ed38b3b8aa6b20f82ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":49,
              "y":194},
            "size":{
              "width":83,
              "height":83},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad23bcfd5c74946961ecaa282cec07a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":49,
                  "y":194},
                "size":{
                  "width":83,
                  "height":83},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u39.png"}},
{
          "id":"403afc49304546d5819d1b6a03850fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":32,
              "y":359},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14b73c1ad892459bb79647afd4c73ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":32,
                  "y":359},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/杂志/u28.png"}},
{
          "id":"f5593e79da0b4a5888912aad1db0c391",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":372},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b7a7c951e57496b9ed8b813ba398a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":372},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e27df7c0d7b743f897951ab5004c0c7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":372},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241b47b6b397497a848ea695082d42d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":372},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"80f2591877e145da8a96b720d80fcb28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":370},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b847a916d46d44cb90621671c1f73099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":370},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u17.png"}},
{
          "id":"a64f7d7bd8f04cef8e121335139eda82",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":400},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"ea94187dac0b434fa77c2c44ce1d39bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":54,
              "y":198},
            "size":{
              "width":74,
              "height":74},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ea415891044170adf7e4e3e5f3da26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":54,
                  "y":198},
                "size":{
                  "width":74,
                  "height":74},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u50.png"}},
{
          "id":"e4a9edea4d4c4adab813bbf63c7f75b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":150,
              "y":223},
            "size":{
              "width":55,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2ca507d5cb4ca2bf76483f16a7ddd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":223},
                "size":{
                  "width":55,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde8cc9f8116487c9544896619d553f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":32,
              "y":313},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd9a3ab78ba44e46af166d5621cbd8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":32,
                  "y":313},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/杂志/u28.png"}},
{
          "id":"d1e10c8390254c1299cb935bac897c16",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":326},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa6fd02f0254823925bf698c4237702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":326},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c9f33d02c734e4c89595ad754bc9f21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":326},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02056f9500c54b29a38b61ac84a23fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":326},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"910fb91247344a7ea72bf95bf8e7e191",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":324},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2918c43485425a80750ff3331dce75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":324},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u17.png"}},
{
          "id":"519911a10a5644adb9a9545e58d78b03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":354},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"d2c3095ef4e44f68ba36f2f5001f61d2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":313},
            "size":{
              "width":320,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2e7381441a884b889955522520793f9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":445},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"f595d4ae58be42c5a4f452158204a76a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":492},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"bb428514fdb842a69d1a1c0c187d89d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":44,
              "y":571},
            "size":{
              "width":296,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7fcddbb25054b2cbfc067bb0d67c4d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lantinghei SC Regular', 'Lantinghei SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":44,
                  "y":571},
                "size":{
                  "width":296,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u36.png"}},
{
          "id":"914d11ad18e8426182106adb3f40d051",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":225},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02cf1f0a0f4349c18348f38b562d591f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":225},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u30.png"}},
{
          "id":"ad7281cdad2a4d8f8fe437bd1c0edda1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":145},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fcf3bace0964574acd5dc60e984d5c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":145},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的/u70.png"}},
{
          "id":"9718bc525acf48e6b9aa0bc34a3fdf6b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":359},
            "size":{
              "width":320,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的发布",
                      "target":{
                        "targetType":"page",
                        "url":"我的发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"79c516661e60482fa61c19416dd7cf2b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":406},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏-资讯",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏-资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6f4d158391124545a1b84967ffa03d4d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":452},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评论",
                      "target":{
                        "targetType":"page",
                        "url":"我的评论.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b8ba02d135db479f92bcb09e3bb0922a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":512},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账户信息",
                      "target":{
                        "targetType":"page",
                        "url":"账户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7ec426a1ff114a7c8dd846ef898f82dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":308},
            "size":{
              "width":290,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/杂志/u33_line.png"}},
{
          "id":"97c4c17015124ba0b5850d796190c015",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":32,
              "y":295},
            "size":{
              "width":321,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ddacb1af5e14f1fbcd969abd2d1f0ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":32,
                  "y":295},
                "size":{
                  "width":321,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u9.png"}},
{
          "id":"598721cd44cd4775964cdda70efe0862",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "location":{
              "x":32,
              "y":638},
            "size":{
              "width":65,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d9f89bb3d384bb0be2bad11ce7a4ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "location":{
                  "x":32,
                  "y":638},
                "size":{
                  "width":65,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u76.png",
            "selected~":"images/资讯/u74_selected.png"}},
{
          "id":"557b30491042478bb384009f9223cf07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "location":{
              "x":160,
              "y":638},
            "size":{
              "width":65,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b954e356ed144b98917af4c27c473d3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "location":{
                  "x":160,
                  "y":638},
                "size":{
                  "width":65,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u76.png",
            "selected~":"images/资讯/u74_selected.png"}},
{
          "id":"62ec7beb52964172b03fbabad947f19b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "location":{
              "x":224,
              "y":638},
            "size":{
              "width":65,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed1fa9de4c40431b952e4352c5c0a033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "location":{
                  "x":224,
                  "y":638},
                "size":{
                  "width":65,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u76.png",
            "selected~":"images/资讯/u74_selected.png"}},
{
          "id":"1aecf8b8399a4d8682baa05ebe74d3cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "location":{
              "x":96,
              "y":638},
            "size":{
              "width":65,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ff5ddbbab745a7a665d2befdb6ecaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "location":{
                  "x":96,
                  "y":638},
                "size":{
                  "width":65,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u76.png",
            "selected~":"images/资讯/u74_selected.png"}},
{
          "id":"46eba46e1c1c4e9aace1ed209b4eb5dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":288,
              "y":638},
            "size":{
              "width":65,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53484e2e8534a3e8618930bd4a6adb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":288,
                  "y":638},
                "size":{
                  "width":65,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u74.png",
            "selected~":"images/资讯/u74_selected.png"}},
{
          "id":"c2dd5f2a0e1e4f84a744c299ccbe6acf",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":638},
            "size":{
              "width":63,
              "height":48}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 资讯",
                      "target":{
                        "targetType":"page",
                        "url":"资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f610f00b694e49a0b59f7186bdbfcab5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":638},
            "size":{
              "width":63,
              "height":48}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 杂志",
                      "target":{
                        "targetType":"page",
                        "url":"杂志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"28c4c5280a7a40d8bcb343ad31ded29c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":638},
            "size":{
              "width":63,
              "height":48}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商铺",
                      "target":{
                        "targetType":"page",
                        "url":"商铺.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f227feee580c4c9e98a5d31bd2760bdf",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":638},
            "size":{
              "width":63,
              "height":48}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 团购",
                      "target":{
                        "targetType":"page",
                        "url":"团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "7a27f51bebe44550b9763fb0bc7cff91":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "9e125fae178d4c03a9ed3cf09bdb6731":{
      "scriptId":"u5"},
    "c6a872172be648d2af2b45574429a4fa":{
      "scriptId":"u6"},
    "229bbe62afbe4b3e8cac2f0201160b63":{
      "scriptId":"u7"},
    "f238483f317241878f08e1fcea063cf2":{
      "scriptId":"u8"},
    "7428958b6ef24c85b1e47ebc8408bc1d":{
      "scriptId":"u9"},
    "adc6376c181f4f1c968e3a2cd52edcc5":{
      "scriptId":"u10"},
    "8575357a52e54e839f872d9b9d6cba5f":{
      "scriptId":"u11"},
    "8e121da9dade4f39b70ad56229b8a9ca":{
      "scriptId":"u12"},
    "b7ab80d8743346439e4e18a603d56f0b":{
      "scriptId":"u13"},
    "c6f1eb4cc8994aa09e7eedfc2bdffb2c":{
      "scriptId":"u14"},
    "f9111b33b2cf4487b1d72dcdd10c5207":{
      "scriptId":"u15"},
    "879c74d08c53477fae271645a27fc0f6":{
      "scriptId":"u16"},
    "a38875e238764a1e885eace9909d7086":{
      "scriptId":"u17"},
    "ee5164d9271041388eaa8aa914ba8b1c":{
      "scriptId":"u18"},
    "020879f43ba54e6c84a95ed685796726":{
      "scriptId":"u19"},
    "3a6a75b2823944ff867e2c87922ce4c6":{
      "scriptId":"u20"},
    "7557cc96319c4ce9ae0262c16d705ba1":{
      "scriptId":"u21"},
    "17ec6c1b675b472b92bc842dd97df4f8":{
      "scriptId":"u22"},
    "2d5e037069aa4f248c33dfe330b20ae1":{
      "scriptId":"u23"},
    "37ea8890fa734fccbe315d45fca37c8c":{
      "scriptId":"u24"},
    "20c788752ae748418bbb59059e51cd90":{
      "scriptId":"u25"},
    "8fd329382ffc4ed19af112e02b1d1660":{
      "scriptId":"u26"},
    "dcd0df54a33044c49823a259cecd37a0":{
      "scriptId":"u27"},
    "5b49704c6ae2404eb3904c9bb75418c0":{
      "scriptId":"u28"},
    "56c36aa029be45478b945bcdde492b3b":{
      "scriptId":"u29"},
    "e0251f3e8fc5415d87dfdde987c96236":{
      "scriptId":"u30"},
    "36b39bdb8d514837a5ef5e224b3c4a56":{
      "scriptId":"u31"},
    "bcbe74714ef94b0587d2b527a8dd7754":{
      "scriptId":"u32"},
    "2f83cae96c3c405cb7d3f606b6093233":{
      "scriptId":"u33"},
    "a6b2a2836d484f69b122c9ed846fa629":{
      "scriptId":"u34"},
    "977b3dbf758b4977bbff878ee92b7c75":{
      "scriptId":"u35"},
    "7674a285109c48c2832bba2ecd4d87d5":{
      "scriptId":"u36"},
    "23388983362f43a3aceb2184b2bec45a":{
      "scriptId":"u37"},
    "17298bc4de294940b4f919f2e4505d96":{
      "scriptId":"u38"},
    "9ae85549f2874ed38b3b8aa6b20f82ab":{
      "scriptId":"u39"},
    "3ad23bcfd5c74946961ecaa282cec07a":{
      "scriptId":"u40"},
    "403afc49304546d5819d1b6a03850fc2":{
      "scriptId":"u41"},
    "14b73c1ad892459bb79647afd4c73ecf":{
      "scriptId":"u42"},
    "f5593e79da0b4a5888912aad1db0c391":{
      "scriptId":"u43"},
    "0b7a7c951e57496b9ed8b813ba398a8b":{
      "scriptId":"u44"},
    "e27df7c0d7b743f897951ab5004c0c7f":{
      "scriptId":"u45"},
    "241b47b6b397497a848ea695082d42d6":{
      "scriptId":"u46"},
    "80f2591877e145da8a96b720d80fcb28":{
      "scriptId":"u47"},
    "b847a916d46d44cb90621671c1f73099":{
      "scriptId":"u48"},
    "a64f7d7bd8f04cef8e121335139eda82":{
      "scriptId":"u49"},
    "ea94187dac0b434fa77c2c44ce1d39bf":{
      "scriptId":"u50"},
    "d5ea415891044170adf7e4e3e5f3da26":{
      "scriptId":"u51"},
    "e4a9edea4d4c4adab813bbf63c7f75b4":{
      "scriptId":"u52"},
    "6b2ca507d5cb4ca2bf76483f16a7ddd9":{
      "scriptId":"u53"},
    "bde8cc9f8116487c9544896619d553f5":{
      "scriptId":"u54"},
    "dd9a3ab78ba44e46af166d5621cbd8b4":{
      "scriptId":"u55"},
    "d1e10c8390254c1299cb935bac897c16":{
      "scriptId":"u56"},
    "aaa6fd02f0254823925bf698c4237702":{
      "scriptId":"u57"},
    "0c9f33d02c734e4c89595ad754bc9f21":{
      "scriptId":"u58"},
    "02056f9500c54b29a38b61ac84a23fa1":{
      "scriptId":"u59"},
    "910fb91247344a7ea72bf95bf8e7e191":{
      "scriptId":"u60"},
    "5c2918c43485425a80750ff3331dce75":{
      "scriptId":"u61"},
    "519911a10a5644adb9a9545e58d78b03":{
      "scriptId":"u62"},
    "d2c3095ef4e44f68ba36f2f5001f61d2":{
      "scriptId":"u63"},
    "2e7381441a884b889955522520793f9b":{
      "scriptId":"u64"},
    "f595d4ae58be42c5a4f452158204a76a":{
      "scriptId":"u65"},
    "bb428514fdb842a69d1a1c0c187d89d2":{
      "scriptId":"u66"},
    "c7fcddbb25054b2cbfc067bb0d67c4d2":{
      "scriptId":"u67"},
    "914d11ad18e8426182106adb3f40d051":{
      "scriptId":"u68"},
    "02cf1f0a0f4349c18348f38b562d591f":{
      "scriptId":"u69"},
    "ad7281cdad2a4d8f8fe437bd1c0edda1":{
      "scriptId":"u70"},
    "1fcf3bace0964574acd5dc60e984d5c4":{
      "scriptId":"u71"},
    "9718bc525acf48e6b9aa0bc34a3fdf6b":{
      "scriptId":"u72"},
    "79c516661e60482fa61c19416dd7cf2b":{
      "scriptId":"u73"},
    "6f4d158391124545a1b84967ffa03d4d":{
      "scriptId":"u74"},
    "b8ba02d135db479f92bcb09e3bb0922a":{
      "scriptId":"u75"},
    "7ec426a1ff114a7c8dd846ef898f82dd":{
      "scriptId":"u76"},
    "97c4c17015124ba0b5850d796190c015":{
      "scriptId":"u77"},
    "7ddacb1af5e14f1fbcd969abd2d1f0ac":{
      "scriptId":"u78"},
    "598721cd44cd4775964cdda70efe0862":{
      "scriptId":"u79"},
    "0d9f89bb3d384bb0be2bad11ce7a4ba1":{
      "scriptId":"u80"},
    "557b30491042478bb384009f9223cf07":{
      "scriptId":"u81"},
    "b954e356ed144b98917af4c27c473d3d":{
      "scriptId":"u82"},
    "62ec7beb52964172b03fbabad947f19b":{
      "scriptId":"u83"},
    "ed1fa9de4c40431b952e4352c5c0a033":{
      "scriptId":"u84"},
    "1aecf8b8399a4d8682baa05ebe74d3cb":{
      "scriptId":"u85"},
    "90ff5ddbbab745a7a665d2befdb6ecaa":{
      "scriptId":"u86"},
    "46eba46e1c1c4e9aace1ed209b4eb5dd":{
      "scriptId":"u87"},
    "b53484e2e8534a3e8618930bd4a6adb3":{
      "scriptId":"u88"},
    "c2dd5f2a0e1e4f84a744c299ccbe6acf":{
      "scriptId":"u89"},
    "f610f00b694e49a0b59f7186bdbfcab5":{
      "scriptId":"u90"},
    "28c4c5280a7a40d8bcb343ad31ded29c":{
      "scriptId":"u91"},
    "f227feee580c4c9e98a5d31bd2760bdf":{
      "scriptId":"u92"}}});