$axure.loadCurrentPage({
  "url":"新闻详情.html",
  "generationDate":new Date(1420531287959.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79ea3717ec054b6ba1f9647f17094a39",
    "type":"Axure:Page",
    "name":"新闻详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"babaa70b302b4143a7a025954e2fa82b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"785bd01c2604463888a04ba09c0655ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d66d0a622d4295afe6beea47447e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"f5df211074744ce89ee86639b9ff7743",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee3db3ae93f49f794d60720971254ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻",
                      "target":{
                        "targetType":"page",
                        "url":"新闻.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"0a20fdc82f9a4da1b46616ddb3d0700d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":321,
              "height":508},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dfaf50f72e3416783c3f3dcc0a55e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":321,
                  "height":508},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻详情/u9.png"}},
{
          "id":"384c2c85daf0456183487fb42ad7a0e3",
          "label":"xinwen",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":342,
              "height":500}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6cf2b6e6477c46aeb57fb5b56e0586db",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3c05822d608f436e80380a1fb9ee5b4e",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":249},
                    "size":{
                      "width":302,
                      "height":401},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97f6b96b2e564301821debf91818619f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":249},
                        "size":{
                          "width":302,
                          "height":401},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u12.png"}},
{
                  "id":"c55adaa0e2f04327b4d5176e5a585754",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":14,
                      "y":200},
                    "size":{
                      "width":265,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12ac77238bfe4fb691ed14935e63ea15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":14,
                          "y":200},
                        "size":{
                          "width":265,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6f8a33553904a7d805d029a8a697e60",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":17,
                      "y":227},
                    "size":{
                      "width":144,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1bda485eb081452ab11f0e61cfbb3cd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":17,
                          "y":227},
                        "size":{
                          "width":144,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1b8b35041a084d16b968972b5babe338",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":321,
                      "height":190}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfd60e88ca6342ea82c80dc428256c18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":321,
                          "height":190}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u18.jpg"}},
{
                  "id":"fedb2f84a1dc4eb686fc853134b20932",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":262},
                    "size":{
                      "width":276,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af340eb59f3f4efe88f8dd63092fe2af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":262},
                        "size":{
                          "width":276,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4303bbaa60bd42559aa68fc8d0e1bc5d",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":301},
                    "size":{
                      "width":285,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ce83f17d0e249e990bd2c6689dcc53b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":301},
                        "size":{
                          "width":285,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7a9bdae6a3b04f3eb30fa3ae5fdfdc7e",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":341},
                    "size":{
                      "width":274,
                      "height":208}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ab5f9daff2b4b1ba3267f2b1b8af8c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":341},
                        "size":{
                          "width":274,
                          "height":208}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ebfda4c109946dfa39da64aa0bab1cb",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":555},
                    "size":{
                      "width":274,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abb5a1b5842e4034a7a10ca7bd760a65",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":555},
                        "size":{
                          "width":274,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35b6b6c7131b49d4adb05ecd7af11cae",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":129,
                      "y":163},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e11998cbee946edbe2184252458e1a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":129,
                          "y":163},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"5ec62ba161024fa2b503c487d0523b45",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":153,
                      "y":163},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d1ebf615ab446b881d9539796ec0dbd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":153,
                          "y":163},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"5a9c71b922bf49ec9f8757e941fdc243",
                  "label":"",
                  "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":177,
                      "y":163},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdd9b5d73d7643378e9834321894f9b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"384c2c85daf0456183487fb42ad7a0e3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":177,
                          "y":163},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "babaa70b302b4143a7a025954e2fa82b":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "785bd01c2604463888a04ba09c0655ed":{
      "scriptId":"u5"},
    "b4d66d0a622d4295afe6beea47447e06":{
      "scriptId":"u6"},
    "f5df211074744ce89ee86639b9ff7743":{
      "scriptId":"u7"},
    "7ee3db3ae93f49f794d60720971254ec":{
      "scriptId":"u8"},
    "0a20fdc82f9a4da1b46616ddb3d0700d":{
      "scriptId":"u9"},
    "0dfaf50f72e3416783c3f3dcc0a55e4f":{
      "scriptId":"u10"},
    "384c2c85daf0456183487fb42ad7a0e3":{
      "scriptId":"u11"},
    "3c05822d608f436e80380a1fb9ee5b4e":{
      "scriptId":"u12"},
    "97f6b96b2e564301821debf91818619f":{
      "scriptId":"u13"},
    "c55adaa0e2f04327b4d5176e5a585754":{
      "scriptId":"u14"},
    "12ac77238bfe4fb691ed14935e63ea15":{
      "scriptId":"u15"},
    "c6f8a33553904a7d805d029a8a697e60":{
      "scriptId":"u16"},
    "1bda485eb081452ab11f0e61cfbb3cd2":{
      "scriptId":"u17"},
    "1b8b35041a084d16b968972b5babe338":{
      "scriptId":"u18"},
    "bfd60e88ca6342ea82c80dc428256c18":{
      "scriptId":"u19"},
    "fedb2f84a1dc4eb686fc853134b20932":{
      "scriptId":"u20"},
    "af340eb59f3f4efe88f8dd63092fe2af":{
      "scriptId":"u21"},
    "4303bbaa60bd42559aa68fc8d0e1bc5d":{
      "scriptId":"u22"},
    "4ce83f17d0e249e990bd2c6689dcc53b":{
      "scriptId":"u23"},
    "7a9bdae6a3b04f3eb30fa3ae5fdfdc7e":{
      "scriptId":"u24"},
    "9ab5f9daff2b4b1ba3267f2b1b8af8c2":{
      "scriptId":"u25"},
    "6ebfda4c109946dfa39da64aa0bab1cb":{
      "scriptId":"u26"},
    "abb5a1b5842e4034a7a10ca7bd760a65":{
      "scriptId":"u27"},
    "35b6b6c7131b49d4adb05ecd7af11cae":{
      "scriptId":"u28"},
    "6e11998cbee946edbe2184252458e1a6":{
      "scriptId":"u29"},
    "5ec62ba161024fa2b503c487d0523b45":{
      "scriptId":"u30"},
    "5d1ebf615ab446b881d9539796ec0dbd":{
      "scriptId":"u31"},
    "5a9c71b922bf49ec9f8757e941fdc243":{
      "scriptId":"u32"},
    "fdd9b5d73d7643378e9834321894f9b8":{
      "scriptId":"u33"}}});