$axure.loadCurrentPage({
  "url":"我的订单-已支付.html",
  "generationDate":new Date(1420531296157.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9da419a50419441cb13c6d10aa600c57",
    "type":"Axure:Page",
    "name":"我的订单-已支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"880e8c0dbb19443cbf941615e3f91a2a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"875c2973ca8b49a2ae3f1c1bb73f0e76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b7d3c33ae684f1ca4f9ac83f7c42853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"5651dd20614b4a36a587c16a56c792e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2ce8b2d82b4fb6a19dd1517652e4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"6c56a8e1f0044717a06e84158d8911b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":176},
            "size":{
              "width":321,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9988e856f5ce4e5ca506e8e2bb11b3d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":176},
                "size":{
                  "width":321,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u9.png"}},
{
          "id":"cdad11b98c7848e99dacaeb886bbc0f0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":205},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"c027e25dd4a342e08f7363bf05cd1ce8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":82,
              "y":183},
            "size":{
              "width":56,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b787c261f5485abe99caf6a33aa06c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":183},
                "size":{
                  "width":56,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0822234dde0f4c44956336c9ff24c3bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":244,
              "y":183},
            "size":{
              "width":66,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9567bb2d48934ad8afbb6b1195ebc831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":244,
                  "y":183},
                "size":{
                  "width":66,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1900278800794ade862331c1d4b46809",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":223,
              "y":208},
            "size":{
              "width":91,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950ac258e31b4c9f8ff39e2bd0bc2d62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":223,
                  "y":208},
                "size":{
                  "width":91,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u16.png"}},
{
          "id":"8035a0ae8d0643a291e4ee3f427ac48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":223},
            "size":{
              "width":321,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"660c001bb5e4415480b5d066dbf5705c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":223},
                "size":{
                  "width":321,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u9.png"}},
{
          "id":"c2b10a297c974b16a6bd506364964961",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":262},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"379afb75c9fd4cbdb2b749ef2f7272bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":44,
              "y":238},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2660565b14c400f9385bc50852547f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":238},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a7f161e7964bbcb4dff1f5ffbea7f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":281},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea665b123a34edc8ba3380513194306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":281},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u18.png"}},
{
          "id":"f47ad64a7b374612967e42a1146be5c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":108,
              "y":282},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e792e080f645f08895cd67f1823d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":282},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f185dbe021a6435096ec186d50f7ceb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":286,
              "y":282},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc217a6e81a341368bc8f65aa6499b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":282},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d55cb81cbac24989aa3e206345f44cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":304},
            "size":{
              "width":132,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6645119385048fc90e2adf3cf343573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":304},
                "size":{
                  "width":132,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e597f6bd03cb4439861cbc32722975e6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":344},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"e203ac78cd824439814e697a924512bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":359},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c49ed5bc5504f0cbd037dd4102a6b6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":359},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74ee01ec6f13479590455edb19da3766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":245,
              "y":359},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afd6900eae664669ba0a7bddb12c3763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":245,
                  "y":359},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb016a4021984e6d956621050b71736d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":323,
              "y":311},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393049bdb1ff42fbb352f3e052df8090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":323,
                  "y":311},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"614e47f0640a4e418f334823879d06f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":273,
              "y":228},
            "size":{
              "width":69,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f37aa8e9424174b440441c8ff179d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":273,
                  "y":228},
                "size":{
                  "width":69,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品评价",
                      "target":{
                        "targetType":"page",
                        "url":"商品评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单/u38.png"}},
{
          "id":"5a7ae06b19314b7eb0c00047915f2e50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":398},
            "size":{
              "width":321,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9824926ffccb4ebcaef05e8b8dbbe0f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":398},
                "size":{
                  "width":321,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u9.png"}},
{
          "id":"b289ea45962f46098b73b47c09883237",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":437},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"293dffa14c804cdc8ef4ceff1f00ecad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":44,
              "y":413},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4199554527f04c66afd024d91a76c1f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":413},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fd49d94bf3c4e66a33754c9ae1773eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":456},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175e0d0c47ec43b0bfe2d3b53a417bd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":456},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u18.png"}},
{
          "id":"9a94ad3ef44d4dabaed0e49d134d68f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":108,
              "y":457},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5493b709104c66b1fe80451a5833dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":457},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02962be16a4f451aa00ae3e682f288ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":286,
              "y":457},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24eb52f6ffd94362a8a8c597c41e55e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":457},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"306070cc562d4f7db654e5f67ba02326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":479},
            "size":{
              "width":132,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644b1a69fdfd40e391aa7b40fb2af37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":479},
                "size":{
                  "width":132,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59be1dee767741fd942b9544e6012a03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":519},
            "size":{
              "width":298,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u11_line.png"}},
{
          "id":"f11a0cfacc6340a5b914b8099c170192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":141,
              "y":534},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332e0beb8c0b4c10912fb0bc91747c53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":534},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d68adb0299248f1afbe32830d31ba5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":245,
              "y":534},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38f327b2ea64e0cb45bff4c6a05a9a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":245,
                  "y":534},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f9d52d90fa74593847d38a90f5798ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":323,
              "y":486},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b779f73b77b64990983d3b24616b08d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":323,
                  "y":486},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd13b77bcc744e3f96ac118e7f44901b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":273,
              "y":403},
            "size":{
              "width":69,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f00b7c95584ae4a05fafa4db0778d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":273,
                  "y":403},
                "size":{
                  "width":69,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品评价",
                      "target":{
                        "targetType":"page",
                        "url":"商品评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的订单/u38.png"}},
{
          "id":"33b295dcdfd04fbd9aab0c003b100f92",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":178},
            "size":{
              "width":142,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "880e8c0dbb19443cbf941615e3f91a2a":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "875c2973ca8b49a2ae3f1c1bb73f0e76":{
      "scriptId":"u5"},
    "6b7d3c33ae684f1ca4f9ac83f7c42853":{
      "scriptId":"u6"},
    "5651dd20614b4a36a587c16a56c792e7":{
      "scriptId":"u7"},
    "0a2ce8b2d82b4fb6a19dd1517652e4b5":{
      "scriptId":"u8"},
    "6c56a8e1f0044717a06e84158d8911b3":{
      "scriptId":"u9"},
    "9988e856f5ce4e5ca506e8e2bb11b3d9":{
      "scriptId":"u10"},
    "cdad11b98c7848e99dacaeb886bbc0f0":{
      "scriptId":"u11"},
    "c027e25dd4a342e08f7363bf05cd1ce8":{
      "scriptId":"u12"},
    "70b787c261f5485abe99caf6a33aa06c":{
      "scriptId":"u13"},
    "0822234dde0f4c44956336c9ff24c3bc":{
      "scriptId":"u14"},
    "9567bb2d48934ad8afbb6b1195ebc831":{
      "scriptId":"u15"},
    "1900278800794ade862331c1d4b46809":{
      "scriptId":"u16"},
    "950ac258e31b4c9f8ff39e2bd0bc2d62":{
      "scriptId":"u17"},
    "8035a0ae8d0643a291e4ee3f427ac48e":{
      "scriptId":"u18"},
    "660c001bb5e4415480b5d066dbf5705c":{
      "scriptId":"u19"},
    "c2b10a297c974b16a6bd506364964961":{
      "scriptId":"u20"},
    "379afb75c9fd4cbdb2b749ef2f7272bc":{
      "scriptId":"u21"},
    "a2660565b14c400f9385bc50852547f6":{
      "scriptId":"u22"},
    "01a7f161e7964bbcb4dff1f5ffbea7f7":{
      "scriptId":"u23"},
    "cea665b123a34edc8ba3380513194306":{
      "scriptId":"u24"},
    "f47ad64a7b374612967e42a1146be5c7":{
      "scriptId":"u25"},
    "d7e792e080f645f08895cd67f1823d7e":{
      "scriptId":"u26"},
    "f185dbe021a6435096ec186d50f7ceb0":{
      "scriptId":"u27"},
    "cc217a6e81a341368bc8f65aa6499b42":{
      "scriptId":"u28"},
    "d55cb81cbac24989aa3e206345f44cba":{
      "scriptId":"u29"},
    "e6645119385048fc90e2adf3cf343573":{
      "scriptId":"u30"},
    "e597f6bd03cb4439861cbc32722975e6":{
      "scriptId":"u31"},
    "e203ac78cd824439814e697a924512bb":{
      "scriptId":"u32"},
    "4c49ed5bc5504f0cbd037dd4102a6b6a":{
      "scriptId":"u33"},
    "74ee01ec6f13479590455edb19da3766":{
      "scriptId":"u34"},
    "afd6900eae664669ba0a7bddb12c3763":{
      "scriptId":"u35"},
    "fb016a4021984e6d956621050b71736d":{
      "scriptId":"u36"},
    "393049bdb1ff42fbb352f3e052df8090":{
      "scriptId":"u37"},
    "614e47f0640a4e418f334823879d06f7":{
      "scriptId":"u38"},
    "18f37aa8e9424174b440441c8ff179d0":{
      "scriptId":"u39"},
    "5a7ae06b19314b7eb0c00047915f2e50":{
      "scriptId":"u40"},
    "9824926ffccb4ebcaef05e8b8dbbe0f7":{
      "scriptId":"u41"},
    "b289ea45962f46098b73b47c09883237":{
      "scriptId":"u42"},
    "293dffa14c804cdc8ef4ceff1f00ecad":{
      "scriptId":"u43"},
    "4199554527f04c66afd024d91a76c1f7":{
      "scriptId":"u44"},
    "6fd49d94bf3c4e66a33754c9ae1773eb":{
      "scriptId":"u45"},
    "175e0d0c47ec43b0bfe2d3b53a417bd1":{
      "scriptId":"u46"},
    "9a94ad3ef44d4dabaed0e49d134d68f7":{
      "scriptId":"u47"},
    "bd5493b709104c66b1fe80451a5833dd":{
      "scriptId":"u48"},
    "02962be16a4f451aa00ae3e682f288ac":{
      "scriptId":"u49"},
    "24eb52f6ffd94362a8a8c597c41e55e7":{
      "scriptId":"u50"},
    "306070cc562d4f7db654e5f67ba02326":{
      "scriptId":"u51"},
    "644b1a69fdfd40e391aa7b40fb2af37a":{
      "scriptId":"u52"},
    "59be1dee767741fd942b9544e6012a03":{
      "scriptId":"u53"},
    "f11a0cfacc6340a5b914b8099c170192":{
      "scriptId":"u54"},
    "332e0beb8c0b4c10912fb0bc91747c53":{
      "scriptId":"u55"},
    "1d68adb0299248f1afbe32830d31ba5c":{
      "scriptId":"u56"},
    "b38f327b2ea64e0cb45bff4c6a05a9a0":{
      "scriptId":"u57"},
    "4f9d52d90fa74593847d38a90f5798ff":{
      "scriptId":"u58"},
    "b779f73b77b64990983d3b24616b08d0":{
      "scriptId":"u59"},
    "fd13b77bcc744e3f96ac118e7f44901b":{
      "scriptId":"u60"},
    "38f00b7c95584ae4a05fafa4db0778d7":{
      "scriptId":"u61"},
    "33b295dcdfd04fbd9aab0c003b100f92":{
      "scriptId":"u62"}}});