$axure.loadCurrentPage({
  "url":"二手详情.html",
  "generationDate":new Date(1420531289917.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8694d2d6647f410d8a31c019beb8746c",
    "type":"Axure:Page",
    "name":"二手详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3afa16ce1e2d4688954346594eaf88e1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"c317025246f24250a302b038f60e5b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4d6f971fbc454296a72c8542bf9509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"1c0d53c986ed4d22ac8e83463b6ac18b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f2a78a138a346729ccbecd8384e696f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 二手列表",
                      "target":{
                        "targetType":"page",
                        "url":"二手列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"12a9bed7bfaf49f88d54d1984daf3eba",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":177},
            "size":{
              "width":340,
              "height":448}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43f843965f15483e9f322929cb0050f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1a8a4e899eb4b2ab794ee6d937b3d93",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":240},
                    "size":{
                      "width":302,
                      "height":360},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8df37ee7b904b8d9ebeec2d41b335aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":240},
                        "size":{
                          "width":302,
                          "height":360},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/二手详情/u10.png"}},
{
                  "id":"2678fdaaf87a4bc9b7f2e074871a7c81",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":11,
                      "y":171},
                    "size":{
                      "width":298,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b26a885b7ca74ec69ea92fb3a5ece85a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":11,
                          "y":171},
                        "size":{
                          "width":298,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f423229c0f194a55927ecd134f33e82e",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":215},
                    "size":{
                      "width":146,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87740ff5a62c4ae9a7c4656a4780c234",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":215},
                        "size":{
                          "width":146,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dbb36416351442529431cb0753183106",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":251},
                    "size":{
                      "width":60,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fee79e5d04bf4d4eb429d08b48f59c7e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":251},
                        "size":{
                          "width":60,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5e47224b2c5e418da97447a1772f9935",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-1},
                    "size":{
                      "width":320,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2772f3bfa8c45aeb568f173d84c97a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-1},
                        "size":{
                          "width":320,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/二手详情/u18.jpg"}},
{
                  "id":"1423001eb77d481aa021e671c34dda81",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":22,
                      "y":279},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fff8c67676674a79a51ee0abc938ca98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":22,
                          "y":279},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c00c41d6957d4e429d2ef3f6d2e34518",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":22,
                      "y":306},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c43c15a59341475d80f0156385280f3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":22,
                          "y":306},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3e9369deb51f43b4822b19573c178cf7",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":547},
                    "size":{
                      "width":302,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/招聘详情/u43_line.png"}},
{
                  "id":"62cecd1f6b6c47208075f27319ce38a0",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "lineSpacing":"20px",
                    "location":{
                      "x":22,
                      "y":334},
                    "size":{
                      "width":277,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7325a56094c4ef6acec0aa90ce3cd58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "lineSpacing":"20px",
                        "location":{
                          "x":22,
                          "y":334},
                        "size":{
                          "width":277,
                          "height":200}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a571843132284eedb5c8d80f2c706f59",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":22,
                      "y":567},
                    "size":{
                      "width":255,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b831ff8179a43bdbf6f0daa2497932f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":22,
                          "y":567},
                        "size":{
                          "width":255,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4b4da502e374444c97a256e229e5a057",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":129,
                      "y":137},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76c01adcb7ac45059f22381f58925392",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":129,
                          "y":137},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"58bfd6d5e2c44ee7be7b03f19653a260",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":153,
                      "y":137},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25eb79aebc4e43899d3a1ed05055a691",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":153,
                          "y":137},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"06a6b0831d804dfe92a0152d22d24a13",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9933},
                    "location":{
                      "x":177,
                      "y":137},
                    "size":{
                      "width":14,
                      "height":14},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37341927f9d240a2be827bc485b6a58d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9933},
                        "location":{
                          "x":177,
                          "y":137},
                        "size":{
                          "width":14,
                          "height":14},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新闻详情/u28.png"}},
{
                  "id":"cecd5a954b974b048d68c8e1ef376f1e",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":258,
                      "y":205},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4aebc3db35084822bccb4243bca98d6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":258,
                          "y":205},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u45.png"}},
{
                  "id":"eb27b4ec0020495fa427c9a2f8110bb7",
                  "label":"",
                  "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":288,
                      "y":209},
                    "size":{
                      "width":22,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe5c005dd83943beb8267cede7ed7680",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"12a9bed7bfaf49f88d54d1984daf3eba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":288,
                          "y":209},
                        "size":{
                          "width":22,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"39277184d9aa4083a25a217e9a92696e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":144},
            "size":{
              "width":27,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db6f037c8cb4a18b58620c9813522e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":144},
                "size":{
                  "width":27,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 cg",
                      "objectsToFades":[{
                          "objectPath":["1d171c90045847be906014fbf216ee7c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u20.png"}},
{
          "id":"c67496075f004aff865791355050173b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":144},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028fa829ec9d4101b67e4b3b89023315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":144},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 fenxiang 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/招聘详情/u18.png"}},
{
          "id":"aab7cf0731004a1dbb6063f361458723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":630},
            "size":{
              "width":321,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffcffd626934491ba1b4817d3c0e9542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":630},
                "size":{
                  "width":321,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u9.png"}},
{
          "id":"6f8c3531a05a4581a99350f0de717ba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":45,
              "y":638},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e6cd9a59834b29b527d474ba56b508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":45,
                  "y":638},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdc0f1ec55ba48f5b7732372e48595ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":44,
              "y":662},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0638b5778394269b54e303ecbef8f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":662},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"375b671e499a40d7a12792e2877db806",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":637},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘详情/u15_line.png"}},
{
          "id":"3e1f08a2dec649b6b69f756475ba02e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":641},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2c8ef2621f4595a9732d949fe5cec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":641},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘详情/u16.png"}},
{
          "id":"4cbf4f753cc242e9a322f99681861228",
          "label":"fenxiang",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":568},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ecbcb5d2268240b7a5a907e339ad6915",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4040fa465f8742558d24b3a26fee4c82",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":320,
                      "height":545},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ea0c13145f24082b9e863c59862d824",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":320,
                          "height":545},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u58.png"}},
{
                  "id":"6a0edb0ca1cd4d6ea80aa0c7e5597c23",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":304},
                    "size":{
                      "width":321,
                      "height":265},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a0aa6f46ff641d4a9c5254a90af1917",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":304},
                        "size":{
                          "width":321,
                          "height":265},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u60.png"}},
{
                  "id":"4e5a698539404713b8fe5dd2e6c7cb50",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":359},
                    "size":{
                      "width":320,
                      "height":4},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acf07dc8f6824d43bb07754cc070b79b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":359},
                        "size":{
                          "width":320,
                          "height":4},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u62.png"}},
{
                  "id":"5695acb419634a12947a39bcc21f0a20",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":144,
                      "y":322},
                    "size":{
                      "width":39,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54ce1ddc5ef1426cb285416850325c91",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":144,
                          "y":322},
                        "size":{
                          "width":39,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f435b98abc1b4c69b89629814b872fc2",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa83a050ea074ef284da2968cfc47cc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":20,
                          "y":507},
                        "size":{
                          "width":280,
                          "height":46},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u66.png"}},
{
                  "id":"17aab75fd845444e8ef608854af9e54b",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":507},
                    "size":{
                      "width":280,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 fenxiang 向下滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["4cbf4f753cc242e9a322f99681861228"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"77f1215fb7cd449c96684d8675ed9310",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ffe5ce6f3b941918bc094c240c84dee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u69.png"}},
{
                  "id":"90380fb2d93f4965962ad07679f1b6cd",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":192,
                      "y":376},
                    "size":{
                      "width":85,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c921e53aa593403b88406b2ea36027b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":192,
                          "y":376},
                        "size":{
                          "width":85,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/u71.png"}},
{
                  "id":"32f6f1b807574e4e88d1105e653f50bc",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":48,
                      "y":471},
                    "size":{
                      "width":72,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a72de691eb174be380904e67905f3347",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":48,
                          "y":471},
                        "size":{
                          "width":72,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f415bfb1ec2426592c5312cb93e8ac8",
                  "label":"",
                  "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":194,
                      "y":471},
                    "size":{
                      "width":83,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f54316d3784544889116cbdd7b5555d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cbf4f753cc242e9a322f99681861228",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":194,
                          "y":471},
                        "size":{
                          "width":83,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1d171c90045847be906014fbf216ee7c",
          "label":"cg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":118,
              "y":380},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eb7a97d572f54721a9a6c05ce7f91a16",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b6171c19ccaf4eeca9234185ead4d9b8",
                  "label":"cg",
                  "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":150,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeadfb91863141f6b16bd2b3697ca1d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d171c90045847be906014fbf216ee7c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFCC66,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":150,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/招聘详情/cg_u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "3afa16ce1e2d4688954346594eaf88e1":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "c317025246f24250a302b038f60e5b27":{
      "scriptId":"u5"},
    "1f4d6f971fbc454296a72c8542bf9509":{
      "scriptId":"u6"},
    "1c0d53c986ed4d22ac8e83463b6ac18b":{
      "scriptId":"u7"},
    "3f2a78a138a346729ccbecd8384e696f":{
      "scriptId":"u8"},
    "12a9bed7bfaf49f88d54d1984daf3eba":{
      "scriptId":"u9"},
    "e1a8a4e899eb4b2ab794ee6d937b3d93":{
      "scriptId":"u10"},
    "f8df37ee7b904b8d9ebeec2d41b335aa":{
      "scriptId":"u11"},
    "2678fdaaf87a4bc9b7f2e074871a7c81":{
      "scriptId":"u12"},
    "b26a885b7ca74ec69ea92fb3a5ece85a":{
      "scriptId":"u13"},
    "f423229c0f194a55927ecd134f33e82e":{
      "scriptId":"u14"},
    "87740ff5a62c4ae9a7c4656a4780c234":{
      "scriptId":"u15"},
    "dbb36416351442529431cb0753183106":{
      "scriptId":"u16"},
    "fee79e5d04bf4d4eb429d08b48f59c7e":{
      "scriptId":"u17"},
    "5e47224b2c5e418da97447a1772f9935":{
      "scriptId":"u18"},
    "c2772f3bfa8c45aeb568f173d84c97a0":{
      "scriptId":"u19"},
    "1423001eb77d481aa021e671c34dda81":{
      "scriptId":"u20"},
    "fff8c67676674a79a51ee0abc938ca98":{
      "scriptId":"u21"},
    "c00c41d6957d4e429d2ef3f6d2e34518":{
      "scriptId":"u22"},
    "c43c15a59341475d80f0156385280f3c":{
      "scriptId":"u23"},
    "3e9369deb51f43b4822b19573c178cf7":{
      "scriptId":"u24"},
    "62cecd1f6b6c47208075f27319ce38a0":{
      "scriptId":"u25"},
    "e7325a56094c4ef6acec0aa90ce3cd58":{
      "scriptId":"u26"},
    "a571843132284eedb5c8d80f2c706f59":{
      "scriptId":"u27"},
    "3b831ff8179a43bdbf6f0daa2497932f":{
      "scriptId":"u28"},
    "4b4da502e374444c97a256e229e5a057":{
      "scriptId":"u29"},
    "76c01adcb7ac45059f22381f58925392":{
      "scriptId":"u30"},
    "58bfd6d5e2c44ee7be7b03f19653a260":{
      "scriptId":"u31"},
    "25eb79aebc4e43899d3a1ed05055a691":{
      "scriptId":"u32"},
    "06a6b0831d804dfe92a0152d22d24a13":{
      "scriptId":"u33"},
    "37341927f9d240a2be827bc485b6a58d":{
      "scriptId":"u34"},
    "cecd5a954b974b048d68c8e1ef376f1e":{
      "scriptId":"u35"},
    "4aebc3db35084822bccb4243bca98d6b":{
      "scriptId":"u36"},
    "eb27b4ec0020495fa427c9a2f8110bb7":{
      "scriptId":"u37"},
    "fe5c005dd83943beb8267cede7ed7680":{
      "scriptId":"u38"},
    "39277184d9aa4083a25a217e9a92696e":{
      "scriptId":"u39"},
    "4db6f037c8cb4a18b58620c9813522e0":{
      "scriptId":"u40"},
    "c67496075f004aff865791355050173b":{
      "scriptId":"u41"},
    "028fa829ec9d4101b67e4b3b89023315":{
      "scriptId":"u42"},
    "aab7cf0731004a1dbb6063f361458723":{
      "scriptId":"u43"},
    "ffcffd626934491ba1b4817d3c0e9542":{
      "scriptId":"u44"},
    "6f8c3531a05a4581a99350f0de717ba2":{
      "scriptId":"u45"},
    "08e6cd9a59834b29b527d474ba56b508":{
      "scriptId":"u46"},
    "cdc0f1ec55ba48f5b7732372e48595ed":{
      "scriptId":"u47"},
    "b0638b5778394269b54e303ecbef8f8a":{
      "scriptId":"u48"},
    "375b671e499a40d7a12792e2877db806":{
      "scriptId":"u49"},
    "3e1f08a2dec649b6b69f756475ba02e5":{
      "scriptId":"u50"},
    "5f2c8ef2621f4595a9732d949fe5cec3":{
      "scriptId":"u51"},
    "4cbf4f753cc242e9a322f99681861228":{
      "scriptId":"u52"},
    "4040fa465f8742558d24b3a26fee4c82":{
      "scriptId":"u53"},
    "3ea0c13145f24082b9e863c59862d824":{
      "scriptId":"u54"},
    "6a0edb0ca1cd4d6ea80aa0c7e5597c23":{
      "scriptId":"u55"},
    "2a0aa6f46ff641d4a9c5254a90af1917":{
      "scriptId":"u56"},
    "4e5a698539404713b8fe5dd2e6c7cb50":{
      "scriptId":"u57"},
    "acf07dc8f6824d43bb07754cc070b79b":{
      "scriptId":"u58"},
    "5695acb419634a12947a39bcc21f0a20":{
      "scriptId":"u59"},
    "54ce1ddc5ef1426cb285416850325c91":{
      "scriptId":"u60"},
    "f435b98abc1b4c69b89629814b872fc2":{
      "scriptId":"u61"},
    "fa83a050ea074ef284da2968cfc47cc8":{
      "scriptId":"u62"},
    "17aab75fd845444e8ef608854af9e54b":{
      "scriptId":"u63"},
    "77f1215fb7cd449c96684d8675ed9310":{
      "scriptId":"u64"},
    "7ffe5ce6f3b941918bc094c240c84dee":{
      "scriptId":"u65"},
    "90380fb2d93f4965962ad07679f1b6cd":{
      "scriptId":"u66"},
    "c921e53aa593403b88406b2ea36027b6":{
      "scriptId":"u67"},
    "32f6f1b807574e4e88d1105e653f50bc":{
      "scriptId":"u68"},
    "a72de691eb174be380904e67905f3347":{
      "scriptId":"u69"},
    "0f415bfb1ec2426592c5312cb93e8ac8":{
      "scriptId":"u70"},
    "f54316d3784544889116cbdd7b5555d7":{
      "scriptId":"u71"},
    "1d171c90045847be906014fbf216ee7c":{
      "scriptId":"u72"},
    "b6171c19ccaf4eeca9234185ead4d9b8":{
      "scriptId":"u73"},
    "eeadfb91863141f6b16bd2b3697ca1d1":{
      "scriptId":"u74"}}});