$axure.loadCurrentPage({
  "url":"我的评论.html",
  "generationDate":new Date(1420531297092.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"210332e51c0c45e39d96a3ad6e83a660",
    "type":"Axure:Page",
    "name":"我的评论",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80afb418d1104816a260ad480e375e8a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fd462542d6194d0682aaa68c6022e877"},
{
          "id":"d54841e5106e46bd93dcb48718b66a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":321,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d3af0e091948a3997a64e05584ec7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":32,
                  "y":136},
                "size":{
                  "width":321,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u5.png"}},
{
          "id":"b1fb470cd93c4185808fc27aa2358ede",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":143},
            "size":{
              "width":28,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40054f136da74d8eaa90c1b27f49df8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":143},
                "size":{
                  "width":28,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u7.png"}},
{
          "id":"7248e918a2744bab880c747400c4551f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":210},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5db303b344f43578478256c279fc812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":210},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u19.png"}},
{
          "id":"52340051a9ef4e469eb7191ba9fa9f48",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":270},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"4a3d14be5b0c451387284e4db2684754",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":189},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6703287d5bd64e588478831db5b7c385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":189},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b38d1038fdc14994a0eb3195e702fd9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":249},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea66964efe4e40e98c638f4170662e7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":249},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3328bb44d76412296828c9e20dfb8d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":186},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009a819625704f9e8b3f6c4a8e489e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":186},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购列表/u26.jpg"}},
{
          "id":"96c38b1ae51144a39db53b96128046e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":156,
              "y":246},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d404c3105d411ea279e8f9e6e025fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":246},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c0cf8bd75de4b9ebbfcbc2c669a3f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":205,
              "y":248},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5508343e4aed43808ffe1e56a393afdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":248},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58303de64e6d4d56975388598569b20b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":251},
            "size":{
              "width":46,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/团购列表/u37_line.png"}},
{
          "id":"8fca2d6c4b374263b54019cf4e2a1e3e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":371},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"768cca2420cb40c09218bfe666416b94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":290},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5279c182f3914720bf48a3b6ca99a838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":290},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d040485ba3544c2b92133af6324768dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":351},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4662717b4ed744298ce5643fee8ec588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":351},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44c281025604469dbf077bf6fe7e4ceb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":286},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3cca651aa5940de85a880997964710c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":286},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺/u100.jpg"}},
{
          "id":"f3e6b3148436478d9a00da9c20535b4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":310},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43db803d58a34c07b5337db5db9cde67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":310},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u17.png"}},
{
          "id":"ab399bf6b1b641f68aa2d83ccc9e59a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":410},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98328440f5534c4f8355a52fa30926b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":410},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u19.png"}},
{
          "id":"5ce84bdf41744a368de72cb21e6bf393",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":469},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"102a33d2fbfc41958cc51778de015bc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":389},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cf9a698f5941809cc854d31f29db23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":389},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a46f478c66d8437b842ae60e37cd5999",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":450},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"643ecdff0e5f41209c8a71bcb5d2b320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":450},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdabeafc9e914eed841aeb5659d2af4e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":270},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"08c58339a196472a9f491a1db2dee853",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":385},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2966b7a68d124d2488a284c9303ae593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":385},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购列表/u26.jpg"}},
{
          "id":"eeeb4fe2734a45249cdf3cbd28d9610a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":156,
              "y":347},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f47e69fcfdc449383d9c81aafd95331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":347},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56ce5501023140eca996a73c4ad39ffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":205,
              "y":350},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecba1aa066f34daf88e605030360fc20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":350},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce6eb689847f4a40b45caf59460d79af",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":353},
            "size":{
              "width":39,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择尺码颜色/u23_line.png"}},
{
          "id":"e8af0244f6a64757b9884dc329c53f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":156,
              "y":447},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5000373407764e32b2db980568d97492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":447},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec20d6b548534045948779f50690b159",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":205,
              "y":449},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ccf20fb27b480397dcaccbfd7dedd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":449},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26ad024edfd64a1982649ea914f93126",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":452},
            "size":{
              "width":46,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/团购列表/u37_line.png"}},
{
          "id":"3c3f4e6b9986411ca56d3a23357b41b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":156,
              "y":229},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8713b327d881413fb36889379f2e6c39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":229},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6516f86b20094daa8fd874db011209e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":288,
              "y":191},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f7f70b3413a4c95bf9fd50a0b5792ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":191},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71f144aa81864586885e2c7b71335f57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":156,
              "y":329},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e71b5e7b6f4149b48ea56589074067a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":329},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f66033baee034360a5ec4bf3ef59a80e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":288,
              "y":291},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18bfc5fd93de44b1bdf59cf1fb513232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":291},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6ef3e493c90418f950b4c3f64bb1fc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":156,
              "y":428},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e25a81496548e1a28ce4698a1d1b87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":428},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"484928e37e1442e68b9a4e9a3ce28039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":288,
              "y":390},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee88009d6f60493a88b2904591913b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":390},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"707a5c8f65bd4969ace23c7304f9eff3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":568},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"50ecc30d0cb1499fb9d17bba0f0e13c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":487},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0dcdd4d1eda48a39d97a536a67abd91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":487},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d75212e5f18245e5999c91fc1a4f950d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":548},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c93259ddf8c4c8290f0363d46dcf3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":548},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9033f546187f4d44ab62356a866fd0c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":483},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"407a5e7edc51443b9657455dc9054406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":483},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺/u100.jpg"}},
{
          "id":"d32ea8a70e5e456c8a4daa3b902ad3ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":507},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e7acac99a1047958f7937d1a04bcd91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":507},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u17.png"}},
{
          "id":"78d5348119e24874b35306f3fa8d3b2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":607},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f3f3331a044b048e423defb306caa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":607},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺列表/u19.png"}},
{
          "id":"7d3b37e167734e239b8501594a006f08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":666},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻/u42_line.png"}},
{
          "id":"5ccf5b87ce5b4f76830008b9e059d00e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":586},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d13642174b54f6c921ca36f09f4eb65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":586},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0492013cdd249528eed163ab38448f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":647},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7127ab93fee466db92fccc1bf8ef64b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":647},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe97627fab044f5e8a363d43103e7e15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":582},
            "size":{
              "width":106,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325622360f464a3c85f9f7cb19098fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":582},
                "size":{
                  "width":106,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购列表/u26.jpg"}},
{
          "id":"d7ef9bb8f7e8460c8bc5fdb88a8a25af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":156,
              "y":544},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0db527e5e2ac4a0ca0b32d548e206c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":544},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb8f147e2f864364a31d9417a9cdfa61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":205,
              "y":547},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2f18f65e5f45629d29039ced0ae4bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":547},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d0c6ca4f52145d99c05156fb820dd16",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":550},
            "size":{
              "width":39,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择尺码颜色/u23_line.png"}},
{
          "id":"fa5dfb232bec43d9ad0e65c1ca09e7b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":156,
              "y":644},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"febe72f4ee3c4116926ec17ae92058ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":644},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"825b3ee6716a4e43854783994e35e738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":205,
              "y":646},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5e39f4e068488fabd90f869ddeb094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":646},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4d847c5131a45888c45e392d678b8c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":649},
            "size":{
              "width":46,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/团购列表/u37_line.png"}},
{
          "id":"6411d0b0ec5241eebeac80f64cb24cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":156,
              "y":526},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f145ceebd14270adf6fedbbe599e81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":526},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea9546c502304108a3c5d90dfe7b0446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":288,
              "y":488},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f94c9d839e141d483a48e2db7f5108b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":488},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb6af2a897724edda25a800ef866656e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":156,
              "y":625},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe1284e6d754dd090a4f8fee3152a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":625},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd94dcfa062e4170af1b0c9d28a0d9d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":288,
              "y":587},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ebb4658d9a14e569b1bd95111b40f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":587},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fd462542d6194d0682aaa68c6022e877":{
      "packageId":"fd462542d6194d0682aaa68c6022e877",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ccb7730bef2c48599bcfa1591173a024",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":381,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7d3ed0c2e4b4c81aad08f4172ac3834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":381,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u1.png"}},
{
            "id":"29e2fb20aa814bcdac64c749d8a5d691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":36,
                "y":120},
              "size":{
                "width":308,
                "height":13},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7dfaea41526490a87ddf7a2dc7280c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":36,
                    "y":120},
                  "size":{
                    "width":308,
                    "height":13},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/引导页/u3.png"}}]}}},
  "objectPaths":{
    "80afb418d1104816a260ad480e375e8a":{
      "scriptId":"u0",
      "ccb7730bef2c48599bcfa1591173a024":{
        "scriptId":"u1"},
      "c7d3ed0c2e4b4c81aad08f4172ac3834":{
        "scriptId":"u2"},
      "29e2fb20aa814bcdac64c749d8a5d691":{
        "scriptId":"u3"},
      "d7dfaea41526490a87ddf7a2dc7280c7":{
        "scriptId":"u4"}},
    "d54841e5106e46bd93dcb48718b66a33":{
      "scriptId":"u5"},
    "42d3af0e091948a3997a64e05584ec7a":{
      "scriptId":"u6"},
    "b1fb470cd93c4185808fc27aa2358ede":{
      "scriptId":"u7"},
    "40054f136da74d8eaa90c1b27f49df8c":{
      "scriptId":"u8"},
    "7248e918a2744bab880c747400c4551f":{
      "scriptId":"u9"},
    "e5db303b344f43578478256c279fc812":{
      "scriptId":"u10"},
    "52340051a9ef4e469eb7191ba9fa9f48":{
      "scriptId":"u11"},
    "4a3d14be5b0c451387284e4db2684754":{
      "scriptId":"u12"},
    "6703287d5bd64e588478831db5b7c385":{
      "scriptId":"u13"},
    "b38d1038fdc14994a0eb3195e702fd9b":{
      "scriptId":"u14"},
    "ea66964efe4e40e98c638f4170662e7c":{
      "scriptId":"u15"},
    "e3328bb44d76412296828c9e20dfb8d3":{
      "scriptId":"u16"},
    "009a819625704f9e8b3f6c4a8e489e95":{
      "scriptId":"u17"},
    "96c38b1ae51144a39db53b96128046e3":{
      "scriptId":"u18"},
    "20d404c3105d411ea279e8f9e6e025fe":{
      "scriptId":"u19"},
    "9c0cf8bd75de4b9ebbfcbc2c669a3f23":{
      "scriptId":"u20"},
    "5508343e4aed43808ffe1e56a393afdd":{
      "scriptId":"u21"},
    "58303de64e6d4d56975388598569b20b":{
      "scriptId":"u22"},
    "8fca2d6c4b374263b54019cf4e2a1e3e":{
      "scriptId":"u23"},
    "768cca2420cb40c09218bfe666416b94":{
      "scriptId":"u24"},
    "5279c182f3914720bf48a3b6ca99a838":{
      "scriptId":"u25"},
    "d040485ba3544c2b92133af6324768dc":{
      "scriptId":"u26"},
    "4662717b4ed744298ce5643fee8ec588":{
      "scriptId":"u27"},
    "44c281025604469dbf077bf6fe7e4ceb":{
      "scriptId":"u28"},
    "f3cca651aa5940de85a880997964710c":{
      "scriptId":"u29"},
    "f3e6b3148436478d9a00da9c20535b4d":{
      "scriptId":"u30"},
    "43db803d58a34c07b5337db5db9cde67":{
      "scriptId":"u31"},
    "ab399bf6b1b641f68aa2d83ccc9e59a8":{
      "scriptId":"u32"},
    "98328440f5534c4f8355a52fa30926b6":{
      "scriptId":"u33"},
    "5ce84bdf41744a368de72cb21e6bf393":{
      "scriptId":"u34"},
    "102a33d2fbfc41958cc51778de015bc2":{
      "scriptId":"u35"},
    "32cf9a698f5941809cc854d31f29db23":{
      "scriptId":"u36"},
    "a46f478c66d8437b842ae60e37cd5999":{
      "scriptId":"u37"},
    "643ecdff0e5f41209c8a71bcb5d2b320":{
      "scriptId":"u38"},
    "fdabeafc9e914eed841aeb5659d2af4e":{
      "scriptId":"u39"},
    "08c58339a196472a9f491a1db2dee853":{
      "scriptId":"u40"},
    "2966b7a68d124d2488a284c9303ae593":{
      "scriptId":"u41"},
    "eeeb4fe2734a45249cdf3cbd28d9610a":{
      "scriptId":"u42"},
    "0f47e69fcfdc449383d9c81aafd95331":{
      "scriptId":"u43"},
    "56ce5501023140eca996a73c4ad39ffd":{
      "scriptId":"u44"},
    "ecba1aa066f34daf88e605030360fc20":{
      "scriptId":"u45"},
    "ce6eb689847f4a40b45caf59460d79af":{
      "scriptId":"u46"},
    "e8af0244f6a64757b9884dc329c53f6a":{
      "scriptId":"u47"},
    "5000373407764e32b2db980568d97492":{
      "scriptId":"u48"},
    "ec20d6b548534045948779f50690b159":{
      "scriptId":"u49"},
    "30ccf20fb27b480397dcaccbfd7dedd0":{
      "scriptId":"u50"},
    "26ad024edfd64a1982649ea914f93126":{
      "scriptId":"u51"},
    "3c3f4e6b9986411ca56d3a23357b41b9":{
      "scriptId":"u52"},
    "8713b327d881413fb36889379f2e6c39":{
      "scriptId":"u53"},
    "6516f86b20094daa8fd874db011209e6":{
      "scriptId":"u54"},
    "0f7f70b3413a4c95bf9fd50a0b5792ef":{
      "scriptId":"u55"},
    "71f144aa81864586885e2c7b71335f57":{
      "scriptId":"u56"},
    "e71b5e7b6f4149b48ea56589074067a2":{
      "scriptId":"u57"},
    "f66033baee034360a5ec4bf3ef59a80e":{
      "scriptId":"u58"},
    "18bfc5fd93de44b1bdf59cf1fb513232":{
      "scriptId":"u59"},
    "c6ef3e493c90418f950b4c3f64bb1fc4":{
      "scriptId":"u60"},
    "e2e25a81496548e1a28ce4698a1d1b87":{
      "scriptId":"u61"},
    "484928e37e1442e68b9a4e9a3ce28039":{
      "scriptId":"u62"},
    "ee88009d6f60493a88b2904591913b1b":{
      "scriptId":"u63"},
    "707a5c8f65bd4969ace23c7304f9eff3":{
      "scriptId":"u64"},
    "50ecc30d0cb1499fb9d17bba0f0e13c5":{
      "scriptId":"u65"},
    "e0dcdd4d1eda48a39d97a536a67abd91":{
      "scriptId":"u66"},
    "d75212e5f18245e5999c91fc1a4f950d":{
      "scriptId":"u67"},
    "8c93259ddf8c4c8290f0363d46dcf3d5":{
      "scriptId":"u68"},
    "9033f546187f4d44ab62356a866fd0c4":{
      "scriptId":"u69"},
    "407a5e7edc51443b9657455dc9054406":{
      "scriptId":"u70"},
    "d32ea8a70e5e456c8a4daa3b902ad3ed":{
      "scriptId":"u71"},
    "3e7acac99a1047958f7937d1a04bcd91":{
      "scriptId":"u72"},
    "78d5348119e24874b35306f3fa8d3b2d":{
      "scriptId":"u73"},
    "52f3f3331a044b048e423defb306caa3":{
      "scriptId":"u74"},
    "7d3b37e167734e239b8501594a006f08":{
      "scriptId":"u75"},
    "5ccf5b87ce5b4f76830008b9e059d00e":{
      "scriptId":"u76"},
    "9d13642174b54f6c921ca36f09f4eb65":{
      "scriptId":"u77"},
    "f0492013cdd249528eed163ab38448f3":{
      "scriptId":"u78"},
    "f7127ab93fee466db92fccc1bf8ef64b":{
      "scriptId":"u79"},
    "fe97627fab044f5e8a363d43103e7e15":{
      "scriptId":"u80"},
    "325622360f464a3c85f9f7cb19098fde":{
      "scriptId":"u81"},
    "d7ef9bb8f7e8460c8bc5fdb88a8a25af":{
      "scriptId":"u82"},
    "0db527e5e2ac4a0ca0b32d548e206c79":{
      "scriptId":"u83"},
    "cb8f147e2f864364a31d9417a9cdfa61":{
      "scriptId":"u84"},
    "6d2f18f65e5f45629d29039ced0ae4bc":{
      "scriptId":"u85"},
    "7d0c6ca4f52145d99c05156fb820dd16":{
      "scriptId":"u86"},
    "fa5dfb232bec43d9ad0e65c1ca09e7b3":{
      "scriptId":"u87"},
    "febe72f4ee3c4116926ec17ae92058ac":{
      "scriptId":"u88"},
    "825b3ee6716a4e43854783994e35e738":{
      "scriptId":"u89"},
    "eb5e39f4e068488fabd90f869ddeb094":{
      "scriptId":"u90"},
    "a4d847c5131a45888c45e392d678b8c6":{
      "scriptId":"u91"},
    "6411d0b0ec5241eebeac80f64cb24cc5":{
      "scriptId":"u92"},
    "d4f145ceebd14270adf6fedbbe599e81":{
      "scriptId":"u93"},
    "ea9546c502304108a3c5d90dfe7b0446":{
      "scriptId":"u94"},
    "5f94c9d839e141d483a48e2db7f5108b":{
      "scriptId":"u95"},
    "fb6af2a897724edda25a800ef866656e":{
      "scriptId":"u96"},
    "6fe1284e6d754dd090a4f8fee3152a5d":{
      "scriptId":"u97"},
    "fd94dcfa062e4170af1b0c9d28a0d9d7":{
      "scriptId":"u98"},
    "0ebb4658d9a14e569b1bd95111b40f02":{
      "scriptId":"u99"}}});